### ISSUE TITLE
Resolution of Uncaught TypeError: Object [object Object] has no method 'call'

### ISSUE THREAD

**Issue by iies** [gree/unity-webview#10]
Thank you for great library for Unity 3D. But I found one bug that native code can't catch callback from javascript. This problem appears only over Android 4.2.

So I have found on google. This is hint I found : http://stackoverflow.com/questions/14031635/android-4-2-1-webview-and-javascript-interface-breaks

I changed build target to 4.2.2 and modified code like below. (just @JavascriptInterface added)
```java
class WebViewPluginInterface
{
	private String mGameObject;

	public WebViewPluginInterface(final String gameObject)
	{
		mGameObject = gameObject;
	}

	@JavascriptInterface
	public void call(String message)
	{
		UnityPlayer.UnitySendMessage(mGameObject, "CallFromJS", message);
	}
}
```

In result, this is work fine after added an annotation.

**Comment by thanh06** [comment]
@splhack  you can upload WebViewPlugin.rar fix version for me?
Thanks you

**Comment by nhiepphong** [comment]
I can't scroll and touch the website in Android.
It's ok in iOS.

**Comment by KojiNakamaru** [comment]
The latest version (https://github.com/gree/unity-webview/tree/39d08af311278693abb8c57129dc1b434b062c25) should have no problem.  Please try the latest `sample/` and `dist/unity-webview.unitypackage`.
