### ISSUE TITLE
JavascriptInterface

### ISSUE THREAD

**Issue by SherAlex1998** [gree/unity-webview#1007]
How can I handle events on a loaded page like in Android?

```
class WebJsInterface {

    @JavascriptInterface
    fun Fun(value: String) {
        //your code
    }
}
```

There are 4 functions that a page can call. It would be cool to create a similar class in C# and somehow connect it to webview.

I will be very grateful for your help.

**Comment by KojiNakamaru** [comment]
* You can detect a loaded page by the `ld:` callback, in which you can inject any javascript function by `EvaluateJS()`.
* You can send a string from Javascript to C# by `Unity.call(msg)` where `msg` will be received by the `cb:` callback.

https://github.com/gree/unity-webview/blob/61554b59e97f6d58466b3844eb596e8a49704fb8/sample/Assets/Scripts/SampleWebView.cs#L68-L113

For example, you can define `Fun` that sends a `'fun'` from Javascript to C# as below:

```c#
        webViewObject.Init(
            cb: (msg) =>
            {
                Debug.Log(msg);
            },
            ...
            ld: (msg) =>
            {
                webViewObject.EvaluateJS("function Fun() { Unity.call('fun'); }");
            });
```

**Comment by SherAlex1998** [comment]
@KojiNakamaru Thank you for your reply!
I have an obfuscated HTML page that I don't have access to. There are 4 functions with the given names. I need to somehow handle the call of these functions by the type of this:
`class WebJsInterface {

    @JavascriptInterface
    fun onGetToken(token: String) {
        //your code
    }
}`
Does it mean that it will not work to achieve the same behavior as on android?
Do I need to build a custom page?

**Comment by KojiNakamaru** [comment]
> Does it mean that it will not work to achieve the same behavior as on android?

I cannot understand what you really want. JavaScriptInterface requires a class name to bind functions as below:

```java
class WebJsInterface {
    @JavaScriptInterface
    void onGetToken(String token) {
    }
}

...

webView.addJavascriptInterface(new WebJsInterface(), "MyClass");
```

so do you want to override a function in the form of `MyClass.onGetToken()`?

> Is it possible to handle any calls from the page that were written in advance?

At least after you inject javascript functions, they should be called adequately. If `getToken()` is defined globally in the html:

```html
<script>
  function getToken(token) {
     // do something
  }
</script>
```

you can override it as below:

```c#
        webViewObject.Init(
            cb: (msg) =>
            {
                Debug.Log(msg);
            },
            ...
            ld: (msg) =>
            {
                webViewObject.EvaluateJS("function getToken(token) { Unity.call(token); }");
            });
```

However, if `getToken()` is obfuscated and is renamed to any other name and/or is defined not globally, you cannot override it with the above code.
