### ISSUE TITLE
Android global table reference overflow when using UNITYWEBVIEW_ANDROID_FORCE_MARGIN_ADJUSTMENT_FOR_KEYBOARD

### ISSUE THREAD

**Issue by Wave1** [gree/unity-webview#1012]
After updating to latest webview version my app started crashing after running for a few minutes.  I'm using the UNITYWEBVIEW_ANDROID_FORCE_MARGIN_ADJUSTMENT_FOR_KEYBOARD option as my app needs to work in portrait and landscape and without it text input fields can get hidden behind the on screen keyboard.

The crash was caused by the global reference table reaching its maximum size.  The crash output showed there were 25787 instances of java.lang.Class, 16803 instances of com.unity3d.player.UnityPlayer and 8408 instances of my custom application Activity class.

These instances were being created by the AdjustBottomMargin method in WebViewObject.cs.  The final else block was being called every frame in my app and this was causing the unreleased allocations in line 368:

`AndroidJavaObject View = UnityClass.GetStatic<AndroidJavaObject>("currentActivity").Get<AndroidJavaObject>("mUnityPlayer").Call<AndroidJavaObject>("getView");`

I managed to fix this by breaking this line of code up into the following (making use of C# 8's new support for not having to enclose code in braces after a using statement):

```
using AndroidJavaObject lCurrentActivity = UnityClass.GetStatic<AndroidJavaObject>("currentActivity");
using AndroidJavaObject lUnityPlayer = lCurrentActivity.Get<AndroidJavaObject>("mUnityPlayer");
using AndroidJavaObject View = lUnityPlayer.Call<AndroidJavaObject>("getView");
```

I'm not sure if the "using" in the final line is strictly necessary, and I'm also wondering if it's possible to cache the "currentActivity" and "mUnityPlayer" instances once when the WebViewObject has been created.  I haven't tried this as I'm not sure whether the life cycle of these objects allows them to be destroyed and recreated.

Just wanted to let you know about it as I believe the AdjustBottomMargin method would be slowly building up references whenever the keyboard is opened or closed when not using the UNITYWEBVIEW_ANDROID_FORCE_MARGIN_ADJUSTMENT_FOR_KEYBOARD option.

**Comment by KojiNakamaru** [comment]
Thank you very much for your detailed analysis and explanation. I introduced #1013 to utilize `using` for every AndroidJavaObject. As you discussed, we could further reduce `using` by caching some of AndroidJavaObjects and/or by realizing the logic in java, but those can be considered later and the fix should be minimal and sufficient.

BTW, I also introduced #1014 and #1015 to make an acitveEmenet (such as an input tag currently focused) visible on device orientation change. If you want to import only #1013, you can get binaries from faac7c8d6383d7d30c5c0973b8f6fedf5d94565c .

**Comment by Wave1** [comment]
Glad to have been able to give something back to your great plugin, and thanks for the new functionality for active elements.  I haven't had a chance to try this out yet, but I will now mark this issue as complete as the main problem I was facing has now been fixed.
