### ISSUE TITLE
Logging in website by setting cookie, or HTTP post request

### ISSUE THREAD

**Issue by abdojapan** [gree/unity-webview#102]
Hi,

I have a backend/frontend word-press website that is used along with my unity game.
I want to allow a user to 'guest login', by creating a random user/pass register it to the server, save it, then login programmatically without forcing the user to enter user/pass.

To do that I have to set webview cookie directly, or send a POST request with the saved user/pass to allow the user to login.

Is either of those ways supported?

Thanks for advance.

**Comment by KojiNakamaru** [comment]
You can utilize EvaluateJS() to send a POST request as below (maybe cookie can also be handled in a similar way):
```c#
    webViewObject.Init(...);
    webViewObject.SetMargins(...);
    webViewObject.SetVisibility(true);
    var js
        = "(function() {"
        + "  var form, parameter; "
        + "  form = document.createElement('form'); "
        + "  form.method = 'post'; "
        + "  form.action = 'https://your.wordpress.site/?action=login'; "
        + "  parameter = document.createElement('input'); "
        + "  parameter.type = 'hidden'; "
        + "  parameter.name = 'user'; "
        + "  parameter.value  = '" + user + "'; "
        + "  form.appendChild(parameter); "
        + "  parameter = document.createElement('input'); "
        + "  parameter.type = 'hidden'; "
        + "  parameter.name = 'pass'; "
        + "  parameter.value = '" + pass + "'; "
        + "  form.appendChild(parameter); "
        + "  document.body.appendChild(form); "
        + "  form.submit(); "
        + "  document.body.removeChild(form); "
        + "})();";
    webViewObject.EvaluateJS(js);
```

**Comment by abdojapan** [comment]
Thank you very much for your detailed reply!

**Comment by gupta-vaibhav** [comment]
Hi, I am trying to do something similar, the only difference being that the javascript is embedded in the html that is opened in the webview. The javascript is called upon tapping on the 'Submit' button. The javascript is being called fine, the request is hitting the server, however, the request received has empty body.

For further debugging, I have tried the following:
- When I open the page in Chrome browser and hit the submit button, I get the request with all the form data as expected. Thus the javascript seems to be working fine.
- Just before the `form.submit()` I have called a `alert("form has " + form.length + " members)` code to print the number of members in the form. In the browser, as well as the webview, the number of elements shown is as expected. Thus even in the webview, the form is being populated fine. 

Still, when I submit the form through the webview, the request is received with an empty body. Could you suggest what do I need to do here?

Thanks,
