### ISSUE TITLE
iPhone does not respond to taps.

### ISSUE THREAD

**Issue by pi-taro** [gree/unity-webview#1024]
Hello. I am using unity-webview to display webRTC. It works fine on Android, but does not respond to taps on iPhone. The UI behind it responds to taps. The implementation is the same as the sample, but a new GameObject is created from the GameObject, which is singletonized so that it can be called from multiple locations. How do I make my iPhone respond to taps?

**Comment by KojiNakamaru** [comment]
Could you please provide a minimum sample app that reproduces the issue? At least the sample app with the latest binaries (https://github.com/gree/unity-webview/tree/1235da5a7461ccc83dd1274caba45c203b9aa37d/dist) works okay for https://webrtc.github.io/samples/src/content/getusermedia/gum/ . My environment/settings are the following:

* Unity 2020.3.48f1
* iPhone SE 3rd gen (iOS 17.1.2)
* NSCameraUsageDescription and NSMicrophoneUsageDescription are defined

**Comment by pi-taro** [comment]
really sorry.
I was operating an instance that could not be connected to GameObject.
The problem was not caused by unity-webview.
