### ISSUE TITLE
user-scalable=yes sometimes doesn't work (pinch zoom)

### ISSUE THREAD

**Issue by CDAfonso** [gree/unity-webview#1025]
Hello! 
I have user-scalable=yes on my pages and sometimes it doesn't work, ie: when the webview loads another page that doesn't have user-scalable=yes and i return to the one who does.

Is there a turnarround for this?

Thank you!

**Comment by KojiNakamaru** [comment]
I uploaded https://github.com/gree/unity-webview/tree/example-for-1025/sample that can be directly opened and built with unity 2020.3.48f1, where

* sample.html defines `user-scalable=yes` and sample2.html defines `user-scalable=no`.
* sample.html has a link to sample2.html and vice versa.

This sample works correctly on my devices (iPhone SE3 (iOS 17.1.2), OSCAL Pad8 (Android 11)). It is helpful if you can provide a concrete example that reproduces the issue.

BTW, if you want to always allow user-scaling (for iOS), the following modification should work.

```diff
--- a/Assets/Plugins/iOS/WebView.mm
+++ b/Assets/Plugins/iOS/WebView.mm
@@ -161,6 +161,7 @@ static NSMutableArray *_instances = [[NSMutableArray alloc] init];
             _sharedProcessPool = [[WKProcessPool alloc] init];
         }
         WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
+        configuration.ignoresViewportScaleLimits = true;
         WKUserContentController *controller = [[WKUserContentController alloc] init];
         [controller addScriptMessageHandler:[[WeakScriptMessageDelegate alloc] initWithDelegate:self] name:@"unityControl"];
         [controller addScriptMessageHandler:[[WeakScriptMessageDelegate alloc] initWithDelegate:self] name:@"saveDataURL"];
```

**Comment by CDAfonso** [comment]
> I uploaded https://github.com/gree/unity-webview/tree/example-for-1025/sample that can be directly opened and built with unity 2020.3.48f1, where
> 
> * sample.html defines `user-scalable=yes` and sample2.html defines `user-scalable=no`.
> * sample.html has a link to sample2.html and vice versa.
> 
> This sample works correctly on my devices (iPhone SE3 (iOS 17.1.2), OSCAL Pad8 (Android 11)). It is helpful if you can provide a concrete example that reproduces the issue.
> 
> BTW, if you want to always allow user-scaling (for iOS), the following modification should work.
> 
> ```diff
> --- a/Assets/Plugins/iOS/WebView.mm
> +++ b/Assets/Plugins/iOS/WebView.mm
> @@ -161,6 +161,7 @@ static NSMutableArray *_instances = [[NSMutableArray alloc] init];
>              _sharedProcessPool = [[WKProcessPool alloc] init];
>          }
>          WKWebViewConfiguration *configuration = [[WKWebViewConfiguration alloc] init];
> +        configuration.ignoresViewportScaleLimits = true;
>          WKUserContentController *controller = [[WKUserContentController alloc] init];
>          [controller addScriptMessageHandler:[[WeakScriptMessageDelegate alloc] initWithDelegate:self] name:@"unityControl"];
>          [controller addScriptMessageHandler:[[WeakScriptMessageDelegate alloc] initWithDelegate:self] name:@"saveDataURL"];
> ```

Thank you! I will test it out with your sample html's

**Comment by CDAfonso** [comment]
It's solved now. I had on the webview properties zoom = false. On the build it was allowing to pinch zoom on the first time, but not after that. Removed zoom parameter it works fine using the meta tag.
Thank you!
