### ISSUE TITLE
Can't see webview (only keyboard)

### ISSUE THREAD

**Issue by antonio-emilio** [gree/unity-webview#1026]
Hi everyone!
First of all, sorry for any possible mistakes. I'm a new unity user.
I'm trying to implement a webview using this lib but I just couldn't make it work.
I tried both sample and implement myself on my personal project, but the view simply doesn't appear, only the keyboard does.
![image](https://github.com/gree/unity-webview/assets/55039179/af5173f9-1c4e-48a9-ac5c-e506bb0cec23)
I'm using WebGL. I did replicate the webGL instructions in the readme, created a gameObject, etc etc, exactly the same thing as the sample

Is there something i'm forgetting?
I'm using Unity 2022.3.14f1.

**Comment by antonio-emilio** [comment]
Now I managed to see my webview when I compiled to webGL (I was trying to see in my Editor)
![image](https://github.com/gree/unity-webview/assets/55039179/6a02213f-cc3c-4fef-8977-91fd516bc76a)
But I'm not being able to open the page (same happens as #941 , but still doesn't load when I removed the evaluateJS

**Comment by KojiNakamaru** [comment]
google.com specifies "X-Frame-Options: SAMEORIGIN" so it cannot be displayed in iframe outside google.com.

**Comment by antonio-emilio** [comment]
Thanks! That's the problem. Changing to another URL worked for me.
