### ISSUE TITLE
Is there a control bar for the webview?

### ISSUE THREAD

**Issue by abdojapan** [gree/unity-webview#103]
Hi,

I understand I can draw my own UI and give webViewObject.GoBack(); orders.
But, is there a built in topbar for the webview to make back/forward?

Thanks for advance.

**Comment by KojiNakamaru** [comment]
No, this plugin just overlays system-provided UIWebView/WebView views on Unity's rendering view. You have to contruct such a control bar by yourself with uGUI etc.

**Comment by abdojapan** [comment]
Thank you for the info and quick reply!
