### ISSUE TITLE
ignore the certificate checking on Unity Editor

### ISSUE THREAD

**Issue by marcolau0212** [gree/unity-webview#1032]
when I'm developing my website and trying to debug on Unity Editor, the "CallOnError" event catch the error
 **"Error Domain=NSURLErrorDomain Code=-1202 " The certificate for this server is invalid. You might be connecting to a server that is pretending to be “<my domain>” which could put your confidential information at risk."** 

I understand that is because the certificate is outdate or somthing else cause this. What I want to know is how to ignore the certificate checking on Unity Editor

I know that I can modify the "Webview.mm" in the "Plugins/iOS" to ignore the certificate checking. But it only effect when I build the project

```
- (void)webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential *))completionHandler
{
    if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
        
        NSURLCredential *card = [[NSURLCredential alloc]initWithTrust:challenge.protectionSpace.serverTrust];
        
        completionHandler(NSURLSessionAuthChallengeUseCredential,card);
        
    }
}
```

**Comment by KojiNakamaru** [comment]
You can find source code for WebView.bundle under https://github.com/gree/unity-webview/tree/09f19253c12e6e817ae492fb1ea2c2f1f53964a0/plugins/Mac .

**Comment by marcolau0212** [comment]
Great! Thanks for your help ; )
