### ISSUE TITLE
URL Scheme between webview and app

### ISSUE THREAD

**Issue by abdojapan** [gree/unity-webview#104]
Hi,

I am implementing oAUTH 1.0 with my server from inside unity's gree webview. After authorization, I want to get the verification token of the custom URL scheme.

So I want a message to unity if the webview loads a url like this
app001://auth_callback?token=xxxx

I noticed that there is no events like onURLLoad or something similar.
I am not sure if I can use Javascript for that.

Thanks for advance.
Your help is greatly appreciated.

**Comment by abdojapan** [comment]
I did a server side javascript that helps me resolve this problem, but if we can have a native onurlload event or similar exposed to unity, I think it will be pretty useful.
Thank you!

**Comment by KojiNakamaru** [comment]
I've just experimentally added the `loaded` callback in https://github.com/gree/unity-webview/pull/106. Please give it a try if you need such a function next time. Another (hopefully obsolete) approach was discussed in https://github.com/gree/unity-webview/issues/73#issuecomment-218641695.
