### ISSUE TITLE
for Mac, WebView plugin has bug

### ISSUE THREAD

**Issue by WolfgangKurz** [gree/unity-webview#1055]
https://github.com/gree/unity-webview/blob/969ce45f745ff919c3715074f9f45be99d622f38/plugins/Mac/Sources/WebView.mm#L811-L818

In `update` method, `inRendering` will not be set to `NO` when called with `refreshBitmap` is `NO`.

After set `inRendering` to `YES`, check `refreshBitmap` and setting `inRendering` to `NO` is in there.

This line should be:
``` obj-c
    @synchronized(self) {
        if (inRendering)
            return;
        if (refreshBitmap) inRendering = YES;
    }
```

or,
https://github.com/gree/unity-webview/blob/969ce45f745ff919c3715074f9f45be99d622f38/plugins/Mac/Sources/WebView.mm#L843

Should call this when `refreshBitmap` is `NO`.

**Comment by KojiNakamaru** [comment]
Thank you. I've fixed the issue in #1056 and updated binaries.
