### ISSUE TITLE
requestAnimationFrame, Animation, Transition throttled in macOS (editor and standalone both)

### ISSUE THREAD

**Issue by WolfgangKurz** [gree/unity-webview#1057]
I tried below code to check screen update frequency:
``` js
let counter = 0;
let lastTime = new Date().getTime();
let ra;

const fn = () => {
    counter++;

    const now = new Date().getTime();
    const elapsed = now - lastTime;
    lastTime = now;

    const text = `${counter} times<br/>\n` +
        `${elapsed} msec<br/>\n` +
        `${Math.floor(10000 / elapsed) / 10} FPS<br/>\n` +
        `${new Date().toISOString()}<br/>\n` +
        `${ra}`;
    document.querySelector("#debug").innerHTML = text;

    if (ra !== null)
        ra = window.requestAnimationFrame(fn);
};
ra = window.requestAnimationFrame(fn);
```

and result shows:
![0](https://github.com/gree/unity-webview/assets/20940566/6483b346-a1dd-4950-8695-a6e199929634)

CSS animation and transition also not working.

So i call DOM change at c# to update screen:
``` c#
    void LateUpdate()
    {
        wv.EvaluateJS(@"
        (() => {
            const el = document.querySelector(""#debug_view"");
            el.scrollLeft = Math.floor(Math.random() * 160);
            el.scrollTop = Math.floor(Math.random() * 160);
        })();
        ");
    }
```

and result:
![1](https://github.com/gree/unity-webview/assets/20940566/cb00a57b-5520-4fe2-ae4d-30d5f393a2a9)

this not work for `requestAnimationFrame` and CSS animation / transition.

Is there anything i missed to fix this?

**Comment by WolfgangKurz** [comment]
Thank you for your quick response!
Very helpful!

**Comment by KojiNakamaru** [comment]
The solutions discussed in https://github.com/gree/unity-webview/issues/1057#issuecomment-2003179007 should still be better, but I came up with a better implementation: https://github.com/gree/unity-webview/issues/1059#issuecomment-2022821244
