### ISSUE TITLE
How can I add a button for scrolling the page?

### ISSUE THREAD

**Issue by nitingit7** [gree/unity-webview#1058]
Hello @KojiNakamaru 

I want to know that how can I make a button for scrolling the webpage little by little, or we can set the amount of that too.

**Comment by KojiNakamaru** [comment]
You can utilize javascript `window.scrollBy()` as below:

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 14e3428..00e79cb 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -199,6 +199,16 @@ public class SampleWebView : MonoBehaviour
     {
         var x = 10;
 
+        if (GUI.Button(new Rect(x, 10, 80, 80), "UP")) {
+            webViewObject?.EvaluateJS("window.scrollBy(0, 10)");
+        }
+        x += 90;
+
+        if (GUI.Button(new Rect(x, 10, 80, 80), "DOWN")) {
+            webViewObject?.EvaluateJS("window.scrollBy(0, -10)");
+        }
+        x += 90;
+
         GUI.enabled = (webViewObject == null) ? false : webViewObject.CanGoBack();
         if (GUI.Button(new Rect(x, 10, 80, 80), "<")) {
             webViewObject?.GoBack();
```

**Comment by nitingit7** [comment]
@KojiNakamaru

Thanks, it is working, one more question, did you know how to build it for android TV using unity?

**Comment by KojiNakamaru** [comment]
I have no experience of Android TV, however, an app for it is basically an ordinal android app. Unity has some switches for Android TV, which can be found in https://docs.unity3d.com/2020.3/Documentation/Manual/class-PlayerSettingsAndroid.html .

**Comment by nitingit7** [comment]
Thank you very much for your support
