### ISSUE TITLE
Webview not rendering correctly on macOS or editor unless using separate window

### ISSUE THREAD

**Issue by jamesrp13** [gree/unity-webview#1059]
We have a view that renders correctly across all platforms except macOS/macOS editor, but does render correctly when using the webview in a separate window (by adding `separated: true` to the initializer. The following image shows the correct view in the separate window:

![Screenshot 2024-03-20 at 9 01 14 PM](https://github.com/gree/unity-webview/assets/11344110/ec6f6952-570e-40bc-972f-81eacbcba10f)

Note that it also renders without the separate window on iOS and Android.

This is what renders without the separate window (some logs redacted):

![Screenshot 2024-03-20 at 9 04 47 PM](https://github.com/gree/unity-webview/assets/11344110/cde85f69-70af-4f5e-813a-8315c81bd994)

We're not certain why it would work in a separate window but not inside the editor or inside the mac build. I'd appreciate any advice or help you can provide.

**Comment by KojiNakamaru** [comment]
The implementation for osx utilizes offscreen WKWebViews and doesn't work well compared with imnplementations for Android/iOS devices, which simply place native WebViews/WKWebViews over Unity's rendering view. The separated mode utilizes onscreen/normal WKWebViews so it works without any limitation. 

As discussed in https://github.com/gree/unity-webview/issues/1057#issuecomment-2003179007, it is better to consider other solutions for supporting osx in production.

**Comment by jamesrp13** [comment]
@KojiNakamaru are there any workarounds to make the osx implementation work here? We've looked into other solutions (including the one you link to in #1057) and have not found any outside of this package whose license works for our use case. Our use case is an integration inside of a developer SDK and business requirements are such that we can't require developers to pay for a separate license (such as with 3d web view https://developer.vuplex.com/webview/overview).

**Comment by jamesrp13** [comment]
If you have debugging tips or if there's a way to programmatically insepct the webview's window, that would be incredibly helpful.

**Comment by KojiNakamaru** [comment]
You can find several implementations on github, which utilize CEF (Chromium Embbedded Framework). The following seems to be continuously updated and promissing.

https://github.com/Voltstro-Studios/UnityWebBrowser/

About debugging, (though it is not handy) you can attach Xcode to the process and utilize its debugger. In the separate mode, you can right-click on window and select Inspect to open developer tools.

**Comment by jamesrp13** [comment]
I wasn’t aware that the voltstro library supported macOS.

Thank you for the debugging pointers

**Comment by KojiNakamaru** [comment]
Ah, the volstro library seems not to support macOS.  However, it should be a good starting point.
cf. https://github.com/Voltstro-Studios/UnityWebBrowser/discussions/148

**Comment by jamesrp13** [comment]
Are you aware of any specific issues in this library (unity-webview, not unitywebbrowser) that would cause iframes not to render on macos? That appears to be the issue. All html appears to render except for what's inside an iframe. However, as noted in the original issue, it renders perfectly when using a separate window to debug. Is there something about the embedded webview that blocks JS or some security setting I can toggle?

**Comment by KojiNakamaru** [comment]
The implementation itself do nothing about iframe. Though https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options affects iframe, but it affects equaly for separated/non-separated modes. Perhaps the issue was caused by the lack of the timer/update mechanism.

BTW, I came up with a better implementation for the non-separated mode (#1061) and updated binaries. It is still incomplete in many aspects compared with the separated mode, but runs more nicely for css animations/movies.

**Comment by jamesrp13** [comment]
Thanks @KojiNakamaru! Your changes in #1061 fixed the rendering issue for non-separated mode! The only remaining issue is that it seems to pass through clicks to the screen underneath rather than intercept them at the webview level. Any idea what I should investigate there?

**Comment by KojiNakamaru** [comment]
I've introduced #1062 and #1063 to instantiate a "background" image when WebViewObject.canvas is specified.

https://github.com/gree/unity-webview/blob/e9b323c77329a02a78246ce78d984195dcb77cfb/sample/Assets/Scripts/SampleWebView.cs#L37-L39

Could you please try the latest?

**Comment by jamesrp13** [comment]
Thank you so much for adding these so quickly! That stops the clicks from being passed through.

No need for you to make any updates for this, but if you have ideas as to why it's happening that might help me figure it out and contribute: clicks seem to be intercepted by the webview but there aren't any state changes. For example, clicking on an input field doesn't place a flashing cursor the way it does in the separated window. I plan on attempting a few things this afternoon, but ultimately I'm lost as to why it works fine in the separate window but not the other. Lmk if you have thoughts and I'll keep digging.

**Comment by KojiNakamaru** [comment]
The current implementation utilizes a windows placed outside screen and the window becomes unfocused when Unity Editor is focused. This is the reason of the missing cursor. Unfortunately it is difficult to avoid this issue.

**Comment by jamesrp13** [comment]
Ah, that makes sense. Thanks for the explanation. I think it’s fair to close this issue now, thanks again for everything.
