### ISSUE TITLE
Unity Call from JS not working on iOS anymore (SOLVED)

### ISSUE THREAD

**Issue by CDAfonso** [gree/unity-webview#1072]
Hi!

I have this app i developed in the past and there is a embed webpage that needs to open files from browser.
At the time i implemented a script to trigger messages from the webview and if it contained "url>" and the url to open it triggered Application.OpenUrl.

It is working fine on Android (14).

I am 99% sure that it was working on iOS, but there is allways a 1% chance i did not verify this in iOS after delivering the app.

Html/Php file:
`   echo '<a href="#" onclick="Unity.call(\'url>' . $row["file" . $i] . '\')" target="_blank" download>📄 ' . $encoded_filename . '</a><br><br>';`

WebviewController.cs:
`  if (msg.StartsWith("url>"))
				   {
					   Debug.Log("Opening Link in External Browser!");
					   msgSplit = msg.Split('>');
					   string urlToOpen = msgSplit[1];
					   Debug.Log("Url to open: " + urlToOpen);
					   Application.OpenURL(urlToOpen);
				   }
				   else
				   {

					   try
					   {
						   msgSplit = msg.Split('|');
						   loginState = msgSplit[0];
						   loginUser = msgSplit[1];
						   loginAccessLevel = int.Parse(msgSplit[2]);
					   }
					   catch
					   {
						   Debug.Log("A error occured getting data from webview.");
					   }
				   }`

I don't have with me a mac computer right now to build and see the log with XCode.. so is there a clue to what is happening?

Thank you much.

**Comment by CDAfonso** [comment]
EDIT:

I found the root of the problem.. the client was uploading files with spaces in the filename. Removing the spaces or adding _ or - solved the problem.
Thank you anyway.

**Comment by KojiNakamaru** [comment]
Then can we close this issue?

**Comment by CDAfonso** [comment]
Yes @KojiNakamaru , thank you so much.
