### ISSUE TITLE
Crash Error - [base.apk!libmonochrome_64.so] - Render process crash wasn't handled by all associated  webviews

### ISSUE THREAD

**Issue by josemgmz** [gree/unity-webview#1073]
Hi @KojiNakamaru!

We are having a problem on Android, around 10% of our crash errors are caused by the following error:

`[base.apk!libmonochrome_64.so] - [FATAL:crashpad_client_linux.cc(745)] Render process (8222)'s crash wasn't handled by all associated  webviews, triggering application crash.

backtrace:
  #00  pc 0x00000000030dd788  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #01  pc 0x000000000596c8a0  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #02  pc 0x000000000626facc  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #03  pc 0x0000000004079278  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #04  pc 0x0000000002b957a8  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #05  pc 0x0000000002b92458  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #06  pc 0x00000000059aeed4  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #07  pc 0x00000000059aee7c  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #08  pc 0x00000000038c20f4  /data/app/~~w3zhi5xIu4RM_GpZ84KYMw==/com.google.android.trichromelibrary_647800842--ZPrZEK43WIvfwaiclYtaw==/base.apk!libmonochrome_64.so (BuildId: 81aed492eb7197ee5191c64aff781f4e481e1b93)
  #09  pc 0x00000000000182e0  /system/lib64/libutils.so (android::Looper::pollInner(int)+1064)
  #10  pc 0x0000000000017e54  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #11  pc 0x000000000016cee4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #12  pc 0x0000000000321514  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+116)
  #13  pc 0x0000000000a113a0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.MessageQueue.next+304)
  #14  pc 0x0000000000a0e270  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+96)
  #15  pc 0x0000000000a0e168  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+1112)
  #16  pc 0x00000000007726cc  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+1660)
  #17  pc 0x000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #18  pc 0x000000000037cb18  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1556)
  #19  pc 0x000000000037c4f4  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32)
  #20  pc 0x00000000003275f8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
  #21  pc 0x0000000000c177e8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
  #22  pc 0x0000000000c21c1c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3404)
  #23  pc 0x000000000033b680  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640)
  #24  pc 0x00000000004e2a90  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+728)
  #25  pc 0x000000000057ab18  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+156)
  #26  pc 0x00000000000c4bf4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+108)
  #27  pc 0x00000000000d1be8  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924)
  #28  pc 0x0000000000002610  /system/bin/app_process64 (main+1464)
  #29  pc 0x0000000000085bd0  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100)
`
`  #00  pc 0x00000000049b4484  /data/app/com.google.android.trichromelibrary_636712333-De3bUyTn8TqrmVWe6NbxOQ==/base.apk!libmonochrome_64.so (BuildId: 930e6da4ab87612673f829f9908c9a2d3178e416)
`

If you could give me any clue on how to solve it I would be very grateful! 

Greetings!

**Comment by KojiNakamaru** [comment]
Perphaps the issue is caused by wrong WebView native modules. It could be solved by upgrading/downgrading WebView.

cf. https://android.stackexchange.com/questions/234830/com-google-android-trichromelibrary-causes-many-android-apps-to-crash/234835#234835

**Comment by josemgmz** [comment]
@KojiNakamaru Thank you for your reply!

**Comment by ArnauKokoro** [comment]
Hi @KojiNakamaru

We have now more information about this. We want to share with you what we have from Android ANR.

<img width="1369" alt="" src="https://github.com/gree/unity-webview/assets/80262126/b4c05b52-c1c6-4792-ba20-2201d3a1f7b6">

They are all HONOR devices with Android API 13.

What do you think? Can be webview obsolete?

If we test a physical HONOR do you think we can figure out the error better?

Thanks!

**Comment by KojiNakamaru** [comment]
@ArnauKokoro 
I guess so. HONOR devices might have very old WebView components that could not be updated because of Huawei's customization. By testing a physical HONOR device and trying to update the WebView component, you should get more clues.

**Comment by ArnauKokoro** [comment]
Thanks!

We will think about it!
