### ISSUE TITLE
Can't load local image in html string when load web view using webVIewObject.LoadHTML(htmlString)

### ISSUE THREAD

**Issue by sarvjeet-talentica** [gree/unity-webview#1078]
How can we incluse any local file  when load loading webview using html string

`<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Unity WebView</title>
    <script src="sample.js"></script>
    
  </head>
  <body>
    <h1>Hello Unity WebView!</h1>
    <hr/>
    <p><a href="https://google.com">https://google.com</a> (for testing go/back buttons)</p>
    <p><a href="http://httpbin.org/headers">http://httpbin.org/headers</a> (for testing custom headers.)</p>
    <p><img id="img" src="/Users/sarvjeetk/Desktop1/sample.jpg"/> (local image)</p>
    <p><a href="javascript:void(0)" onclick="testSaveDataURL();">Test saveDataURL</a> (experimental, only for Android/iOS)</p>
    <hr/>
    <div id="msg">[]</div>
    <p><a href="javascript:void(0)" onclick="Unity.call('anchor');">[Send Message!]</a></p>
    <form method="get" action="form">
      <input id="input1" type="text" value="hoge" name="msg"/>
      <input type="submit" value="Send Message!" onclick="Unity.call('form?msg=' + document.getElementById('input1').value); return false;"/><br/>
      <input type="file" name="datafile"/>
    </form>
  </body>
</html>
`

    <p><img id="img" src="/Users/sarvjeetk/Desktop1/sample.jpg"/> (local image)</p> this line in the code

**Comment by KojiNakamaru** [comment]
WebView restricts its file access only under the root url. You may copy necessary files to make them accessible by referring the following sample code:

https://github.com/gree/unity-webview/blob/323d5d3611c92632f259d2d2cdadc9bbbb0e9014/sample/Assets/Scripts/SampleWebView.cs#L167-L185

where files in StreamingAssets are copied to `Application.temporaryCachePath`.

**Comment by sarvjeet-talentica** [comment]
@KojiNakamaru I don't want to load any local html file, I want load a html string and string contains reference a local file

like in thee code example from Assets/Scripts/SampleWebview.cs I replaced webViewObject.LoadURL(Url.Replace(" ", "%20")); to ->>> webViewObject.LoadHTML(Url,""); and passed full html string in Url variable

now that Url contains image src

Is that possible?



`
        webViewObject.SetMargins(5, 100, 5, Screen.height / 4);
        webViewObject.SetTextZoom(100);  // android only. cf. https://stackoverflow.com/questions/21647641/android-webview-set-font-size-system-default/47017410#47017410
        webViewObject.SetVisibility(true);


        
        webViewObject.LoadHTML(Url,"");
        yield break;
#if !UNITY_WEBPLAYER && !UNITY_WEBGL
        if (Url.StartsWith("http")) {
            webViewObject.LoadURL(Url.Replace(" ", "%20"));
        } else {
            var exts = new string[]{
                ".jpg",
                ".js",
                ".html"  // should be last
            };
            foreach (var ext in exts) {
                var url = Url.Replace(".html", ext);
                var src = System.IO.Path.Combine(Application.streamingAssetsPath, url);
                var dst = System.IO.Path.Combine(Application.temporaryCachePath, url);
                byte[] result = null;
                if (src.Contains("://")) {  // for Android
#if UNITY_2018_4_OR_NEWER
                    // NOTE: a more complete code that utilizes UnityWebRequest can be found in https://github.com/gree/unity-webview/commit/2a07e82f760a8495aa3a77a23453f384869caba7#diff-4379160fa4c2a287f414c07eb10ee36d
                    var unityWebRequest = UnityWebRequest.Get(src);
                    yield return unityWebRequest.SendWebRequest();
                    result = unityWebRequest.downloadHandler.data;
#else
                    var www = new WWW(src);
                    yield return www;
                    result = www.bytes;
#endif
                } else {
                    result = System.IO.File.ReadAllBytes(src);
                }
                System.IO.File.WriteAllBytes(dst, result);
                Debug.Log("path is " + dst);
                if (ext == ".html") {
                    //webViewObject.LoadURL("file://" + dst.Replace(" ", "%20"));
                    break;
                }
            }
        }
#else
        if (Url.StartsWith("http")) {
            webViewObject.LoadURL(Url.Replace(" ", "%20"));
        } else {
            webViewObject.LoadURL("StreamingAssets/" + Url.Replace(" ", "%20"));
        }
#endif


        yield break;`

**Comment by KojiNakamaru** [comment]
It is not possible. WebView is very restricted about accessing local files -- otherwise it leads to a serious security breach. You might be able to read an image file by File.ReadAllBytes() and embed it in html with `data:`.

**Comment by sarvjeet-talentica** [comment]
thanks for the suggestion will try that.
Also, will the same thing work for .js file?

**Comment by KojiNakamaru** [comment]
If you can read a js file with File.ReadAllText(), you can then embed it with the `<script>` tag.

**Comment by sarvjeet-talentica** [comment]
Thanks
