### ISSUE TITLE
How do I change the Webview rotation?

### ISSUE THREAD

**Issue by Daekyo-Jeong** [gree/unity-webview#1083]
Hello.
The target platform is Android.
I want to rotate the Webview in the right direction, is there any way?
keep the game screen and just rotate the Webview.

![스크린샷 2024-07-26 오전 11 53 20](https://github.com/user-attachments/assets/6f0ef05d-9e01-47e9-b269-ffebbc498669)
Please refer to the picture.
*Multiple web views need not be represented simultaneously with different rotations, as shown in the picture.

**Comment by KojiNakamaru** [comment]
I pushed an experimental implementation to https://github.com/gree/unity-webview/commits/experimental/android_rotated/, which utilizes https://github.com/rongi/rotate-layout to rotate webviews. The sample app on this branch can be opened and built directly with 2020.3.48f1. For importing rotate-layout to your project, you need to use custom gradle templates where the following should be added to Assets/Plugins/Android/baseProjectTemplate.gradle:

```gralde
        maven { url 'https://jitpack.io' }
```

and the following should be added to Assets/Plugins/Android/mainTemplate.gradle:

```gradle
    implementation 'com.github.rongi:rotate-layout:v3.0.0'
```
