### ISSUE TITLE
how to compile the android jar file

### ISSUE THREAD

**Issue by cd0304** [gree/unity-webview#109]
hi,
   i want to modify the CWebViewPlugin.java,  but i can not run the install.sh 

what is your env can run the install ?
how to compile it ,thanks

**Comment by cd0304** [comment]
ok,i resolve this problem 
my env is windows 7

so i install git bash tool

and install.sh must modify as this:

#!/bin/sh
UNITYLIBS=`find -L D:/softwave/Unity | grep classes.jar | tail -1`
DSTDIR="../../build/Packager/Assets/Plugins/Android"
export ANT_OPTS=-Dfile.encoding=UTF8
android.bat update project -t android-18 -p .
mkdir -p libs
cp $UNITYLIBS libs
ant "-Djava.compilerargs=-Xlint:deprecation" release
mkdir -p $DSTDIR
cp -a bin/classes.jar $DSTDIR/WebViewPlugin.jar
ant clean
rm -rf libs res proguard-project.txt

**Comment by KojiNakamaru** [comment]
Thank you for solving the issue and providing an extra information. If you need any assistance further, please reopen this issue or open a new issue.

**Comment by jirevwe** [comment]
Hi, I'm tried out the shell script... But it's not working..

what's android.bat?

**Comment by jirevwe** [comment]
Hi, I tried out the shell script modification,  but it didn't work... what is android.bat?
