### ISSUE TITLE
[iOS][MacOS]Cookies Callback not invoked when calling Getcookies

### ISSUE THREAD

**Issue by jonobarel-slatescience** [gree/unity-webview#1090]
> I put a modified sample app which can be directly opened and built with 2022.3.16f1 under: https://github.com/gree/unity-webview/tree/example-for-1034/sample . 

_Originally posted by @KojiNakamaru in https://github.com/gree/unity-webview/issues/1034#issuecomment-1898769156_
            

Hi @KojiNakamaru 

Since updating to the latest version I've tried calling `GetCookies()` with a callback, just like in your sample, and the callback never gets invoked.

I've tried this in the editor and on iOS (your sample works perfectly on both!)

I wonder if there's a problem when the plugin tries to call `_CWebViewPlugin_GetCookies(webView, url);`?

Specifically, I look for the callback invocation after this call: https://github.com/gree/unity-webview/blob/6c8756239547a6cbe3972cbd019f8137497fa4cd/dist/package/Assets/Plugins/WebViewObject.cs#L1425

**Comment by KojiNakamaru** [comment]
`_CWebViewPlugin_GetCookies(webView, url)` won't be called if `webView == IntPtr.Zero`.

https://github.com/gree/unity-webview/blob/6c8756239547a6cbe3972cbd019f8137497fa4cd/dist/package/Assets/Plugins/WebViewObject.cs#L1422-L1425

Similarly, `webViewObject?.GetCookies(Url)` won't do nothing if `webViewObject == null`

https://github.com/gree/unity-webview/blob/8358845259f3eb20af6968b633cc76a21e067aba/sample/Assets/Scripts/SampleWebView.cs#L234-L236

You can check these parts by importing the unity-webview package under Assets and by adding `Debug.Log()`. By running an emitted iOS project on Xcode, you can further add a break point for `_CWebViewPlugin_GetCookies()`.

**Comment by jonobarel-slatescience** [comment]
Thanks for the comments!

I tried both of those, and I saw that in XCODE we reach `UnitySendMessage([gameObjectName UTF8String], "CallOnCookies", [result UTF8String]);`

But after that I don't see the callback invoked, even when I reduce it to a simple debug (like in your sample).
Anywhere else I can check?

https://github.com/gree/unity-webview/blob/6c8756239547a6cbe3972cbd019f8137497fa4cd/dist/package/Assets/Plugins/iOS/WebView.mm#L372
https://github.com/gree/unity-webview/blob/6c8756239547a6cbe3972cbd019f8137497fa4cd/dist/package/Assets/Plugins/iOS/WebView.mm#L404

**Comment by KojiNakamaru** [comment]
How about the `ld:` callback? It also utilize UnitySendMessage() so if it works then UnitySendMessage() for "CallOnCookies" should also work...

Can you attach a zip file of the minimum project that reproduces the issue? I can then investigate the issue further.

**Comment by jonobarel-slatescience** [comment]
ld confirmed works correctly.
Before I send you a project I'll try to use our version in your sample project and see if it still happens. Thanks.

**Comment by jonobarel-slatescience** [comment]
Okay, after further investigation, we found that our own code was destroying the webview before the callback had a chance to get invoked.

Thanks again for your guidance, it helped lead us in the right direction after confirming that our changes to the plugin weren't the cause 🙏
