### ISSUE TITLE
NullPointerException in Java code when calling webViewObject.GetCookies

### ISSUE THREAD

**Issue by jonobarel-slatescience** [gree/unity-webview#1094]
Hi Koji,

I started getting a NullPointerException error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void net.gree.unitywebview.CWebViewPluginInterface.call(java.lang.String, java.lang.String)' on a null object reference` at [CWebviewPlugin.java](https://github.com/gree/unity-webview/blob/afb694bdcfffb0ad029979bf9bae46a8699cc568/plugins/Android/webview/src/main/java/net/gree/unitywebview/CWebViewPlugin.java#L1365)

Note that this doesn't happen in the sample project you created, only in our main project.

I can't share our full project here, but I can share that I tried adding debug prints int he Java code:

```    
public void GetCookies(String url)
    {
        CookieManager cookieManager = CookieManager.getInstance();
        Log.i("CWebViewPlugin", "cookieManager is null? " + ((cookieManager == null)? "true" : "false"));
        Log.i("CWebViewPlugin", cookieManager.toString());
        mWebViewPlugin.call("CallOnCookies", cookieManager.getCookie(url));
    }
```
    
```
    > cokieManager is null? false
    > Mp@a0576c3
  ```
  
  Any thoughts on why the `call` method would be failing here?

**Comment by jonobarel-slatescience** [comment]
Obviously I printed debugs for `cookieManager` but the null value is for `mWebViewPlugin`, but I'm trying to debug the plugin directly on Android now.

**Comment by jonobarel-slatescience** [comment]
Where is CWebviewPlugin::Init called? It looks like the instance I'm using wasn't initialized. Is it called from the Csharp Init call?

**Comment by KojiNakamaru** [comment]
Thank you for investigating further. `WebViewObject#Init()` calls `CWebView#Init()` as below:

https://github.com/gree/unity-webview/blob/afb694bdcfffb0ad029979bf9bae46a8699cc568/plugins/WebViewObject.cs#L682-L686

The actual initialization however happens in a `Runnable` scheduled by `runOnUiThread()`:

https://github.com/gree/unity-webview/blob/afb694bdcfffb0ad029979bf9bae46a8699cc568/plugins/Android/webview/src/main/java/net/gree/unitywebview/CWebViewPlugin.java#L399-L821

so if you call any method that doesn't utilize `runOnUiThread()` just after calling `Init()`, it may fail.

I'll later add a way to check the completion of the initialization. For now, could you please try to avoid calling any method just after calling `Init()`. For example, you may perform `yield return null` several times.

**Comment by KojiNakamaru** [comment]
I introduced #1095 and updated binaries. You can wait for the completion of the initialization as below:

https://github.com/gree/unity-webview/blob/271aad458f96ab5fb84697a9238cd04ecbd0b595/sample/Assets/Scripts/SampleWebView.cs#L132-L135

**Comment by jonobarel-slatescience** [comment]
You're a champ, Koji, thank you so much! I'll test this on my end and update the issue.

**Comment by jonobarel-slatescience** [comment]
Thanks, Koji! that's exactly what I needed 🔥 🔥 🔥
