### ISSUE TITLE
Crash on calling WebViewObject.SetVisibility(false) on Editor mode

### ISSUE THREAD

**Issue by kimsama** [gree/unity-webview#11]
Hello, 

Unity Editor crashes when WebViewObject.SetVisibility(false) is called. 

I put a button and call Unity.call('close') in the html then make the webview to be closed when it received 'close' message. 

The message is correctly arrived on Unity but it crashes when it calls WebViewObject.SetVisibility(false).:

		// regisiter callback
		webViewObject.Init((msg)=>{
			Debug.Log(string.Format("CallFromJS[{0}]", msg));
			
			if (msg == "close")
			{
				webViewObject.SetVisibility(false);
			}
		});

The only differences what I've changed is putting code which check the message then change the visibility of the webviewObject. 

I ran it on OSX 10.8.2.

I also tried to do clean build the OSX plugin with Xcode 4.6. Building 32bit bundle has no problem, but got bunch of errors with 64bit bundle. 

Is there any way to debug OSX bundle when Unity is on play mode? 

-Kim

**Comment by KojiNakamaru** [comment]
I've tried the latest (should be very different from one caused crashes) and it seems to cause no crash. Please reopen the issue if you need any assistance further.
