### ISSUE TITLE
Get "Undefined" when trying to find element шт 

### ISSUE THREAD

**Issue by savic1111** [gree/unity-webview#1102]
I send   webViewObject.EvaluateJS(js + @"Unity.call($('html'))") in  webViewObject.Init. And when i run my app - in logs i see undefined
![Capture](https://github.com/user-attachments/assets/4cb06e4b-9246-4a9a-8c41-9b653ed4ffb8)

I expect to see info about element because i m sure it is visible on this web-page.

Please help)

**Comment by KojiNakamaru** [comment]
Perhaps `$` is not defined (jQuery does not exist in the html page).

**Comment by savic1111** [comment]
> Perhaps `$` is not defined (jQuery does not exist in the html page).

Yes, thank you, I ve tried document.querySelector and it works now)
