### ISSUE TITLE
WebGLでreact-router-domのLinkの画面遷移時にページ再読み込みが発生してしまう

### ISSUE THREAD

**Issue by heroz-iwamoto** [gree/unity-webview#1105]
WebGLにおいて、Reactで開発したページを読み込む際に問題が発生しました。
react-router-domのLinkを使って画面遷移した場合、通常はページ再読込みが発生しないのですが、unity-webviewのWebGLの場合のみ、ページ再読込みが発生します。

以下は問題が発生するサンプルコードです。

```typescript
import {BrowserRouter, Link, Route} from "react-router-dom"
import * as React from "react"

export const Test = () => {
    return (
        <BrowserRouter>
            <Route exact path="/test" render={() => <Index />} />
            <Route exact path="/test/detail" render={() => <Detail />} />
        </BrowserRouter>)
}

export const Index = () => {
    return (
        <Link to={"/test/detail"}>Detail</Link>
    )
}

export const Detail = () => {
    return <div>Detail</div>
}

export default Test
```

/testを開き、"Detail"のリンクをクリックすると、HTTPリクエストは発生せずにDetail画面に遷移し、URLが切り替わるのが正常な動作です。
しかし、unity-webviewのWebGLの場合のみ、/test/detailにHTTPリクエストが送信され、ページが再読込みされてしまいます。

こちらの行をコメントアウトすることで解決しました。
https://github.com/gree/unity-webview/blob/master/plugins/WebGLTemplates/unity-webview-2020/unity-webview.js#L28

リンククリック時にページ読込みを発生させたくない場合もあるので、問題ないようであればこの箇所を削除してはいかがでしょうか？

**Comment by KojiNakamaru** [comment]
詳細な調査と修正の提案、ありがとうございます。 #1106  で修正し、パッケージを更新しました。

**Comment by heroz-iwamoto** [comment]
早速のご対応ありがとうございます。
