### ISSUE TITLE
send and receive webview<==>unity

### ISSUE THREAD

**Issue by pmtolk** [gree/unity-webview#111]
I am migrating from coherent ui which stopped support then to uniwebview because it is crashing on certain https ssl certificates and now this project which is going strong and working! great job ;)

I was wondering how can I send and receive messages between unity and the webview
this is how I am doing it in uniwebview2 and I was wondering whats the unity-webview equivalent?

```
 uniWebView.OnReceivedMessage += OnReceivedMessage;

 //receive call from Webview To Unity
 void OnReceivedMessage(UniWebView webView, UniWebViewMessage message) {
    string command=message.path;
    if(command=="hello_world"){
        string data=message.args["data"];
    }
 }

 //Send call from Unity to Webview
 uniWebView.TriggerEvent("Login", data);

 //then in the  class UniWebView
 public void TriggerEvent(string name, string data){
    data=name+"("+data+");";
    UniWebViewPlugin.EvaluatingJavaScript(gameObject.name, data);
 }
```

**Comment by KojiNakamaru** [comment]
Thanks;) For WebView->Unity, you can utilize Unity.call() or (`location = "unity:message_to_besent"`):

https://github.com/gree/unity-webview/blob/b626f99806ba37b99fb214ae600451d239d9c2ba/sample/Assets/StreamingAssets/sample.html#L12

where its callback can be specified as below:

https://github.com/gree/unity-webview/blob/master/sample/Assets/Scripts/SampleWebView.cs#L34-L39

For Unity->WebView, you can utilize EvaluateJS():

https://github.com/gree/unity-webview/blob/b626f99806ba37b99fb214ae600451d239d9c2ba/plugins/WebViewObject.cs#L311

**Comment by pmtolk** [comment]
I am having trouble sending messages from the web view to unity.
If I have the following code then it works only on the url that loads.
Do I need to add this to every webpage?
Can I add this directly to a javascript file so I dont need to add it from unity to the web page after it load?
Why do I need this code? What does it do?

`	#if !UNITY_ANDROID
			webViewObject.EvaluateJS(
				"window.addEventListener('load', function() {" +
				"   window.Unity = {" +
				"       call:function(msg) {" +
				"           var iframe = document.createElement('IFRAME');" +
				"           iframe.setAttribute('src', 'unity:' + msg);" +
				"           document.documentElement.appendChild(iframe);" +
				"           iframe.parentNode.removeChild(iframe);" +
				"           iframe = null;" +
				"       }" +
				"   }" +
				"}, false);");
			#else
			webViewObject.EvaluateJS(
				"parent.$(function() {" +
				"   window.Unity = {" +
				"       call:function(msg) {" +
				"           parent.unityWebView.sendMessage('WebViewObject', msg)" +
				"       }" +
				"   };" +
				"});");
			#endif`

**Comment by pmtolk** [comment]
I am having trouble sending messages from the web view to unity.
If I have the following code then it works only on the url that loads.
Do I need to add this to every webpage?
Can I add this directly to a javascript file so I dont need to add it from unity to the web page after it load?
Why do I need this code? What does it do?

#if !UNITY_ANDROID
        webViewObject.EvaluateJS(
            "window.addEventListener('load', function() {" +
            "   window.Unity = {" +
            "       call:function(msg) {" +
            "           var iframe = document.createElement('IFRAME');" +
            "           iframe.setAttribute('src', 'unity:' + msg);" +
            "           document.documentElement.appendChild(iframe);" +
            "           iframe.parentNode.removeChild(iframe);" +
            "           iframe = null;" +
            "       }" +
            "   }" +
            "}, false);");
        #else
        webViewObject.EvaluateJS(
            "parent.$(function() {" +
            "   window.Unity = {" +
            "       call:function(msg) {" +
            "           parent.unityWebView.sendMessage('WebViewObject', msg)" +
            "       }" +
            "   };" +
            "});");
        #endif

Also,  I am not sure I understand what this means location = "unity:message_to_besent"

I would like to get a function like this working on every webpage.

    	function engine_call(name,data) {
        	console.log(name+data);
        	location = "unity:"+name"?json="+data;
        	window.location.href = location;
        	Unity.call(name+"?json="+data);
    	}

**Comment by KojiNakamaru** [comment]
> As soon as I navigate to another webpage the web view to unity messaging stops working.
> Do I need to add the following code after every webpage is loaded?
> Can I add this directly to a javascript file so I dont need to add it from unity to the web page after it load?

Yes, the definition will be vanished when any page transition occurs and it is totally okay to have the definition in your javascript in your htmls and not to call `EvaluateJS()` . Also for some historical reasons, the sample code is a bit complicated, unnecessarily. The funciton `Unity.call()` for Android/iOS/OSX can be defined as below:

```javascript
if (typeof(Unity) === 'undefined') {
    Unity = {
        call: function(msg) {
            var iframe = document.createElement('IFRAME');
            iframe.setAttribute('src', 'unity:' + msg);
            document.documentElement.appendChild(iframe);
            document.documentElement.removeChild(iframe);
        },
    };
}
```

`Unity.call()` for Android is defined by the plugin so you don't need to redefine it if `Unity` is defined.

**Comment by pmtolk** [comment]
So I added the code as you suggested but for some reason it is screwing up my subscquent angular javascript code. The rest of my javascript becomes all literals for some reason.

Does the unity function need to be in an iframe? What does creating an iframe and then appending it and then immediately removing it do? Is their another way to add the unity call besides the iframe?

function engine_call(name,data) {
    if (typeof(Unity) === 'undefined') {
        register_unity();
    }
    if (typeof(Unity) === 'undefined') {
        console.log("error unity undefined");
    }
    else{
        Unity.call(name+"?json="+data);
    }
   
    //var str = "uniwebview://"+name+"?json="+data;
    //window.location.href = str;
}

function register_unity(){
    if (typeof(Unity) === 'undefined') {
       Unity = {
        call: function(msg) {
            var iframe = document.createElement('IFRAME');
            iframe.setAttribute('src', 'unity:' + msg);
            document.documentElement.appendChild(iframe);
            document.documentElement.removeChild(iframe);
            },
        };
    }
}

**Comment by KojiNakamaru** [comment]
Although your code has a minor syntax error (the last comma in `call: function(msg) { ... },` should be removed), it should works. I've tested the sample works with the following modification.

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 824cb82..2f5e39d 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -78,20 +78,6 @@ public class SampleWebView : MonoBehaviour
                 }
             }
         }
-#if !UNITY_ANDROID
-        webViewObject.EvaluateJS(
-            "window.addEventListener('load', function() {" +
-            "   window.Unity = {" +
-            "       call:function(msg) {" +
-            "           var iframe = document.createElement('IFRAME');" +
-            "           iframe.setAttribute('src', 'unity:' + msg);" +
-            "           document.documentElement.appendChild(iframe);" +
-            "           iframe.parentNode.removeChild(iframe);" +
-            "           iframe = null;" +
-            "       }" +
-            "   }" +
-            "}, false);");
-#endif
 #else
         if (Url.StartsWith("http")) {
             webViewObject.LoadURL(Url.Replace(" ", "%20"));
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 14f70cd..417ffbd 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -2,6 +2,35 @@
   <head>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <title>Unity WebView</title>
+    <script>
+    function engine_call(name,data) {
+        if (typeof(Unity) === 'undefined') {
+            register_unity();
+        }
+        if (typeof(Unity) === 'undefined') {
+            console.log("error unity undefined");
+        }
+        else{
+            Unity.call(name+"?json="+data);
+        }
+
+        //var str = "uniwebview://"+name+"?json="+data;
+        //window.location.href = str;
+    }
+
+    function register_unity(){
+        if (typeof(Unity) === 'undefined') {
+           Unity = {
+            call: function(msg) {
+                var iframe = document.createElement('IFRAME');
+                iframe.setAttribute('src', 'unity:' + msg);
+                document.documentElement.appendChild(iframe);
+                document.documentElement.removeChild(iframe);
+                },
+            };
+        }
+    }
+    </script>
   </head>
   <body>
     <h1>Hello Unity WebView!</h1>
@@ -9,7 +38,7 @@
     <p><a href="https://google.com">https://google.com</a> (for testing go/back buttons)</p>
     <p><img src="sample.jpg"/> (local image)</p>
     <hr/>
-    <p><a href="javascript:void(0)" onclick="Unity.call('anchor');">[Send Message!]</a></p>
+    <p><a href="javascript:void(0)" onclick="engine_call('anchor');">[Send Message!]</a></p>
     <form method="get" action="form">
       <input id="input1" type="text" value="hoge" name="msg"/>
       <input type="submit" value="Send Message!" onclick="Unity.call('form?msg=' + document.getElementById('input1').value); return false;"/>
```

You may directly assign "unity:xxx" to `location.href` to send a message to the Unity side. The reason why the current `Unity.call()` is defined as it utilizes `iframe`, is that the original author (perhaps) didn't want to modify `location.href` as the function for Android didn't affect `location.href`.

**Comment by pmtolk** [comment]
I dont know why the iframe method was interfering with my angular code, 
but this is working perfectly!!! 😎 

```javascript
function engine_call(name,data) {
    //var str = "uniwebview://"+name+"?json="+data;
    var str = "unity:"+name+"?json="+data;
    window.location.href = str;
}

**Comment by KojiNakamaru** [comment]
Thanks again for the last comment, I recall it in https://github.com/gree/unity-webview/issues/149#issuecomment-285857755 . The twitter login page is also realized with react, so the 'iframe' approach cause the same issue.

**Comment by SivaG4K** [comment]
Hello. I'm trying to send data from Unity to Univeview4 but I don't know how to send it. Please tell me if you know. ThankYou

**Comment by KojiNakamaru** [comment]
What is `Univeview4`?
