### ISSUE TITLE
CUnityPlayer and Unity 6

### ISSUE THREAD

**Issue by justin-tsai** [gree/unity-webview#1110]
Hi, Unity 6 just released and I tried building my existing project with it but I get errors relating to this plugin when targeting Android. I think mainly due to the fact that [Android: Java class UnityPlayer needs to be renamed to UnityPlayerForActivityOrService](https://docs.unity3d.com/2023.2/Documentation/Manual/UpgradeGuide20231.html#android-unityplayer). Here are some examples

> ../Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/net/gree/unitywebview/CUnityPlayerActivity.java:14: error: incompatible types: CUnityPlayer cannot be converted to UnityPlayerForActivityOrService
>         mUnityPlayer = new CUnityPlayer(this);
>                        ^
> .../Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/net/gree/unitywebview/CUnityPlayerActivity.java:15: error: no suitable method found for setContentView(UnityPlayerForActivityOrService)
>         setContentView(mUnityPlayer);
>         ^
>     method Activity.setContentView(int) is not applicable
>       (argument mismatch; UnityPlayerForActivityOrService cannot be converted to int)
>     method Activity.setContentView(View) is not applicable
>       (argument mismatch; UnityPlayerForActivityOrService cannot be converted to View)

**Comment by KojiNakamaru** [comment]
CUnityActivity was introduced for the Unity 5.6.x z-order issue. It is not necessary for other Unity versions, so I removed it from recent plugins since #1082 . Could you please try the latest binaries?
