### ISSUE TITLE
How does one turn the webview to portrait mode?

### ISSUE THREAD

**Issue by lionslmao** [gree/unity-webview#1117]
The title :)

**Comment by KojiNakamaru** [comment]
You can specify the screen orientation for Unity and webviews follow it:

https://github.com/gree/unity-webview/issues/776#issuecomment-1030147055

If you set an orientation differs from Unity's one, you could utilize an experimental implementation:

https://github.com/gree/unity-webview/issues/1083#issuecomment-2253750646

**Comment by lionslmao** [comment]
It fails to build. With this error:
Could not resolve all dependencies for configuration ':launcher:releaseRuntimeClasspath'. See the Console for details.
Is there anything else im supposed to add like dependancy-wise?

**Comment by lionslmao** [comment]
Im using Unity 6.000.x, I havent tried it on the sample project im going to do that in a second.

**Comment by Volko61** [comment]
Meybe check here : https://discussions.unity.com/t/could-not-resolve-all-files-for-configuration-launcher-releaseruntimeclasspath/945621/5

Try to delete the the debug.keystore
Maybe try  to : double check passwords for project keystore, try reimported all, force resolve Android libraries, relaunch unity.

**Comment by lionslmao** [comment]
Hi I finally managed to build it! [This](https://discussions.unity.com/t/could-not-resolve-all-files-for-configuration-launcher-releaseruntimeclasspath/945621/5) was a part of the issue. I had to modify the solution to work for me but in the end it works.
Here are my .gradle files for anyone who has the same issue =) [baseProject](https://pastebin.com/51WNMfEL) [main](https://pastebin.com/cH4rLYUx). (i also had to remove the depResManager as mentioned [here](https://ksml4.com/2024/07/10/fixed-could-not-resolve-all-files-for-configuration-launcherreleaseruntimeclasspath/))

Thank you very much for helping a newbie out! 😄

**Comment by KojiNakamaru** [comment]
For a reference, I've pushed a bit different settings to https://github.com/gree/unity-webview/compare/7561370...bebc80c
