### ISSUE TITLE
Render uGUI on top of webview [Android]

### ISSUE THREAD

**Issue by jmsalandanan** [gree/unity-webview#125]
Is it possible to render uGUI on top of webview on android? Ideas? Thank you in advance.

**Comment by KojiNakamaru** [comment]
No it isn't for now, because Android/iOS implementations overlay their native WebView/UIWeView on Unity's rendering view.

**Comment by jmsalandanan** [comment]
@KojiNakamaru Thank you for your reply, though do you have any suggestions on how would I go about solving this? or any workaround that comes to mind. Thank you very much

**Comment by KojiNakamaru** [comment]
If you show your own HTML content with this plugin, you can realize any UI elements as a part of the HTML. You can communicate with the unity side as shown in the sample project,

https://github.com/gree/unity-webview/blob/1832580b614cbfca58b6d667624cfd6811688b5f/sample/Assets/StreamingAssets/sample.html#L12

or by utilizing `unity:` links as below.

```html
  <a href="unity:any message to be sent to the unity side">foo</a>
```

If we really want to overlay uGUI rendering on WebView, we need to generate a texture for WebView/UIWebView for every frame. This requires a bit large modification and the result may have performance/functional issues (for example, html video won't work).

**Comment by jmsalandanan** [comment]
@KojiNakamaru I see, thanks for the help!

**Comment by KojiNakamaru** [comment]
:-)
