### ISSUE TITLE
Change orientation in iOS

### ISSUE THREAD

**Issue by riqui99** [gree/unity-webview#126]
Hello,

First of all sorry for my english.

I using this plugin to open a web inside a game in unity. The game be in AutoRotation and when starts, in void Start() function I call the webViewObject.Init(...) SetMargins to 0,0,0,0 and SetVisibility(false). 

When I show the webview I only call SetVisibility(true). My problem arrive because I will like visualize webview in fullscreen and landscape. In Android with when I force the orientation (with Screen.orientation = ScreenOrientation.LandscapeLeft;) runs ok, but in iOS if game starts in portrait when orientation changes the webview size it's not full screen. (it's look like when apply rotation the webview "frame" rotate and mantain the original size and only visualize part of webview)

How can I do to force fullscreen and landscape in iOS? 

Thanks for advance

**Comment by KojiNakamaru** [comment]
Thanks for the report. I've fixed to set `autoresizingMask` in #127 and updated binaries in https://github.com/gree/unity-webview/commit/1c9feaa720bcb114c0ffe453a4de51fd2b916e83. It seems to work okay with the sample app. Could you please try the latest?

**Comment by riqui99** [comment]
Thanks for fast reply. Last night I working abiout the issue and arrive to the same solutions 
I update the unity package with your last modifications and runs perfect.

THANKS!!

**Comment by KojiNakamaru** [comment]
:-)
