### ISSUE TITLE
Send Raw data as application/js

### ISSUE THREAD

**Issue by jirevwe** [gree/unity-webview#128]
Hi,

I'm trying to send data to my server as raw JSON data and not form data.
How do I do this...??

I'm not good with JavaScript, but I was able to do this to no avail...

`var js`
      `  = "(function() {"`
      `  + " var data = {"`
      `  + "     \"reference_id\":\"1234567890987654322222222222222345\","`
      `  + "     \"uuid\":\"123456789876543wertyukjhgfd1234567\","`
      `  + "     \"time\":\"2016-08-01 13:31:59\","`
      `  + "     \"hash\":\"fee77c8db40f7f8d85342526a1ad9213\","`
     `   + "     \"amount\": 200000,"`
     `   + "     \"merchant_id\": 3,"`
      `  + "     \"product_id\": 4"`
     `   + "};"`
     `   + "var xhr = new XMLHttpRequest();"`
      `  + "xhr.addEventListener(\"readystatechange\", function() {"`
     `   + "if (this.readyState === 4){"`
       ` + "     console.log(this.responseText);}"`
      `  + "});"`
       ` + "xhr.open(\"post\", \"http://139.59.163.48:8282/ewallet/v1/merchant/initpayment\", true);"`
       ` + "xhr.setRequestHeader(\"content-type\", \"application/json\");"`
        `+ "xhr.send(data);"`
       ` + "})();";`
        `webViewObject.EvaluateJS(js);`

Thanks...

**Comment by KojiNakamaru** [comment]
`xhr.send(data);` seems to be wrong. Could you please try `xhr.send(JSON.stringify(data));` instead.

**Comment by jirevwe** [comment]
I tried that, it still didn't work. I found a way around it though.

Thanks
