### ISSUE TITLE
Problem in Unity 5.5.0f3

### ISSUE THREAD

**Issue by creative-nap** [gree/unity-webview#130]
Can't import the unity package in Unity version 5.5.0f3

DllNotFoundException: WebView
WebViewObject.Init (System.Action`1 cb, Boolean transparent, System.String ua, System.Action`1 err, System.Action`1 ld, Boolean enableWKWebView) (at Assets/Plugins/WebViewObject.cs:180)
SampleWebView+<Start>c__Iterator0.MoveNext () (at Assets/Scripts/SampleWebView.cs:33)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

Can anyone help?

- nap

**Comment by KojiNakamaru** [comment]
Are you using Unity for Windows? This plugin currently doesn't support it.

**Comment by creative-nap** [comment]
Hey KojiNakamaru,
Yeah I would use it for Windows/Windows Store.
Oh ok, then i will search for an alternative, thanks for your reply! But great work!
