### ISSUE TITLE
iOS + React Unity undefined exception

### ISSUE THREAD

**Issue by FrancooHM** [gree/unity-webview#134]
Hi.

I'm currently working on a Javascript fullstack app, with React at the top, wich is embeed in this Unity Webview plugin.

While Android is working fine, i could find this exception at runtime inspecting via Safari developer tools. This error is showed by browser console logs:

ReferenceError: Can't find variable: Unity

Any idea?

**Comment by KojiNakamaru** [comment]
The SampleWebView app injects the definition of `Unity` in the `ld` (loaded) callback:

https://github.com/gree/unity-webview/blob/240ce2cb5c306dda1424d957a7f14c8a7c2efdc5/sample/Assets/Scripts/SampleWebView.cs#L49-L61

but this is a bit fragile approach compared to the Android case in which `Unity` is defined by the Java code and always available in JavaScript. If you have a whole control for your web pages, as in your case, you can define the 'Unity' object as a part of your JavaScript code. Please refer the following discussions:

https://github.com/gree/unity-webview/issues/111#issuecomment-259576138
https://github.com/gree/unity-webview/issues/111#issuecomment-260267298

**Comment by FrancooHM** [comment]
Great!

We have done this way and is actually working:

```
let token = '';
        if (localStorage.getItem('id_token') != null)
        token = localStorage.getItem('id_token');
        if(/iPad|iPhone|iPod|webOS/.test(navigator.userAgent))
        {
          let msg = `offline-trucoaltoque-${token}`,
          UnityIOS = {
            call: function(msg) {
                var iframe = document.createElement('IFRAME');
                iframe.setAttribute('src', 'unity:' + msg);
                document.documentElement.appendChild(iframe);
                document.documentElement.removeChild(iframe);
                }
            };
UnityIOS.call();
```

Thanks!

**Comment by KojiNakamaru** [comment]
:-)
