### ISSUE TITLE
Compile jar file on Windows Environment.

### ISSUE THREAD

**Issue by jirevwe** [gree/unity-webview#136]
Hi I want to edit the CWebViewPlugin.java file and rebuild the jar... The bash script supplied doesn't work on my environment and I tried using the shell from #109, this didnt work either as he seems to be using a Mac..

thanks for any support...

**Comment by KojiNakamaru** [comment]
As he noted I guess he utilized "git bash" https://git-for-windows.github.io/ .

**Comment by jirevwe** [comment]
I did too... 

I've fixed it though... I moved to project to Android Studio and repackaged it there...

Thanks.
