### ISSUE TITLE
WebViewObject missing a using directive or an assembly reference

### ISSUE THREAD

**Issue by christsaragih** [gree/unity-webview#137]
Hy when i clone this project and open with unity 5.3.x  get error :

> Assets/Scripts/SampleWebView.cs(28,5): error CS0246: The type or namespace name `WebViewObject' could not be found. Are you missing a using directive or an assembly reference?

**Comment by KojiNakamaru** [comment]
Could you please check the steps described at: https://github.com/gree/unity-webview#sample-project .

**Comment by topherfangio** [comment]
I just ran into this same issue and the instructions provided fixed it (particularly the part about importing the `dist/unity-webview.unitypackage` and disabling the Metal editor support.

@KojiNakamaru I think this issue can be closed?

**Comment by KojiNakamaru** [comment]
@topherfangio Yes, thank you!

**Comment by Saleemkk** [comment]
Just remove packages/manifest.json
and its done
