### ISSUE TITLE
APK rejected - WebViewClient.onReceivedSslError

### ISSUE THREAD

**Issue by astrubel** [gree/unity-webview#139]
https://support.google.com/faqs/answer/7071387

**Comment by KojiNakamaru** [comment]
Thank you for the info. The plugin doesn't override `onReceivedSslError` so it may have the issue only if API level is 7 (Android 2.1.x) or lower (in which there is no `onReceivedSslError` and `onReceivedError` is called instead).

I guess setting `minSdkVersion` to at least 9 (Android 2.3) or higher should be okay for the recent market, but do you need to support `minSdkVersion` lower than 9?

**Comment by astrubel** [comment]
No I don't need to support minSdkVersion lower than 9

**Comment by astrubel** [comment]
How can I rebuild the WebViewPlugin.jar?

**Comment by KojiNakamaru** [comment]
Pease install Java, Android SDK, and Ant. You can then invoke install.sh command to build build/Packager/Assets/Plugins/Android/WebViewPlugin.jar:
```bash
$ cd plugins/Android/
$ ./install.sh
```

**Comment by astrubel** [comment]
#141 doesn't solve this issue.
"The host application must call either proceed() or cancel() to set the WebView's response to the request."
https://developer.android.com/reference/android/webkit/SslErrorHandler.html
http://stackoverflow.com/questions/35720753/android-google-play-warning-ssl-error-handler-vulnerability

**Comment by KojiNakamaru** [comment]
Thank you for pointing out the issue. I've reverted #141 and updated binaries.

**Comment by astrubel** [comment]
Do you found a solution for this issue?

**Comment by KojiNakamaru** [comment]
The current implementation of this plugin doesn't have onReceivedSslError (by following your suggestion) so an app utilizing it shouldn't be rejected. If we want to implement it, we need to add some confirmation for a user as discussed in http://stackoverflow.com/questions/35218775/google-play-warning-webviewclient-onreceivedsslerror-handler/37823137#37823137. It is possible, but recently everyone can enable correct https by https://letsencrypt.org/ so I think the current implementation is sufficient.

(could you please point out and elaborate the issue if my understanding is wrong/insufficient).

**Comment by astrubel** [comment]
I'm sorry, the issue comes from an old implementation of Unity IAP plugin.
A click on Update button from services panel fixed this issue.
No need to implement onReceivedSslError in this plugin!

**Comment by KojiNakamaru** [comment]
Okay, thanks!
