### ISSUE TITLE
Sending a cookie or postMessage via EvaluateJS function

### ISSUE THREAD

**Issue by montag64** [gree/unity-webview#140]
I've been struggling with this for a couple weeks and can't seem to figure out how to send a cookie or really anything to a php script or html/javascript page server-side. I have it working in html on my local machine in OS X but not within the Unity plugin. I am pretty new to js and HTML5. 

I've tried adding this in the sample web view with a valid cookie string such as 

```
string cookie = "FB_Login_Session=jpshtu30870hsfh062bfsdyfsdf; expires=Mon, 23-Jan-2017 15:51:34 GMT; path=/";

	               webViewObject.EvaluateJS(@"
	                  window.Unity = {
	                    call: function(msg) {
	                      var iframe = document.createElement('IFRAME');
	                      iframe.setAttribute('src', 'unity:' + msg);
	                      document.documentElement.appendChild(iframe);" +
						+ "document.cookie = " + cookie + ";" +
						@"iframe.parentNode.removeChild(iframe);
	                      iframe = null;
	                    }
	                  }
	                ");

```
I have also tried just sending a simple message.

`webViewObject.EvaluateJS(@"window.postMessage('hello','*');");`

and I've also tried this line in the js code in the sample web view script. 

`	"iframe.contentWindow.postMessage('hello', '*');" + `

I'd like to be able to post a cookie or send a message to the currently opened url/webview. Any ideas?

Thank you very much for your time and assistance.

**Comment by montag64** [comment]
Also, I just want to say -- fantastic work on this. I have some code I'd like to contribute but I've never worked in github before.

**Comment by montag64** [comment]
by luck or some miracle I was able at 5 am this morning to put this together (my Objective C is incredibly rusty). It might be worth adding to the project. All I did was pass a cookie as a string and added the requisite supporting functions.
```


	public void LoadURLWithCookie(string url, string cookie)
	{
	if (string.IsNullOrEmpty(url))
	return;
	#if UNITY_WEBPLAYER
	Application.ExternalCall("unityWebView.loadURLWithCookie", name, url, cookie);
	//?
	#elif UNITY_EDITOR || UNITY_STANDALONE_OSX || UNITY_IPHONE
	if (webView == IntPtr.Zero)
	return;
	_CWebViewPlugin_LoadURLWithCookie(webView, url, cookie);
	#elif UNITY_ANDROID
	if (webView == null)
	return;
	webView.Call("LoadURLWithCookie", url, cookie);
	#endif
	}

void _CWebViewPlugin_LoadURLWithCookie(void *instance, const char *url, const char *cookie);

void _CWebViewPlugin_LoadURLWithCookie(void *instance, const char *url, const char *cookie)
{
    CWebViewPlugin *webViewPlugin = (__bridge CWebViewPlugin *)instance;
    [webViewPlugin loadURLWithCookie:url cookie:cookie];
}


- (void)loadURLWithCookie:(const char *)url cookie:(const char *)cookie
{
    if (webView == nil)
        return;
    NSString *urlStr = [NSString stringWithUTF8String:url];
    NSString *cookieStr = [NSString stringWithUTF8String:cookie];
    NSURL *nsurl = [NSURL URLWithString:urlStr];

    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:nsurl];
    [request addValue:cookieStr forHTTPHeaderField:@"Cookie"];
    
    [webView load:request];
}
```

**Comment by KojiNakamaru** [comment]
Thanks for the note. If you need to put some cookie from Unity side, the following  as you tried initially
```
webViewObject.EvaluateJS(@"document.cookie = '" + your_cookie + "';");
```
should be okay. Perhaps you failed because you add the line `document.cookie = ...` inside `Unity.call()` function. Unless you call `Unity.call()` the line won't be called.

**Comment by montag64** [comment]
This works, thank you.

**Comment by tiancaipipi110** [comment]
> Thanks for the note. If you need to put some cookie from Unity side, the following as you tried initially
> 
> ```
> webViewObject.EvaluateJS(@"document.cookie = '" + your_cookie + "';");
> ```
> should be okay. Perhaps you failed because you add the line `document.cookie = ...` inside `Unity.call()` function. Unless you call `Unity.call()` the line won't be called.

How do you call `Unity.call()`? in Unity C# script? or in server html/php script?

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/166#issuecomment-462142460
