### ISSUE TITLE
How do I get the html source code?

### ISSUE THREAD

**Issue by doyongid** [gree/unity-webview#149]
I want to get the PIN code from the Twitter login page. The PIN code can be obtained from html source code.

I should get 4805960 from the example code.

```
<Div id = "oauth_pin">
       <P>
         <Kbd aria-labelledby = "code-desc"> <code> 4805960 </ code> </ kbd>
       </ P>
     </ Div>
```

Please tell me how. Thank you.

**Comment by KojiNakamaru** [comment]
You may utilize `WebViewObject#EvaluateJS()` to perform any javascript. In order to send a value to the Unity side, you can utilize `Unity.call()` in javascript. Please check the sample application.

**Comment by doyongid** [comment]
Thank you for answer.

Does iOS mode support JavaScript?

I tried to get the URL. But it only succeeded in Android.

Code: webViewObject.EvaluateJS ("if (location) window.Unity.call ('url:' + location.href);");

Does EvaluateJS work on iOS?

**Comment by doyongid** [comment]
Thank you for answer.

I succeeded in getting the html code from the Android version.

WebViewObject.EvaluateJS ("if (location) window.Unity.call (document.documentElement.innerHTML.toString ());");

I have parsed the PIN Code here.

But iOS failed. It is not returned. I saw the example source, but I do not understand it.

I had to study JavaScript to get the PIN code on Twitter. Please help me.

**Comment by KojiNakamaru** [comment]
Please perform the following before invoking `Unity.call()`:
https://github.com/gree/unity-webview/blob/d2b70548fccadadf6d7233cc63623ff7dff3c549/sample/Assets/Scripts/SampleWebView.cs#L49-L61
For ios/osx, `Unity.call()` isn't defined initially so that we need to define it at first.

**Comment by doyongid** [comment]
Thank you for answer.
I tried your advice, but iOS failed.

Is there a problem with the code below? I added the code in init ().
The Update () function checks every 2 seconds. Once all pages have been loaded, request the HTML code.

It works fine on Android.

You may be busy, but please review. Thank you.

```
    float m_fTimer;
    // Update is called once per frame
    void Update() 
    {
        if(webViewObject != null)
        {
            if(Time.time - m_fTimer > 2.0f)
            {
                m_fTimer = Time.time;

                /////////////////////////// PIN CODE Request  //////////////////////////
                webViewObject.EvaluateJS("if (location) window.Unity.call(document.documentElement.innerHTML.toString());");
            }
        }
    }

    void OnRequestTokenCallback(bool success, Twitter.RequestTokenResponse response)
    {
        if (success)
        {
            string log = "OnRequestTokenCallback - succeeded";
            log += "\n    Token : " + response.Token;
            log += "\n    TokenSecret : " + response.TokenSecret;
            print(log);

            m_RequestTokenResponse = response;

            webViewObject.Init(
            cb: (msg) =>
            {
                Debug.Log("## MSG : " + msg);

                int iStart = msg.IndexOf("<code>") + 6;
                int iEnd = msg.IndexOf("</code>");
                
                /////////////////////////// Get PIN CODE ////////////////////////
                if(iStart > 0 && iEnd > 0)
                    Debug.Log("## PIN CODE : " + mUrl + ", [" + msg.Substring(iStart, iEnd - iStart) + "]");
            },
            err: (msg) =>
            {
                Debug.Log(string.Format("CallOnError[{0}]", msg));
            },
            ld: (msg) =>
            {
                Debug.Log(string.Format("CallOnLoaded[{0}]", msg));

#if !UNITY_ANDROID
                webViewObject.EvaluateJS (@"
                window.Unity = {
                    call : function (msg) {
                    var iframe = document.createElement ( 'IFRAME');
                    iframe.setAttribute ( 'src', 'unity :'+ msg);
                    document.documentElement.appendChild (iframe);
                    iframe.parentNode.removeChild (iframe);
                    iframe = null;
                    }
                }
                ");
#endif
            },
            enableWKWebView: true);

            Twitter.API.OpenAuthorizationPage(webViewObject, response.Token);
        }
        else
        {
            print("OnRequestTokenCallback - failed.");
        }
    }
```

**Comment by KojiNakamaru** [comment]
I'm not sure where you show `webViewObject`, maybe in your customized `OpenAuthorizationPage()`? Also, you tried to send a whole html without any urlencode and this may cause troubles. As in the following, it is better to extract the minimum information you need in JavaScript and send it by `Unity.call()`:

```diff
--- tmp.cs.orig	2017-03-10 11:44:57.000000000 +0900
+++ tmp.cs	2017-03-10 11:58:08.000000000 +0900
@@ -9,7 +9,17 @@
                 m_fTimer = Time.time;
 
                 /////////////////////////// PIN CODE Request  //////////////////////////
-                webViewObject.EvaluateJS("if (location) window.Unity.call(document.documentElement.innerHTML.toString());");
+                webViewObject.EvaluateJS(@"
+                    (function() {
+                        if (window.Unity != null) {
+                            var div = document.getElementById('oauth_pin');
+                            if (div != null) {
+                                var code = div.getElementsByTagName('code')[0].innerText;
+                                window.Unity.call(code);
+                            }
+                        }
+                    })();
+                    ");
             }
         }
     }
@@ -60,6 +70,8 @@
 #endif
             },
             enableWKWebView: true);
+            webViewObject.SetMargins(0, 0, 0, 0);
+            webViewObject.SetVisibility(true);
 
             Twitter.API.OpenAuthorizationPage(webViewObject, response.Token);
         }
```

**Comment by doyongid** [comment]
Thank you for your kind reply.

I tried many things, but iOS still does not return a value.

However, OSX returned an error.

CallOnError [Error Domain = NSURLErrorDomain Code = -999 "(null)" UserInfo = {NSErrorFailingURLStringKey = https: //api.twitter.com/oauth/unity%20:2869756, NSErrorFailingURLKey = https: //api.twitter.com/ Oauth / unity% 20: 2869756}]

2869756 is PIN CODE.

**Comment by doyongid** [comment]
I have found one problem.

JavaScript does not work on Twitter URLs. (IOS, OSX)
(Ex: https://mobile.twitter.com/login)

However, other sites work well on iOS, OSX.

**Comment by KojiNakamaru** [comment]
Thanks for pointing out the issue. I've experimented small modification for the unity-webview sample app and found that `Unity.call()` with 'iframe' seemed somehow not working on the twitter login page. It is anyway a tricky method and I conclude that we should adopt a simpler approach, i.e., `location = 'unity:...'`. I'll later fixed SampleWebView.cs in the repository, too.

`EvaluateJS()` should work on https://mobile.twitter.com/login . For example, the following modification will add a 'call unity' link on the top of the twitter login page, which invokes 'window.Unity.call(123456789)' to call the Unity side.

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 8338c31..10dfc06 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -50,14 +50,27 @@ public class SampleWebView : MonoBehaviour
                 webViewObject.EvaluateJS(@"
                   window.Unity = {
                     call: function(msg) {
-                      var iframe = document.createElement('IFRAME');
-                      iframe.setAttribute('src', 'unity:' + msg);
-                      document.documentElement.appendChild(iframe);
-                      iframe.parentNode.removeChild(iframe);
-                      iframe = null;
+                      window.location = 'unity:' + msg;
                     }
                   }
                 ");
+                webViewObject.EvaluateJS(@"
+(function() {
+    function checkTwitterLoginLoaded() {
+        var div = document.getElementById('react-root');
+        if (div != null) {
+            var a = document.createElement('a');
+            a.setAttribute('href', 'javascript:void(0)');
+            a.setAttribute('onclick', 'window.Unity.call(123456789);return false;');
+            a.appendChild(document.createTextNode('call unity'));
+            document.body.insertBefore(a, div);
+        } else {
+            setTimeout(checkTwitterLoginLoaded, 1000);
+        }
+    }
+    setTimeout(checkTwitterLoginLoaded, 1000);
+})();
+                ");
 #endif
             },
             enableWKWebView: true);
```
![image](https://cloud.githubusercontent.com/assets/2645978/23822379/72f9eb42-068f-11e7-8fd7-e3175938a5e6.png)

Perhaps this new definition of 'Unity.call()' may also fix your original issue. Please note that you should extract the minum information as in https://github.com/gree/unity-webview/issues/149#issuecomment-285561021 and send it with `Unity.call()`.

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/111#issuecomment-260268749

**Comment by doyongid** [comment]
All features work well.
Thanks for always helping me.
Have a nice day.
