### ISSUE TITLE
Acces to the internal canvas

### ISSUE THREAD

**Issue by joelnl** [gree/unity-webview#15]
I'm trying to draw the webview on a 3d object, and i managed to get this working fine in the Unity Editor (including mouse position etc.)
However, this doesnt seem possible on  IOS or Android.

**Comment by KojiNakamaru** [comment]
unity-webview is designed to overlay a system-provided webview as is and its implementation for Editor is rather special. For utilizing webview rendering as textures, other approaches such as uWebKit might help.
