### ISSUE TITLE
Is it possible to get the current URL loaded in the Webview?

### ISSUE THREAD

**Issue by gamedevkev1** [gree/unity-webview#152]
Is it possible to get the current URL (string) of the page loaded in the Webview? 

For example, I would like to have a text field display the current url of the webview in the instance that the webview shown is not the starting webview, like in the case that a link is clicked.

**Comment by KojiNakamaru** [comment]
You can get the current url in the `ld` callback:

https://github.com/gree/unity-webview/blob/1bf35ae7a5073440953d67e087026186b5280f3b/sample/Assets/Scripts/SampleWebView.cs#L48

and can also dynamically send the current url by `Unity.call` and receive it in the `cb` callback:

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 2c362cf..a27e83d 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -105,6 +105,13 @@ public class SampleWebView : MonoBehaviour
         yield break;
     }
 
+    void Update()
+    {
+        if (webViewObject != null) {
+            webViewObject.EvaluateJS("if (Unity.call != null) { Unity.call(window.location); }");
+        }
+    }
+
 #if !UNITY_WEBPLAYER
     void OnGUI()
     {
```

https://github.com/gree/unity-webview/blob/1bf35ae7a5073440953d67e087026186b5280f3b/sample/Assets/Scripts/SampleWebView.cs#L36

**Comment by GameDevKaran** [comment]
Thanks for this great plugin
