### ISSUE TITLE
Webview Background Color

### ISSUE THREAD

**Issue by Russel1** [gree/unity-webview#16]
Is there a way to change the background color of the gree/unity-webview? How can I change the color of the webview on Unity3D?

**Comment by KojiNakamaru** [comment]
Recent versions allow to make a webview transparent (cf. https://github.com/gree/unity-webview/blob/770f34b6b5253bfa2e25fb651e72c62834ebe03c/plugins/WebViewObject.cs#L142 ). You can place any rendering behind a webview. Please reopen the issue if you need any assistance further.
