### ISSUE TITLE
How to run the sample Android

### ISSUE THREAD

**Issue by joshferns** [gree/unity-webview#164]
Hi I've used the sample project, imported the plugins, and made an Android build.
When I open the app there are three two GUI  buttons on the top right and the GUI text at the bottom left of the screen animates and disappears. Nothing else happens.
Is there something I'm missing?
I'm using unity 5.6.0 (didn't make any changes as is was mentioned that a post process build script would handle everything) 
Apologies if this is a noob question.

**Comment by KojiNakamaru** [comment]
When you build the sample app for the first time, the following should be displayed.
![image](https://cloud.githubusercontent.com/assets/2645978/25414359/20d10ade-2a6c-11e7-9e6a-c1b11234857e.png)
As noted here, you have to rebuild the app again to get a correct result. The post process script emits a customized AndroidManifest.xml under Assets/Plugins/Android so the second build will be correctly adjusted.
