### ISSUE TITLE
UnitySendMessage() failing on Mac in Unity 4.2.2f1?

### ISSUE THREAD

**Issue by IQpierce** [gree/unity-webview#17]
I integrated this plugin into my Unity project a while back with a few minor modifications. I had it disabled for a while and now I'm trying to use it again.

During that time I upgraded to Unity 4.2.2f1. It seems that, due to that upgrade (?), this line in "webView:decidePolicyForNavigationAction:request:frame:decisionListener:" consistently causes a crash (with no callstack, sadly) when running in editor on the Mac:

UnitySendMessage([gameObject UTF8String],
			"CallFromJS", [[url substringFromIndex:6] UTF8String]);

I can't determine exactly what's wrong, but the crash seems to occur on the line where UnitySendMessage() calls mono_runtime_invoke().

Last time I checked, the iOS version of the plugin worked fine. I'm unfamiliar with Mac plugins so I'm feeling around in the dark here; any insight would be appreciated!

**Comment by KojiNakamaru** [comment]
The latest version works without troubles (for Unity 5.x). Please reopen the issue if you need any assistance further.
