### ISSUE TITLE
Look's like cannot set webview in word space~

### ISSUE THREAD

**Issue by vilon888** [gree/unity-webview#172]
Hi , 
I tried this example, and cannot find any way to set the webview in word space. 

How can I set a word space position for webivew?

Thanks~

**Comment by KojiNakamaru** [comment]
Sorry, it cannot be placed in the world space for now. This plugin only allows to put a native WebView/UIWebview over Unity's rendering view.

**Comment by vilon888** [comment]
Got it . Thanks for you reply:)
