### ISSUE TITLE
can't call url scheme on android

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#174]
My application needs to send message from webview to unity.
I have read the implementation example in[ issue number 111](https://github.com/gree/unity-webview/issues/111). It works well on iOS, but not well on android.

So, I made a hyperlink on webview, and if it is clicked it will go back to the unity apps. And then the unity apps will catch the message.
Both `<a href=""></a>` and `Unity.call` works well on iOS.

On android, since the webview did not respond anything at first, I changed the setting in AndroidManifest.xml:
`<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />`
(the default is false).
If I changed the url of the link to for example google.com, it can open the google page.
However, it can not open url scheme (ERR_UNKNOWN_URL_SCHEME), and Unity.call seems not works too.

Is there anything I missed in the android setting?

**Comment by KojiNakamaru** [comment]
Could you please describe the version of unity and the android version of the target device? At least for recent unity 5.x, you don't need to add `unityplayer.ForwardNativeEventsToDalvik`. If you have `Assets/Plugins/Android/WebView.jar` and it is compiled into the final apk, everything should work.

**Comment by lutfianasari** [comment]
I am using unity 4.7.2f1 and android version 6.0.1
What I have in my plugin directory is `Assets/Plugins/Android/WebViewPlugin.jar`

My Apologize, It seems that I used a bit older version of the plugin.
I changed it to the newest version and it now can open url scheme.
However, Unity.call is still not working, and I have to make `unityplayer.ForwardNativeEventsToDalvik` value to `true`.
I have not compiled it to apk file. Instead, I exported it to android project and opened it with android studio because I wanted to add some configuration from android studio. I will update here when I compiled it to apk.

**Comment by KojiNakamaru** [comment]
I tried the latest plugin for Unity 4.7.2f1 and Android 6.0.1 (Nexus 7/2013) and it worked. I put the following under Assets/Plugins/Android/, which is based on `Temp/StagingArea/AndroidManifest-main.xml`, and select "Build And Run" from Build Settings.

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="net.gree.unitywebview.sample" android:installLocation="preferExternal" android:versionName="1.0" android:versionCode="1">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true">
    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
    </activity>
  </application>
  <uses-sdk android:minSdkVersion="9" android:targetSdkVersion="25" />
</manifest>
```

**Comment by lutfianasari** [comment]
Thank you very much for your help. I think for general solution, we need to add those codes under Assets/Plugins/Android as you said. However,  in my case I need to compile my unity project to android project, so I had to put that configuration after I opened in Android Studio.

By the way, using the newest version of the plugin, I found new error when I switch platform to iOS. (still using Unity 4.7.2f1)
> Assets/Plugins/iOS/Editor/UnityWebViewPostprocessBuild.cs(5,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor'. Are you missing an assembly reference?

Did you find it too?

**Comment by KojiNakamaru** [comment]
> Thank you very much for your help. I think for general solution, we need to add those codes under Assets/Plugins/Android as you said. However, in my case I need to compile my unity project to android project, so I had to put that configuration after I opened in Android Studio.

It should be okay, and even if you export a android project, there will be AndroidManifest.xml if you put AndroidManifest.xml above under Assets/Plugins/Android/.

> Did you find it too?

Yes, UnityEditor.iOS.Xcode is bundled with Unity 5.x. Please remove/comment out UnityWebViewPostprocessBuild.cs. You can add WebKit.framework manually after emitting an iOS project.

**Comment by lutfianasari** [comment]
Very grateful of your hint to add WebKit.framework manually after emitting the iOS project.
I'm sorry if this question is a little bit out of the topic, I successfully install my application on iPhone after adding WebKit.framework, but the hyperlink that now works well on android, doesn't work well on iPhone.

It produced the following error:

> [DYDisplayLinkInterposer UTF8String]: unrecognized selector sent to instance 0x174038f00
> *** WebKit discarded an uncaught exception in the webView:didFinishLoadForFrame: delegate: <NSInvalidArgumentException> -[DYDisplayLinkInterposer UTF8String]: unrecognized selector sent to instance 0x174038f00}

I wonder if you have any clue about those error, and thank you very much for your time helping me along.

**Comment by lutfianasari** [comment]
I read the solution  you give on the previous issue to double-click-ed `WebView.mm` from Build `Phases/Compile Sources` and add `-fobjc-c`
Unity.call works, but UnitySendMessage() doesn't work.

**Comment by KojiNakamaru** [comment]
I've tried with Unity 4.7.2f1. First, I set the target iOS to 8:

![image](https://cloud.githubusercontent.com/assets/2645978/26135746/9a6316b2-3af2-11e7-802b-2e2243a2cd4a.png)

Then for the emitted Xcode project, I set `-fobjc-arc` for WebView.mm in "Build Phase/Compile Sources" and added WebKit.framework in "Link Binaries With Libraries".

![image](https://cloud.githubusercontent.com/assets/2645978/26135417/53f87eee-3af0-11e7-8f28-1b720a0ea698.png)

![image](https://cloud.githubusercontent.com/assets/2645978/26135422/589d6860-3af0-11e7-8db9-22ec8072aa05.png)

With this configuration, I ran the sample app successfully on iPad 3 (iOS 9.3.5). I'm using Xcode 8.2.1. Could you please try these steps?

**Comment by lutfianasari** [comment]
Yes, now it's solved.
You helped me a lot. Many thanks! <3
