### ISSUE TITLE
How can I display a pdf document?

### ISSUE THREAD

**Issue by ryo-ma** [gree/unity-webview#180]
I want to display a pdf document into webview when I moved web page.
Environment is android.

**Comment by KojiNakamaru** [comment]
As discussed the link in https://github.com/gree/unity-webview/issues/91#issuecomment-230647247, the google docs pdf viewer seems only the solution. For example,
```html
<a href="https://docs.google.com/gview?embedded=true&amp;url=http://foo/boo/woo/aboo.pdf">aboo.pdf</a>
```

**Comment by ryo-ma** [comment]
Thank you reply, I want to display other people's page where HTML can not be changed.

I want to make it like the following code.
```
public void somethingCallback(){
    if(url.endsWith(".pdf")){
        webview.loadUrl("http://drive.google.com/viewerng/viewer?embedded=true&url=" + url);
    }
}
```
Will you planning to support to pdf for android?

**Comment by KojiNakamaru** [comment]
How about utilizing JavaScript as in https://github.com/gree/unity-webview/issues/175:
```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 4311168..74a7b33 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -54,6 +54,18 @@ public class SampleWebView : MonoBehaviour
                     }
                   }
                 ");
+#else
+                webViewObject.EvaluateJS(@"
+                  (function() {
+                    var links = document.links;
+                    for (var i = 0; i < links.length; i++) {  
+                      var l = links[i];
+                      if (/\.pdf$/.test(l.href)) {
+                        l.href = 'https://docs.google.com/gview?embedded=true&url=' + encodeURI(l.href);
+                      }
+                    }
+                  })();
+                ");
 #endif
                 webViewObject.EvaluateJS(@"Unity.call('ua=' + navigator.userAgent)");
             },
```
This rewrites links for pdf files in the `ld:` callback.

**Comment by ryo-ma** [comment]
Thank you for reply!
That went well!

**Comment by sbaysan** [comment]
I've tried this but it still doesn't work.. Also after installing Google Drive PDF Viewer. I'm still clicking on buttons that should trigger  PDF urls but nothing happens. I'm using a Samsung Galaxy S10.

**Comment by KojiNakamaru** [comment]
I investigated the issue again and found the code didn't work for Android 11 or later. I've fixed it in #834 and updated binaries. Could you please try the latest? I also put an example https://github.com/gree/unity-webview/tree/example-for-180/sample that can be directly opened and built with 2020.3.34f1.

**Comment by sbaysan** [comment]
I've tried it and it worked for me. Thank you very much!

**Comment by unobatbayar** [comment]
Sorry to bump in, what if the URL itself is a pdf link in the first place? 

How should we display this on Android? Do we use the same logic?

I'm tried it like 

```cs
            #if UNITY_ANDROID
                Url = "https://drive.google.com/viewerng/viewer?embedded=true&url=" + URL;
            #endif
```

But it doesn't seem to work when I build to actual Android device. iOS works well.

Hmm...
