### ISSUE TITLE
What do you recommend for calling a unity function with arguments from javascript

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#187]
In your example of communication from javascript to unity you send a string. What do you recommend  for calling a unity function with arguments from javascript?  

 cb: (msg) =>
            {
                Debug.Log(string.Format("CallFromJS[{0}]", msg));
                status.text = msg;
                status.GetComponent<Animation>().Play();
},

**Comment by KojiNakamaru** [comment]
For example, you can utilize json as below.

(JavaScript)
```javascript
function foo(str, num)
{
    var arg = {
        method: 'foo',
        args: [ str, num ]
    };
    Unity.call(JSON.stringify(arg));
}
```

(C#)
```c#
cb: (arg) =>
{
    var json = LitJson.JsonMapper.ToObject(arg);
    switch ((string)json["method"]) {
    case "foo":
        foo((string)json["args"][0], (int)json["args"][1]);
        break;
    }
}
```

**Comment by whimsica** [comment]
Thanks.
