### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#188]
Is there a way to send actual javascript errors and also console.log output to Debug.Log?

**Comment by KojiNakamaru** [comment]
You can override `console.log` as below and can call `Debug.Log` or do anything in the Unity side.
```javascript
      (function() {
        var old = console.log;
        console.log = function() {
          Unity.call(arguments[0]);
          old.apply(this, arguments);
        };
      })();
```

**Comment by whimsica** [comment]
I can override console.log as you suggest and can send javascript errors to Debug.Log by using

window.onerror = function (msg, url, line, column, error) {
Unity.call(msg+"line:"+line);
}

What kinds of errors are caught by err in the code below?  

 err: (msg) =>
            {
                Debug.Log(string.Format("CallOnError[{0}]", msg));
                status.text = msg;
                status.GetComponent<Animation>().Play();
            },

**Comment by KojiNakamaru** [comment]
It is called when loading is failed. But, I found it wasn't implemented for WKWebView so I fixed it in https://github.com/gree/unity-webview/pull/190 .  Could you please try the latest.

**Comment by whimsica** [comment]
Thanks.
