### ISSUE TITLE
The buttons on the site are not clickable on Android.

### ISSUE THREAD

**Issue by Roman15SM** [gree/unity-webview#19]
When I open site on Android, I can't click on any button.

**Comment by thanh06** [comment]
@jtothebell  do you have skyper?

You can help me fix this?

**Comment by KojiNakamaru** [comment]
This should also be caused by NativeActivity (cf. https://github.com/gree/unity-webview/issues/6 ). Recent Unity and unity-webview combination doesn't have the issue. Please reopen the issue if you need any assistance further.
