### ISSUE TITLE
Is youtube playback possible?

### ISSUE THREAD

**Issue by lexar** [gree/unity-webview#192]
Hello, someone else asked this before, but closed the issue without comment.
I added a youtube URL to the sample app and opened in the editor. I see the youtube page and am able to click on the play icon. But then I see that spinning loading indicator, but the video is never played.
Is there something I can do about that?
Thanks, l

**Comment by KojiNakamaru** [comment]
Unfortunately YouTube won't be played back correctly on Unity Editor for now. It should be played well on Android/iOS.

**Comment by lexar** [comment]
Thanks! May I ask why that is? Is there anything I could do?

**Comment by KojiNakamaru** [comment]
Could you please check the following?
https://github.com/gree/unity-webview/issues/63#issuecomment-174369462

Also, you might want to look WebViewSeparated:
https://github.com/gree/unity-webview/tree/b542882718e106640ed83e875461d8d4b6cca944#webviewseparatedbundle

Though it is for debugging, you can get a on-screen webview in a separate window:
![image](https://user-images.githubusercontent.com/2645978/26913772-ffe73e20-4c57-11e7-9c31-f36caf7a694b.png)

**Comment by lexar** [comment]
Thanks a lot. I didn't find #63 when I searched issues, sorry.
