### ISSUE TITLE
Crash in iOS 11 + Xcode 9 beta

### ISSUE THREAD

**Issue by amaike** [gree/unity-webview#195]
Unity 5.6.1p2 + iOS 11 beta + Xcode 9 beta for iPad Air2

log

2017-06-08 10:29:19.076465+0900 Webview[1028:307906] [] network_config_register_boringssl_log_debug_updates Failed to register for BoringSSL log debug updates
2017-06-08 10:29:19.094173+0900 Webview[1028:307805] Uncaught exception: NSInternalInconsistencyException: Completion handler passed to -[CWebViewPlugin webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once
(
	0   CoreFoundation                      0x00000001896a6500 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001abc58528 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001896a6430 <redacted> + 0
	3   WebKit                              0x000000019198d8c0 <redacted> + 216
	4   WebKit                              0x00000001919d36f4 <redacted> + 56
	5   Webview                             0x0000000103208ac4 -[CWebViewPlugin webView:decidePolicyForNavigationAction:decisionHandler:] + 2220
	6   WebKit                              0x00000001919d1258 <redacted> + 968
	7   WebKit                              0x0000000191b33fcc <redacted> + 1072
	8   WebKit                              0x0000000191b5cc78 <redacted> + 92
	9   WebKit                              0x0000000191b5632c <redacted> + 240
	10  WebKit                              0x00000001919cebdc <redacted> + 128
	11  WebKit                              0x0000000191ba8e50 <redacted> + 36
	12  WebKit                              0x0000000191990440 <redacted> + 196
	13  WebKit                              0x000000019198ddb8 <redacted> + 140
	14  WebKit                              0x0000000191990670 <redacted> + 232
	15  JavaScriptCore                      0x000000018ca66208 <redacted> + 344
	16  JavaScriptCore                      0x000000018ca66438 <redacted> + 36
	17  CoreFoundation                      0x000000018964d1a0 <redacted> + 24
	18  CoreFoundation                      0x000000018964c9d4 <redacted> + 276
	19  CoreFoundation                      0x000000018964a57c <redacted> + 832
	20  CoreFoundation                      0x000000018956503c CFRunLoopRunSpecific + 436
	21  GraphicsServices                    0x0000000199d97f94 GSEventRunModal + 100
	22  UIKit                               0x000000019052a86c UIApplicationMain + 208
	23  Webview                             0x0000000102cac174 main + 228
	24  libdyld.dylib                       0x00000001ac9b9d1c <redacted> + 4
)
2017-06-08 10:29:19.094950+0900 Webview[1028:307805] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[CWebViewPlugin webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'
*** First throw call stack:
(0x1896a64e8 0x1abc58528 0x1896a6430 0x19198d8c0 0x1919d36f4 0x103208ac4 0x1919d1258 0x191b33fcc 0x191b5cc78 0x191b5632c 0x1919cebdc 0x191ba8e50 0x191990440 0x19198ddb8 0x191990670 0x18ca66208 0x18ca66438 0x18964d1a0 0x18964c9d4 0x18964a57c 0x18956503c 0x199d97f94 0x19052a86c 0x102cac174 0x1ac9b9d1c)
libc++abi.dylib: terminating with uncaught exception of type NSException

![2017-06-08 10 30 11](https://user-images.githubusercontent.com/11954681/26908466-c4629dc6-4c35-11e7-863d-8c4315857df7.png)
![2017-06-08 10 30 20](https://user-images.githubusercontent.com/11954681/26908475-c9986b9a-4c35-11e7-882f-cce9d5cda487.png)

**Comment by KojiNakamaru** [comment]
Thank you for the report. Although I haven't tested with iOS 11 beta + Xcode 9, I found an issue and fixed it in #196. Could you please try the latest?

**Comment by amaike** [comment]
Thanks ! It was Fixed.
