### ISSUE TITLE
Question about javascript bridge differences on osx and ios

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#199]
I'm sending some information back and forth using the javascript bridge. On osx the information is sent back and forth immediately. For example if I send a command to javascript and a return command during FixedUpdate it is sent back before FixedUpdate finishes. Same with Update and Late Update.

On IOS if I send a command to javascript during FixedUpdate it doesn't return until fixed,update,late have occured, or a frame later.

Why is there a difference? It doesn't seem related to the framerate.
Is there any way to get the javascript bridge to return immediately on ios rather than a frame later?

**Comment by KojiNakamaru** [comment]
The bridge is based on `location` or `iframe`:

https://github.com/gree/unity-webview/blob/97293c85e7ae95a17d9e3beb9e1003299c090427/sample/Assets/Scripts/SampleWebView.cs#L50-L73

Especially the `location` approach may cause a delay, but even the `iframe` approach still have some delay. If you only need to support WKWebView, you can utilize `window.webkit.messageHandlers.unityControl.postMessage()` which is much efficient (cf. https://github.com/gree/unity-webview/issues/189).

After the Objective-C code receiving a message from JavaScript, however, it utilizes `UnitySendMessage()` to send a event to C#. It is safe but asynchronous so may cause another delay. If you also need to avoid this delay, you could try `MonoPInvokeCallback`:

https://forum.unity3d.com/threads/monopinvokecallback-in-unity.132510/

**Comment by whimsica** [comment]
Thank you very much for the information about what might cause delays. I tried the wkwebview version also and it had the same issues. I will do some experiments with location vs iframe and UnitySendMessage vs MonoPInvokeCallback.

**Comment by whimsica** [comment]
I built a test project to see the problems more clearly. It fires off calls to javascript functions that call unity back during FixedUpdate, Update, and LateUpdate and documents when they return.

I tried getting rid of the iframe methods, and also using setTimeouts to delay the iframes. I also did some more experiments with wkwebview. In the experiments the return calls from javascript always seem to happen after LateUpdate no matter when they are called. Also they return at random times after LateUpdate. According to documentation on UnitySendMessage it has a one frame delay so this may be the problem.  I also downloaded a few more projects for unity including `http://uniwebview.onevcat.com/` and it has the same frame delays. If it's possible to fix it would be very powerful to get immediate synchronous returns from javascript. I've been reading up on MonoPInvokeCallback, but unfortunately it's beyond my expertise to put together an example to see if it solves the problem.  If you have time could you provide some example code that I could try with my test system to see if it's possible to solve the problem? Thank you.

**Comment by KojiNakamaru** [comment]
I've implemented `CallMethod` based on MonoPInvokeCallback, so please check it:
https://github.com/gree/unity-webview/tree/experimental/monopinvokecallback
Please note it is experimental and works only for osx and ios.

**Comment by whimsica** [comment]
Great. I'll run some experiments and get back to you.

**Comment by whimsica** [comment]
Success! There are now no frame delays. I am sending EvaluateJS with return calls consecutively in FixedUpdate, Update, and LateUpdate. The returns are immediate and everything stays in sync.
