### ISSUE TITLE
WebView Error

### ISSUE THREAD

**Issue by dajver** [gree/unity-webview#20]
Hi, i had this issues when I click to play button in unity editor, I use unity 4.3 and I don't know how to fix this error. Web browser doesnt work and nothing works after start scene... Help please.

DllNotFoundException: WebView
WebViewObject.Init (System.Action`1 cb) (at Assets/plugins/WebViewObject.cs:139)
SampleWebView.Start () (at Assets/Scripts/SampleWebView.cs:34)

**Comment by doodoori2** [comment]
how about make an unsupported excepion for unity window editor ?

**Comment by yanakend** [comment]
https://github.com/gree/unity-webview/issues/28

**Comment by yanakend** [comment]
I fixed same problem by refer below 
https://github.com/gree/unity-webview/issues/28

**Comment by crystaldns11** [comment]
I want to plugin support use webview for winstore , pls help me ! thanks u very much

**Comment by KojiNakamaru** [comment]
unity-webview utilizes system-provided webkit-based webviews. Because such a webkit component is not available on Windows flavors, it is difficult to support them. Please reopen the issue if you need any assistance further.
