### ISSUE TITLE
IOS scroll issue

### ISSUE THREAD

**Issue by antoniohof** [gree/unity-webview#209]
On Android, It's possible to fast scroll by swiping fast and then removing the finger, letting it scroll automatically until it slowly stops. 
On IOS, as soon as I remove my finger the scroll stops. 

Is there any configuration to enable this on IOS?
I'm using WKWebView.

Thanks,

**Comment by KojiNakamaru** [comment]
There is no configuration provided in this plugin. You might modify the iOS implementation part as done in
https://stackoverflow.com/questions/31369538/cannot-change-wkwebviews-scroll-rate-on-ios-9-beta-9-3
but I think it should not be changed otherwise it behaves differently from Safari.
