### ISSUE TITLE
javascript not work on android (unity 4.7.2f1)

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#211]
I am using Unity 4.7.2f1 and downloaded the recent version of this plugin (downloaded last month).
It seems that javascript doesn't work on Android (there is no problem on iOS).
I can not use Unity.call or other javascript/jquery function.

I added `android:hardwareAccelerated="true"` and added `<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />`  to the manifest.
I tried it using emulator Nexus 6 (API 25) and Xiaomi Redmi 4 (API 23).

Do I miss any additional setting?
Thank you in advance.

**Comment by KojiNakamaru** [comment]
Your configuration seems to be okay. I've tried with the following AndroidManifest.xml and successfully made the sample app runs on Nexus 7 (2013, Android 6.0.1). At least if touch events work (for example you can move to https://google.com), there might be any error message about JavaScript shown in adb logcat stream when you tap `[Send Message]` link/button.
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="net.gree.unitywebview.sample" android:installLocation="preferExternal" android:versionName="1.0" android:versionCode="1">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true">
    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name" android:hardwareAccelerated="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
    </activity>
  </application>
  <uses-sdk android:minSdkVersion="9" android:targetSdkVersion="26" />
</manifest>
```

**Comment by lutfianasari** [comment]
I tried the sample app on Android.
The google url can  be clicked, and [Send Message] also work.

In my app, I can click url and also open google page.
Google page seems work find.

I found out that if I put javascript code inside onclick, for example:
`<a href="#" onclick="alert('test')">test</a>` -> works ok
but, if I made a javascript function, and put the function on the html page, it didn't work.
`<a href="#" onclick="my_function()">test</a>` -> not work

so, maybe it couldn't read the javascript function.
however, I included jquery mobile on the page, and seems working find.
I will try including javascript file, instead of adding the javascript function on the html, and will update the result here.

**Comment by KojiNakamaru** [comment]
If you want to include your JavaScript files in StreamingAssets, you need to write them as done for sample.html. Could you please check the discussion in #191, especially https://github.com/gree/unity-webview/issues/191#issuecomment-306716413, and also https://github.com/gree/unity-webview/issues/193.

**Comment by lutfianasari** [comment]
Yes, thank you very much. I'm sorry for the lack of my testing. 
I can include javascript file in the head part of html, and thanks for the information about putting javascript in StreamingAssets. In my case, I need to put the html, js, etc in server, not in Assets.
I'm just wondering why it can work well on iOS, but not on android. Maybe, this is the problem of the OS.
I will close the issue. You helped me again this time. Many thanks!!
