### ISSUE TITLE
Invoke unity function from Javascript or listen/trigger from redirect http response

### ISSUE THREAD

**Issue by paatz04** [gree/unity-webview#220]
Hey there! Awesome work.

I was wondering if there is a way to listen to javascript function and invoke a unity function. 
I couldn't find a documentation. Any hints ? 

I would like to build a user login form and a short quizz and use that in my webview. I need to somehow listen to the submit event and close the webform. Or can i register to redirects ? For example close the webview when a certain response is returned.

Do I have to work with the init function I suppose ? I assume I can use cb - > call from JS. Do you have a JS sample that would trigger cb?

Thanks!

**Comment by KojiNakamaru** [comment]
The sample app shows how to interract between Unity and HTML. If you want to call the Unity-side, you can utilize `Unity.call()`, for example:

https://github.com/gree/unity-webview/blob/95fc7afcb575a2bbd8129fcb2f720d162d4d478c/sample/Assets/StreamingAssets/sample.html#L13

If you want to call the JavaScript-side, you can utilize `EvaluateJS()`, for example:

https://github.com/gree/unity-webview/blob/95fc7afcb575a2bbd8129fcb2f720d162d4d478c/sample/Assets/StreamingAssets/sample.html#L13

**Comment by paatz04** [comment]
Hey! Thanks for the quick and prompt reply! 
So :    ` <p><a href="javascript:void(0)" onclick="Unity.call('anchor');">[Send Message!]</a></p>`
Calls the cb action added to the webViewObject.init() with the msg="anchor" ?

**Comment by KojiNakamaru** [comment]
Yes, it behaves as you noted. So you can communicate between Unity and HTML (JavaScript) in both directions.

**Comment by paatz04** [comment]
Thanks a lot! Easy and simple. I'm about to use it in production. Are you aware of any limitations on iOS / android ? Does it support Android SDK >=15 and iOS >=8? Cheers
It works fine on my devices 👍

**Comment by KojiNakamaru** [comment]
Yes, it should run well on android with API version 15 or later and iOS 8 or later.

**Comment by paatz04** [comment]
Hey again. I tried the sample scene with the local html file but i'm not getting any log in my console when using it in Unity Editor. Does it only work on actual devices ? I do get nothing for the call('anchor') 


and i do get this error for the form button:

`CallOnError[Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSUnderlyingError=0x600000a5eae0 {Error Domain=kCFErrorDomainCFNetwork Code=-1100 "The requested URL was not found on this server."`

I tried on my actual site, and didn't get any logs either. What am I doing wrong ? 
Thanks for your time!

**Comment by paatz04** [comment]
what is a production ready pre-processor flag for android. The sample app uses:

`#if !UNITY_ANDROID
                // NOTE: depending on the situation, you might prefer
                // the 'iframe' approach.
                // cf. https://github.com/gree/unity-webview/issues/189
#if true
                webViewObject.EvaluateJS(@"
                  window.Unity = {
                    call: function(msg) {
                      window.location = 'unity:' + msg;
                    }
                  }
                ");
#else
                webViewObject.EvaluateJS(@"
                  window.Unity = {
                    call: function(msg) {
                      var iframe = document.createElement('IFRAME');
                      iframe.setAttribute('src', 'unity:' + msg);
                      document.documentElement.appendChild(iframe);
                      iframe.parentNode.removeChild(iframe);
                      iframe = null;
                    }
                  }
                ");
#endif
#endif
`

But that doesn't work on android at all. 
Does going with 

` webViewObject.EvaluateJS(@"
                  window.Unity = {
                    call: function(msg) {
                      window.location = 'unity:' + msg;
                    }
                  }
                ");`

Work in any case for android >15 and ios>8. Or what do you suggest?

Thanks!

**Comment by KojiNakamaru** [comment]
The sample app *doesn't* define `Unity.call()`:

https://github.com/gree/unity-webview/blob/e5f15764fe20d537362691bcc39ef32e103eb4ad/sample/Assets/Scripts/SampleWebView.cs#L49-L74

because `Unity.call()` is defined in WebViewPlugin.jar:

https://github.com/gree/unity-webview/blob/e5f15764fe20d537362691bcc39ef32e103eb4ad/plugins/Android/src/net/gree/unitywebview/CWebViewPlugin.java#L60-L63
https://github.com/gree/unity-webview/blob/e5f15764fe20d537362691bcc39ef32e103eb4ad/plugins/Android/src/net/gree/unitywebview/CWebViewPlugin.java#L185

> When calling LoadURL(), is there a way to clear the webview (show white while loading) instead of showing the previous website until it finishes loading ?

You could utilize `EvaluateJS()` and/or `LoadHTML()` to show some loading animation while redirecting to the next page.

**Comment by paatz04** [comment]
Thank you!!! That means it should work without the injection for android, so I can use the compiler flag, and therefore only inject it through EvaluateJs for iOS ? 
I noticed injecting it for android as well works anyway though 


ok

**Comment by KojiNakamaru** [comment]
> Thank you!!! That means it should work without the injection for android, so I can use the compiler flag, and therefore only inject it through EvaluateJs for iOS or does it do a similar thing for iOS?

The injection is required only for iOS. If you only utilize WKWebView (by specifying `enablWKWebView: true` and limiting iOS versions to 8 or later), you can utilize more efficient/reliable `window.webkit.messageHandlers.unityControl.postMessage()` (introdueced by @dragonx in #161) instead of `Unity.call()` and don't need the injection.

> I noticed injecting it for android as well works anyway though

Yes, it also works because `unity:` prefixed URLs can also work for Android. However, natively defined `Unity.call()` should be more efficient.
