### ISSUE TITLE
Is it possible to use texture sphere?

### ISSUE THREAD

**Issue by SemiMoon95** [gree/unity-webview#228]
Is it possible to use it as texture on some object like a sphere in android?
I saw #186 , but that is OS X. 
How can I do that in sphere?

**Comment by KojiNakamaru** [comment]
Sorry, currently it is not possible. cf. https://github.com/gree/unity-webview/issues/198#issuecomment-308906318

**Comment by SemiMoon95** [comment]
ok thanks
