### ISSUE TITLE
WebView issue in Android

### ISSUE THREAD

**Issue by binspaul** [gree/unity-webview#23]
Hi,

I was not able to open an url using the plugiin n Android. I used the 'sample' project that was available with the source. I imported the 'unity-webview' package available in the 'dist' folder. I added a section to detect if the runtime is Android and open the url.

The url was set to: http://www.google.com

Thanks,
BP

**Comment by gsssrao** [comment]
You need to add permission for internet in manifest. Add this to Plugins/Android/ 
Create the following manifest
    <?xml version="1.0" encoding="utf-8"?>
            <manifest
                xmlns:android="http://schemas.android.com/apk/res/android"
                package="com.unity3d.player"
                android:installLocation="preferExternal"
                android:theme="@android:style/Theme.NoTitleBar"
                android:versionCode="1"
                android:versionName="1.0">
                <uses-feature android:name="android.hardware.camera" />
                <supports-screens
                    android:smallScreens="true"
                    android:normalScreens="true"
                    android:largeScreens="true"
                    android:xlargeScreens="true"
                    android:anyDensity="true"/>
                <uses-permission android:name="android.permission.INTERNET" />
                <uses-permission android:name="android.permission.CAMERA" />
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
                
                <application
                    android:icon="@drawable/app_icon"
                    android:label="@string/app_name"
                    android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
                    android:debuggable="false">
                    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity"
                              android:label="@string/app_name">
                        <intent-filter>
                            <action android:name="android.intent.action.MAIN" />
                            <category android:name="android.intent.category.LAUNCHER" />
                        </intent-filter>
                        <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
                        <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
                    </activity>
                    <activity android:name="com.unity3d.player.VideoPlayer"
                              android:label="@string/app_name"
                              android:screenOrientation="portrait"
                              android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
                    </activity>
                    
                    <uses-library android:name="com.ti.s3d" android:required="false" />
                </application>
            </manifest>

**Comment by KojiNakamaru** [comment]
Though you still need to prepare AndroidManifest.xml for performance (cf. https://github.com/gree/unity-webview/tree/770f34b6b5253bfa2e25fb651e72c62834ebe03c#android ), the latest version should work without troubles. If you need any assistance further, please reopen the issue.
