### ISSUE TITLE
Some website see with zoomed in when first showing

### ISSUE THREAD

**Issue by theolovesyou** [gree/unity-webview#230]
Hi. 
I like your webview but i have some problems.

Not every website, some website already zoomed in when webview is showing.
Can i control it with code?

This happend only in android. IOS is ok.

Thanks.

**Comment by KojiNakamaru** [comment]
Thank you for the report. I haven't reproduce the issue yet, but I modified the code to fix it in #231. Could you please try the latest?

**Comment by theolovesyou** [comment]
I tried the latest version and it works well!
Thank you again!!

**Comment by theolovesyou** [comment]
I tried the latest version and it works well!
Thank you again!!
