### ISSUE TITLE
How to change the WebView size?

### ISSUE THREAD

**Issue by jack9766** [gree/unity-webview#234]
Do I need to change the constant some where or call a method?

**Comment by QuentinGprd** [comment]
`SetMargins(int left, int top, int right, int bottom)`

or

`SetCenterPositionWithScale(Vector2 center, Vector2 scale)`

**Comment by KojiNakamaru** [comment]
Yes, `SetMargins()` is supported on both Android/iOS. By computing margins adequately, you can adjust the window size/position to any degree.
