### ISSUE TITLE
webview language

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#239]
Hi again,
I have a question,
how can we change the language of the webview?
for example, if we make a dropdown select on iOS, there will be a "Done" on the top right to close the dropdown. I want to make it into other language (in my case, into japanese).
Is the default of this plugin using english?
I tested it using iPhone 5s and 7, and set the language of the phone into japanese.
When I opened my html page using safari, the language is already in japanese.

![done](https://user-images.githubusercontent.com/1013933/29344732-e013539c-8274-11e7-8560-9d6fc77db495.png)

**Comment by KojiNakamaru** [comment]
The button utilizes the system setting language by adding the following to Info.plist.
```
    <key>CFBundleAllowMixedLocalizations</key>
    <true />
```
cf. https://stackoverflow.com/questions/3856158/uiwebview-localization/3896330#3896330

**Comment by lutfianasari** [comment]
Thank you very much. Problem solved.
I'm sorry for my lack of researching.
