### ISSUE TITLE
DllNotFoundException: WebView WebViewObject.Init

### ISSUE THREAD

**Issue by irsalshabirin** [gree/unity-webview#24]
I import the project in unity Version 4.5.2f1.
and then I upgrade this project
![1](https://cloud.githubusercontent.com/assets/4993269/4129533/78aa9f0c-3322-11e4-9725-f8b339d23d51.png)

and then i have problem when compile the project and shows the error like this :+1: 
DllNotFoundException: WebView
WebViewObject.Init (System.Action`1 cb) (at Assets/Plugins/WebViewObject.cs:119)
SampleWebView.Start () (at Assets/Scripts/SampleWebView.cs:34)

what should i do? thank you for your attention and i hope you will be pleasure to answer me. :-)

**Comment by WorlazMighty** [comment]
Am having the same issue.

Using Unity 4.6.2


DllNotFoundException: WebView
WebViewObject.Init (System.Action`1 cb) (at
Assets/Plugins/WebViewObject.cs:119)
SampleWebView.Start () (at Assets/Scripts/
SampleWebView.cs:34)

**Comment by KojiNakamaru** [comment]
For now unity-webview doesn't support Unity for Windows. WebView.bundle for OSX is provided but there is no WebView.dll for Windows.

**Comment by WorlazMighty** [comment]
Any Possibility it can work on Windows ?

**Comment by KojiNakamaru** [comment]
For now unity-webview relies on webkit-based webview implementation provided by each OS. Because there is no such implementation on Windows, it is difficult to support Windows.

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
