### ISSUE TITLE
Change viewport/enable scrolling when software keyboard pops up

### ISSUE THREAD

**Issue by paatz04** [gree/unity-webview#244]
Hi!

When I have a form, after focusing a input the software keyboard pops up.
In the browser the viewport is resized so the content above the keyboard scrolls. 

Is there a way to archive the same functionality within the webview ? Not sure how to solve this

Thanks!

**Comment by KojiNakamaru** [comment]
I've put https://github.com/gree/unity-webview/pull/245 to fit a webview with the software keyboard display. It behaves differently from the current implementation and also requires to clear the fullscreen setting, so for now I leave it experimental.

**Comment by paatz04** [comment]
Thanks for that. 
I guess for now it's better to "hack" it by adding negative space to the bottom, and allow scrolling that way.

**Comment by KojiNakamaru** [comment]
I've finally implemented https://github.com/gree/unity-webview/pull/300 based on https://github.com/gree/unity-webview/pull/245#issuecomment-328618624 .
