### ISSUE TITLE
android call on page loaded twice

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#251]
I am accessing webpage from unity using the following code:
`webViewObject.Init(`
`  cb: (msg)=>...,`
`  ld: (msg)=>{`
`    Debug.Log("call on loaded");`
`  }`
`);`

In iPhone, the debug log "call on loaded" is shown once, but in android it is shown twice.
Did you find this too?

**Comment by KojiNakamaru** [comment]
The android implementation simply utilizes `WebViewClient#onPageFinished` and this method has the issue you described, depending on pages the WebView loading. For such cases, it might be necessary to check whether `location` becomes stable by JavaScript.

**Comment by lutfianasari** [comment]
> For such cases, it might be necessary to check whether `location` becomes stable by JavaScript.

I want to do something after page loaded, but it should not be run twice.
I thought I had to edit the plugin to solve my problem, but it would be easier if I can do that with javascript.
Would you please explain how to check whether `location `becomes stable using javascript?
I'm sorry, I don't really understand about checking `location` .

**Comment by KojiNakamaru** [comment]
The following example diff is for the sample app. The page is recognized stable if there is no `ld:` callback call in one second. It is a bit tricky and not perfect but might be utilized. 
```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 9ec7973..2f297a0 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -26,6 +26,9 @@ public class SampleWebView : MonoBehaviour
     public string Url;
     public GUIText status;
     WebViewObject webViewObject;
+    string url0;
+    string url1;
+    float t0;
 
     IEnumerator Start()
     {
@@ -34,6 +37,10 @@ public class SampleWebView : MonoBehaviour
             cb: (msg) =>
             {
                 Debug.Log(string.Format("CallFromJS[{0}]", msg));
+                if (msg.StartsWith("url1:")) {
+                    var url1 = msg.Substring(5);
+                    return;
+                }
                 status.text = msg;
                 status.GetComponent<Animation>().Play();
             },
@@ -46,6 +53,16 @@ public class SampleWebView : MonoBehaviour
             ld: (msg) =>
             {
                 Debug.Log(string.Format("CallOnLoaded[{0}]", msg));
+#if UNITY_ANDROID
+                url0 = msg;
+                url1 = null;
+                t0 = Time.realtimeSinceStartup;
+                webViewObject.EvaluateJS(@"
+                  setTimeout(function() {
+                    Untiy.call('url1:' + location);
+                  }, 1000);
+                ");
+#endif
 #if !UNITY_ANDROID
                 // NOTE: depending on the situation, you might prefer
                 // the 'iframe' approach.
@@ -127,6 +144,17 @@ public class SampleWebView : MonoBehaviour
         yield break;
     }
 
+#if UNITY_ANDROID
+    void Update()
+    {
+        if (url0 != null && (url0 == url1 || Time.realtimeSinceStartup - t0 > 1.0f)) {
+            Debug.Log("stable: " + url0);
+            url0 = url1 = null;
+            t0 = 0.0f;
+        }
+    }
+#endif
+
 #if !UNITY_WEBPLAYER
     void OnGUI()
     {
```

**Comment by lutfianasari** [comment]
I got it. I implemented your example and it works well. 
There are some misspelling, but those can be corrected. 
Thank you very much!!!
