### ISSUE TITLE
Ipad White Screen

### ISSUE THREAD

**Issue by bahadir147** [gree/unity-webview#253]
I have no problem with the browser, but now when I call the site it stays on the white screen.
The problem is only in the iPad.
If you have a suggestion, it might be your cause.

Link; 
https://www.vesselfinder.com/aismap?zoom=7&lat=undefined&lon=undefined&width=100%&height=500&names=false&track=false&fleet=false&fleet_hide_old_positions=false&clicktoact=false&store_pos=false&ra=about%3Ablank&imo=

**Comment by KojiNakamaru** [comment]
The url seems wrong. `width=100%` should be `width=100%25`.

**Comment by bahadir147** [comment]
Thank You for help.
