### ISSUE TITLE
[css]keyframe in css not refreshing the page

### ISSUE THREAD

**Issue by dockmanaman** [gree/unity-webview#269]
hello , while playing with this plugin I realize that keyframes animation in css 
are not loaded  when the page is displayed.

here is a link I  used : 
https://codepen.io/Izumenko/full/MpWyXK/

tested on Mac editor only

**Comment by KojiNakamaru** [comment]
Perhaps the css animation is rendered with a hardware-accelerated view and cannot be captured as youtube isn't played on the editor. This is a limitation of the current implementation. The rendering on Android/iOS should have no issue. Also, though it is not perfect, you may still utilize WebViewSeparated to debug your program:
https://github.com/gree/unity-webview/tree/1d5020dc96e5808118a8862b5a458b80aabb72cf#webviewseparatedbundle

**Comment by dockmanaman** [comment]
thank you, I tested it on mobile and it work very well .
