### ISSUE TITLE
Plugin is not working on xcode 6

### ISSUE THREAD

**Issue by longkeng** [gree/unity-webview#27]
Because xcode 6 using ARC and new API, this plugin occurred a lot of bug! 
WebViewPlugin *webViewPlugin = (WebViewPlugin *)CFBridgingRelease(instance);
[webViewPlugin loadURL:url];
not working and force stopped!

**Comment by splhack** [comment]
You can compile the source code without ARC
https://github.com/gree/unity-webview/issues/25
