### ISSUE TITLE
Local webview - Copying whole folder structure to persistent data

### ISSUE THREAD

**Issue by antoniohof** [gree/unity-webview#270]
Hi!
Im able to load the index.html, but the index cannot find all the others assets that were on the streaming assets folder.
I was not able to find anything on how to copy folders from streaming assets to persistent data.
Is it possible?

Thank you,

**Comment by KojiNakamaru** [comment]
Please check the sample app as an example, which copies index.html and index.jpg in the following part:
https://github.com/gree/unity-webview/blob/1d5020dc96e5808118a8862b5a458b80aabb72cf/sample/Assets/Scripts/SampleWebView.cs#L89-L110

**Comment by antoniohof** [comment]
Thanks.
I realized I have to create the folders structure on the persistent data, and then move each file I want accordingly.
