### ISSUE TITLE
Playing media in web page on Mac OS or Editor

### ISSUE THREAD

**Issue by dcdemars** [gree/unity-webview#290]
Is the plugin supposed to support playing media on a web page? I've been doing this with the iOS plugin with no problem but the Mac OS plugin doesn't seem to play either video or audio media on a web page. I've tried it both in the editor and in a Mac game build. Is this expected or am I doing something wrong?

**Comment by KojiNakamaru** [comment]
Unfortunately the current implementation for osx is limited and cannot support media (such as youtube) playback.
cf. https://github.com/gree/unity-webview/issues/63#issuecomment-174369462
cf. https://github.com/gree/unity-webview/issues/192

**Comment by dcdemars** [comment]
Thanks for your quick reply. I will probably take a look at the code myself and see if anything can be done. After a quick look it is puzzling to me that it doesn't even play audio files; it looks to me like that should work.
