### ISSUE TITLE
Can't send consecutive javascript commands to unity using src method

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#30]
I can't seem to send multiple consecutive javascript commands to unity using the current scheme which is to send it in a url. 

		document.getElementById("Unity").src="unity:foo()";

 Is there a way to use SendMessage from javascript, or another way to use the current implementation to send two consecutive javascript commands and have them both go through to unity?

**Comment by KojiNakamaru** [comment]
Could you please try the latest repository? (https://github.com/gree/unity-webview/tree/39d08af311278693abb8c57129dc1b434b062c25) I've just merged several fixes today and `sample/` and `dist/unity-webview.unitypackage` are updated. The files `sample/Assets/StreamingAssets/sample.html` and `sample/Assets/Scripts/SampleWebView.cs` show how we can define `Unity.call(msg)` to perform a call from JavaScript to Unity.

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
