### ISSUE TITLE
Incorrect result executing multiline js function on Android using "javascript:" approach

### ISSUE THREAD

**Issue by yura415** [gree/unity-webview#302]
I've been using this project lately and noticed that multiline js functions are not always executing right on Android.

Sometimes executing a line like this would result in whole document being replaced with 'example text'.
```js
document.getElementById('debug').innerHTML = 'example text';
```

And sometimes I would see no results with no error messages.

The reason is that code is being executed using 'javascript:' in navigator.
So I've replaced all line breaks with empty strings if on Android platform and this solved the problem.

**Comment by KojiNakamaru** [comment]
Although it isn't reproduced on my device (Android 6.0.1), I've modified the code to solve such an issue in #306 and updated binaries. Could you please try the latest?

**Comment by yura415** [comment]
Thanks. This seems to fix the issue. Tested on 7.1.2.
