### ISSUE TITLE
Ingame screenshot with browser

### ISSUE THREAD

**Issue by metamorphling** [gree/unity-webview#317]
Hello, I have a question about screenshot functionality.
Is it possible to take screenshot in game with WebView being displayed too?
Using ReadPixels() I managed to do this in Mac Unity editor, but for ios/android I get screenshots without WebView.

**Comment by KojiNakamaru** [comment]
For Android/iOS this plugin places native WebView/UIWebView/WKWebView views over the Unity rendering view, so they cannot be captured by ReadPixels(). If you need to capture the whole screen you have to utilize screen capture APIs.

**Comment by metamorphling** [comment]
By screen capture API you mean java/objective-c side? Can it be done on Unity side?

**Comment by KojiNakamaru** [comment]
I mean java/objective-c side. There is no simple way to perform it on unity side, I guess.

**Comment by metamorphling** [comment]
Yeah, I guessed so too but wanted to confirm, Anyway, thanks for your answers!
