### ISSUE TITLE
Black background for android:targetSdkVersion > 14

### ISSUE THREAD

**Issue by HuyThachGit** [gree/unity-webview#33]
In our application, we only show the web view inside a header and footer, but after finished loading website, the footer is cover by a black color cover. Header also is cover by a black cover but only a part as in the attached image.

We discovered that if we set android:targetSdkVersion is less than or equal to 13, this issue does not occur. But API level 13 is too old now.

Please give me any suggestion to fix this problem.
Thank you.

![blackbackground](https://cloud.githubusercontent.com/assets/13446828/8819823/acdeb40a-308a-11e5-9d93-7768d8a1cb3d.png)

**Comment by KojiNakamaru** [comment]
It might be solved the following but I'm not sure. Could you please provide a minimum MonoBehaviour example to reproduce the issue?
```diff
diff --git a/plugins/Android/src/net/gree/unitywebview/WebViewPlugin.java b/plugins/Android/src/net/gree/unitywebview/WebViewPlugin.java
index c9f9cd3..2ea3eb2 100644
--- a/plugins/Android/src/net/gree/unitywebview/WebViewPlugin.java
+++ b/plugins/Android/src/net/gree/unitywebview/WebViewPlugin.java
@@ -76,6 +76,7 @@ public class WebViewPlugin
 			mWebView.setVisibility(View.GONE);
 			mWebView.setFocusable(true);
 			mWebView.setFocusableInTouchMode(true);
+			mWebView.setBackgroundColor(0x00000000);
 
 			if (layout == null) {
 				layout = new FrameLayout(a);
```

**Comment by KojiNakamaru** [comment]
The latest version call `setBackgroundColor(0x00000000)` if `transparent` is set to `true`. Please reopen the issue if you need any assistance further.
