### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by Ghoulversi** [gree/unity-webview#331]
Can I set a background image? If yes, how can I?

**Comment by KojiNakamaru** [comment]
For example, you can set a background image as below:
```diff
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 0962587..19c76f8 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -3,6 +3,12 @@
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <title>Unity WebView</title>
     <script src="sample.js"></script>
+    <style>
+      body {
+          background-size: cover;
+          background-image: url("sample.jpg");
+      }
+    </style>
   </head>
   <body>
     <h1>Hello Unity WebView!</h1>
```

![image](https://user-images.githubusercontent.com/2645978/42944874-c7e35bfa-8ba1-11e8-939b-7435cb2f7e60.png)

**Comment by Ghoulversi** [comment]
It makes from html part, I need from webView. I tried to put two web views but than it blocks my buttons so unity call doesn't works. Can I somehow make it works? if one web view is background and second is main web view?

**Comment by KojiNakamaru** [comment]
For such a case, we often make a webview transparent (by specifying `transparent:true` for `webViewObject.Init()`) and show a background by uGUI. Many apps we made show a dialog frame by uGUI and display a webview over it.

**Comment by Ghoulversi** [comment]
Thanks a lot, it was a such easy answer.
