### ISSUE TITLE
Restart WebView

### ISSUE THREAD

**Issue by Ghoulversi** [gree/unity-webview#339]
Hello again, and sorry for so many questions. How can I destroy it and call again? Or to quit it and call again? More exactly when I go back to previous scene to close webView and when I open again web view scene to open WebView.

**Comment by KojiNakamaru** [comment]
https://github.com/gree/unity-webview/issues/328#issuecomment-409487187 might be useful to understand create/destroy a webview.

**Comment by Ghoulversi** [comment]
It worked, thanks.
