### ISSUE TITLE
Is there anyway to know loading URL failed?

### ISSUE THREAD

**Issue by HuyThachGit** [gree/unity-webview#34]
When we load an URL failed, it shows nothing in iOS and a "Webpage not available" in Android.
Is there anyway to know loading URL failed in programming?

**Comment by KojiNakamaru** [comment]
Currently there is no function directly informs failures. For now, by always preparing `window.Unity.call`,
```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 46a30c6..0b28b17 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -69,7 +69,6 @@ public class SampleWebView : MonoBehaviour
 			}
 			if (Application.platform != RuntimePlatform.Android) {
 				webViewObject.EvaluateJS(
-					"window.addEventListener('load', function() {" +
 					"	window.Unity = {" +
 					"		call:function(msg) {" +
 					"			var iframe = document.createElement('IFRAME');" +
@@ -78,8 +77,7 @@ public class SampleWebView : MonoBehaviour
 					"			iframe.parentNode.removeChild(iframe);" +
 					"			iframe = null;" +
 					"		}" +
-					"	}" +
-					"}, false);");
+					"	}");
 			}
 			break;
 #else
```
we can check whether the current `location.href` is correct.
```c#
webViewObject.EvaluateJS("Unity.call(location.href);");
```

The "Webpage not available" display on Android is however ugly and should normally be avoided, so I'll investigate further for better solutions.

**Comment by KojiNakamaru** [comment]
I've added a new callback for load failures: https://github.com/gree/unity-webview/pull/75 . Please check `sample/Assets/Scripts/SampleWebView.cs` about how to set the callback. If you need any assistance further, please reopen the issue.

**Comment by KojiNakamaru** [comment]
Sorry, https://github.com/gree/unity-webview/pull/75 accidentally dropped Unity.call() on Android. I've fixed the issue in https://github.com/gree/unity-webview/pull/80.
