### ISSUE TITLE
Unity Editor on OSX running with other platforms selected

### ISSUE THREAD

**Issue by chrisfairc** [gree/unity-webview#343]
Hi @KojiNakamaru , unity web view works great for me, (thanks!) I tested it on device on iOS and Android, and it works in the editor too, however only when I have standalone build selected.

If I have iOS or Android build platform selected in editor, then the sample scene provided in this repo doesn't show the page, I got this error :

Assertion failed: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range

I tried modifying some of your compile switches to no avail. I think it's an opengl version issue.
Could you suggest a setting I can use to get around this issue by any chance ? 

This is using the sample project you provide in the repo with the plugin imported. I tested this and got the same result on Unity 2017.1, 2018.1, and 2018.2

**Comment by KojiNakamaru** [comment]
I tried to reproduce the issue and failed. The following is an example of the Editor running with the iOS platform selected. I'm running Unity 2018.2.2f1 on macOS High Sierra (10.13.6).

![image](https://user-images.githubusercontent.com/2645978/44442312-5c1ca680-a60c-11e8-9186-ee75f21222ac.png)

As the latest WebViewObject.cs contains `#if UNITY_EDITOR_OSX` before `UNITY_IOS` and/or `UNITY_ANDROID` so it should work even if the platform is set for mobile. Could you please provide more detailed steps to reproduce the issue?

**Comment by chrisfairc** [comment]
Hmm. Ok I will try again and give you more info. I am on HighSierra 10.13.2. I have OpenGL 4.1 showing in my Unity top bar like in your screenshot... thanks for the quick reply, I will get back to you.

**Comment by Verlangieri** [comment]
Hi ! It works fine with iOS plateform, but I got the same error when I tried to play the sample project with Android build plateform selected.

I'm running on :
- Unity 2018.2.16f1
- macOS High Sierra (10.13.6)
- OpenGL 4.1

<img width="1272" alt="" src="https://user-images.githubusercontent.com/16365136/49385346-8575c400-f71d-11e8-8a1f-237a3d669f02.png">

**Comment by KojiNakamaru** [comment]
Thank you for your report, I found the cause. If you select a mobile platform, the maximum texture dimension is limited to 2048x2048 and/or 4096x4096 by Unity's emulation, and in this case we cannot allocate a texture for a high-resolution screen so that it causes the error you experienced. Could you please try to limit your screen resolution to, for example, 1136x640?

**Comment by chrisfairc** [comment]
Awesome. Thank you @KojiNakamaru! 
I verified this fixes the issue. All I need to do is make the size of the unity play view a bit smaller and the error stops happening. Don't even need to restart unity or the app. I guess you mightn't see this on a macbook but I am using an imac so I see it consistently. Closing this issue now.
