### ISSUE TITLE
NSURLErrorDomain Code=-1100 

### ISSUE THREAD

**Issue by howo** [gree/unity-webview#350]
ios and pc platform use unity.call is normal but
android platform is will return this

CallOnError[Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." 
UserInfo={
NSUnderlyingError=0x158d0ee60 {Error Domain=kCFErrorDomainCFNetwork Code=-1100 "The requested URL was not found on this server." 
UserInfo={
NSErrorFailingURLStringKey=file:///Users/Apple/Library/Application%20Support/Sample%20Inc_/sample/form?msg=hoge,
NSLocalizedDescription=The requested URL was not found on this server., NSErrorFailingURLKey=file:///Users/Apple/Library/Application%20Support/Sample%20Inc_/sample/form?msg=hoge}
}, NSErrorFailingURLStringKey=file:///Users/Apple/Library/Application%20Support/Sample%20Inc_/sample/form?msg=hoge, NSErrorFailingURLKey=file:///Users/Apple/Library/Application%20Support/Sample%20Inc_/sample/form?msg=hoge, NSLocalizedDescription=The requested URL was not found on this server.
}

<img width="1427" alt="123" src="https://user-images.githubusercontent.com/13917716/44942881-23d84d80-adee-11e8-878b-96b9092da927.png">

unity 2017.4.10
how solution this ?
thanks

**Comment by KojiNakamaru** [comment]
Thanks, I've fixed SampleWebView.cs to work even if the platform is set to Android in #352. Could you please try the latest.

**Comment by howo** [comment]
it working thanks
