### ISSUE TITLE
WebView.mm issue from another project but same Author... Possible Assistance?

### ISSUE THREAD

**Issue by samavan** [gree/unity-webview#351]
It seems the WebView.mm file has been used into another project for Google login use : 
https://github.com/midworld/unity-googledrive/blob/master/Assets/Plugins/iOS/WebView.mm

Author the is a same the WebView.mm from your project.
Midworld plugins works great but it seems the current WebView.mm file is a bit oldish and doesn't build anymore into Xcode.

Anyone would know how to fix those issue?
- https://github.com/midworld/unity-googledrive/issues/41
That would help a lot!

Thank you :)....

**Comment by KojiNakamaru** [comment]
The issue described here seems to be fixed in https://github.com/midworld/unity-googledrive/issues/41 so I'll close this issue.
