### ISSUE TITLE
Camera access for WebView in Android?

### ISSUE THREAD

**Issue by adickenscheidt** [gree/unity-webview#359]
I'm trying to get the camera access to work in Android. I'm loading my app into the WebView from the persisted files (which all works), but when I want to use camera access, I don't get the prompt and can't do anything. It just shows a pixelated play button symbol. I added the neccesary permissions to the manifest.xml. 

If you want to test it, you can use this site as an example: https://davidwalsh.name/demo/camera.php

Am I missing something?

Thanks in advance!

**Comment by KojiNakamaru** [comment]
The plugin on the master branch won't grant the camera access when it is requested. I've put an experimental implementation to allow it in #360, so could you please give a try?

**Comment by adickenscheidt** [comment]
Hi @KojiNakamaru 

Thank you very much, your solution worked perfectly!

**Comment by KojiNakamaru** [comment]
:-)
