### ISSUE TITLE
How to give Camera access to the webview in android app developed by Unity using unity-webview?

### ISSUE THREAD

**Issue by bhasinnitish** [gree/unity-webview#36]
HI,

I am trying to open one website in the webview developed using unity-webview which requires camera permission to proceed. Unfortunately, I am unable to do so. Can you please help here with a way to give access to mobile camera?

Regards

**Comment by KojiNakamaru** [comment]
Although I haven't tried, adding some permissions in AndroidManifest.xml could solve the issue.
cf. https://developer.appcelerator.com/question/174485/webview-not-allowing-for-file-access-using-camera

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
