### ISSUE TITLE
webView.Load(HTML) Usage

### ISSUE THREAD

**Issue by deltamish** [gree/unity-webview#365]
Hey,

How can I load html if its being stored as a string and can be changed dynamically prior to displaying 

I tried the following 
`  if (useHtml)
        {
            webViewObject.LoadHTML(HTMLvalue, "");
            Debug.Log("HTML Value" + HTMLvalue); }`

But the Screen remains as Blank page and instead  the HTML code itself is being printed 

The html is encoded as
`string HTMLvalue= @"<.!DOCTYPE html>
<.html>
<.body style=""background-color:powderblue;"">
<.h1>This is a heading</.h1>
<.p>This is a paragraph.</.p>
</body>
</html>"; `

**Note** : dot **(.)** intentionally added in html code displayed above to prevent git from reading it as a html 

thanks

**Comment by KojiNakamaru** [comment]
Thank you for the report. I've confirmed the issue on iOS and fixed it: https://github.com/gree/unity-webview/pull/366, and updated binaries. Could you please try the latest.

**Comment by deltamish** [comment]
Hi I tried the updated package. But facing same problem 
![screenshot_1541685640](https://user-images.githubusercontent.com/9283808/48203491-a7ce2900-e38d-11e8-8832-a8f594e700d3.png)


Here is the code I am using 
`**string HTMLTEST = @"< !DOCTYPE html >**
 

 < html >
 

 < head >
 
     < style > #container {
            width: 100vw;
    height: 100px;
    position: relative;
    }
    input[type = ""button""], input[type = ""submit""] { 
              visibility: hidden;
            }
hashtag navi,
hashtag infoi {
width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
          }
          #infoi {
            z-index: 10;
          }

          .WideViewPort
          {
              width: 100vw;
              width: 100%;
          }
          
          .square{
        width: 100px;
        height: 100px;
        Background-color: #fff;/* Your Color */
       
    }
    
    </style>
    <link rel = ""stylesheet"" href=""http://unicorn-ui.com/buttons/css/buttons.css"">
    
</head>
<body>


<div id = ""container"" >
        < div  class=""WideViewPort"">
                <form method = ""POST"" visibility=""hidden"">
                       
                        <script
                            src = ""https://checkout.razorpay.com/v1/checkout.js""
                            data-key=""rzp_test_OmccP2VN9cmpoi""
                            data-amount=""1005""
                            data-name=""Titlez""
                            data-description=""Purchase Description""
                            data-order-id=""<gghg767>""
                            data-image=""https://razorpay.com/favicon.png""
                            data-prefill.name=""Harshil Mathur""
                            data-prefill.email=""support@razorpay.com""
                            data-prefill.contact=""8888888888""
                            data-theme.color=""#0080ff""
                        ></script>
                        <input type = ""Hidden""  value=""Hidden Element"" name=""hidden""> 
                        <div  >
                              
                                <button id = ""rzp-button1"" class=""button button-block button-rounded button-caution button-large"" style=""width:200px;""> Pay and checkout</button>
                                </div>
                        </form>
        </div>
     
      </div>
</body>
</html> ";
 webView.useHtml = true;
        webView.HTMLvalue = (HTMLTEST);
        StartCoroutine(webView.Load());


SampleWebView webView;
`

**The slightly modified SampleWebView**
Inside the Load() Function
`
bool useHtml;
  if (useHtml)
        {
            webViewObject.LoadHTML(HTMLvalue, "");
            Debug.Log("HTML Value" + HTMLvalue);
        }else
        if (Url.StartsWith("http")) {
            webViewObject.LoadURL(Url.Replace(" ", "%20"));
        } else {`


The html file for your refernce


[theHTMLFIle.zip](https://github.com/gree/unity-webview/files/2562092/theHTMLFIle.zip)

**Comment by KojiNakamaru** [comment]
At least with the following modification for the sample app,

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 1d169a1..24354ee 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -102,6 +102,17 @@ public class SampleWebView : MonoBehaviour
         webViewObject.SetMargins(5, 100, 5, Screen.height / 4);
         webViewObject.SetVisibility(true);
 
+        webViewObject.LoadHTML(@"
+<!DOCTYPE html>
+<html>
+<body style=""background-color:powderblue;"">
+<h1>This is a heading</h1>
+<p>This is a paragraph.</p>
+</html>
+",
+            "");
+        yield break;
+
 #if !UNITY_WEBPLAYER
         if (Url.StartsWith("http")) {
             webViewObject.LoadURL(Url.Replace(" ", "%20"));
```

I got the following correct result.

![image](https://user-images.githubusercontent.com/2645978/48206662-42d8fa00-e3b2-11e8-9ae7-7ee4c06dd961.png)

My environment is:
* Unity 2018.2.6f1
* iPhone SE (iOS 12.1)

Also, for describing your code here, please check https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code .

**Comment by deltamish** [comment]
Hey,

Thanks for the suggest. I reformated the code. 

Can you try the HTML value I have described above and see if you are facing similar issue. 

Environment I am using is 
Unity 2017.4 
Android Oreo

**Comment by KojiNakamaru** [comment]
Your html contains wrong tags such as "< !DOCTYPE html >" (redundant space characters around '<' and/or '>'). It is shown incorrectly on PC browser, too.

**Comment by deltamish** [comment]
I feel so stupid now. 
Thanks
