### ISSUE TITLE
BCE0044: unexpected char: '$'. 

### ISSUE THREAD

**Issue by chamx2** [gree/unity-webview#367]
My goal is to make the code organize for it has several features. 

I get this error everytime I try to put everything into a separate or new folder. 

Is there a work around here? 

Thanks.

**Comment by KojiNakamaru** [comment]
You may have a JS file somewhere outside StreamingAssets. Unity then try to parse the JS file as its script, not just an asset.

**Comment by chamx2** [comment]
Thank you!
