### ISSUE TITLE
Is it possible not to use SampleWebView.cs

### ISSUE THREAD

**Issue by chamx2** [gree/unity-webview#368]
I want to create a plane or a gameobject in the scene and put webObjectView right away in the scene. Will be this possbiel in unity 2017.2.0.f3? 

Then some Buttons for back, forward, refresh and close(probably this one I'll just turn the gameobject off)

**Comment by KojiNakamaru** [comment]
You cannot render a webview as a texture for iOS/Android. This plugin only allows to overlay a webview on Unity's rendering. On this condition, if you want to align a webview to a plane placed in the world, you can utilize `Camera.WorldToScreenPoint()` for example.

Buttons for "back" and "forward" can be implemented as in SampleWebView.cs. There is no direct function for "refresh", but it can be implemented as `webViewObject.EvaluateJS("location.reload(true)")`. Turning off or destroying the gameobject is okay for "close".

**Comment by chamx2** [comment]
Thanks again!
