### ISSUE TITLE
How to set Webview to render behind Unity UI?

### ISSUE THREAD

**Issue by kaninhot004** [gree/unity-webview#372]
Is it possible to render behind Unity UI?

Another question is how to set Webview rect to same size in each devices. ( Not full screen )

This is code for set Webview size but it's show different size on each devices.
```  webViewObject.SetMargins(0, 275, 0, 100 + int.Parse(getButtonColorController.GetComponent<RectTransform>().sizeDelta.y.ToString()));```

Thank you very much!

![01](https://user-images.githubusercontent.com/9493525/47780868-e67d3700-dd2e-11e8-92f0-da81e502307a.JPG)
![02](https://user-images.githubusercontent.com/9493525/47780870-e67d3700-dd2e-11e8-97ec-efc784a89ca6.JPG)

**Comment by KojiNakamaru** [comment]
> Is it possible to render behind Unity UI?

No. This plugin allows only to overlay system-native webviews over unity's rendering view.

> Another question is how to set Webview rect to same size in each devices. ( Not full screen )

You need to compute adequate margins based on `Screen.with` and `Screen.height`. Then, at least in pixel unit, you can perfectly control webviews' sizes. Please note this might not be sufficient for your requirement, as dpi/fonts differ by devices and a html may/may not specify `<meta viewport=...>`.

**Comment by kaninhot004** [comment]
Thank you Mr.Koji Nakamaru. I will try to debug height and set the size again.

**Comment by kaninhot004** [comment]
Hello again, Is iOS 9.3.5 compatible with?
Sorry for disturb you.

**Comment by KojiNakamaru** [comment]
Yes, the plugin should work. WKWebView of iOS9 however has several issues, so you might want to  utilize UIWebView. In such a case, please set `enableWKWebView` to `false`.

https://github.com/gree/unity-webview/blob/136f953f1612c4def98d760cc987efbbc2a50f12/sample/Assets/Scripts/SampleWebView.cs#L98

**Comment by kaninhot004** [comment]
I really appreciate it.

Do you have any donate info?, I want to donate my little money to you.

**Comment by KojiNakamaru** [comment]
Thank you, but I won't receive any donation as this project is supported by my company. It is appreciated if you report any bug you find and/or send this project a pull request:-).
