### ISSUE TITLE
Is it possible to open webview hidden, i.e. not visible in screen?

### ISSUE THREAD

**Issue by perza** [gree/unity-webview#373]
I need to connect to a web site to run a short javascript "behind the scenes", literally :)

br, perza

**Comment by KojiNakamaru** [comment]
It is possible by setting margins adequately. For example, the following makes a webview with height zero.

```csharp
        webViewObject.SetMargins(0, 0, 0, Screen.height);
        webViewObject.SetVisibility(true);
```

**Comment by perza** [comment]
Thanks a lot, that's great news!
