### ISSUE TITLE
How to call Unity C# from javascript running in the WebView?

### ISSUE THREAD

**Issue by perza** [gree/unity-webview#376]
Maybe the question is a bit out of the scope here, but this would be a really precious piece of information.

**Comment by perza** [comment]
Brilliant, so stupefyingly simple when you pointed it out :) Thanks a lot!

**Comment by deltamish** [comment]
Hi,

i'm a little confused as how this works. Can you kindly explain how it can be used to call a function defined in a script attached to same object as webview.

PS. i tried using the above js but the function in my class didn't get called.Should it be a static function ?

thanks
