### ISSUE TITLE
Google Playにおけるリジェクトについて

### ISSUE THREAD

**Issue by Sakura777** [gree/unity-webview#377]
素晴らしいプラグインをありがとうございます。

こちらのWebViewを利用してアプリを開発し、GooglePlayに投稿したところ、
公開後のポリシーチェックにおいて
「YouTube 動画のバックグラウンド再生が有効になっている」という理由から
下記ポリシーに違反しているとリジェクトとなりました。

端末やネットワークの不正使用に関するポリシー
https://play.google.com/about/privacy-security-deception/device-network-abuse/

Unity側でバックグラウンド再生を可能にする設定は一切していない為、
WebViewが原因かと思われるのですが、お心当たりはありますでしょうか。
バックグラウンド再生機能は不要なので、オフにする方法がありましたら教えて頂けますと幸いです。

ビルド環境
Unity 2018.2.3f1 / Mac Mojave 10.14
Android SDK Tools 25.2.3 / Platform-tools 28 / Bulid-tools 28.01

**Comment by KojiNakamaru** [comment]
ご報告ありがとうございます。これまでの経験では問題になったことはなく、OSのバージョンなどにも依存する問題のようですが、 Google Playのレビューでなんらか問題検知の仕組みに更新があったのかもしれません。 #378 でWebViewのポーズ/レジュームを明示的に行うように対応をいれて、バイナリも更新しましたので、最新版をお試しいただけますでしょうか？

**Comment by Sakura777** [comment]
返信が遅れて申し訳ありません。
バージョンアップしたバイナリを再インポートして提出したところ、無事にリリースされました。
（私もこれまでは問題無く通っていたので最近検知が強化されたのかなと思います）
ご対応ありがとうございました。
