### ISSUE TITLE
mac app store validation pre 10.8

### ISSUE THREAD

**Issue by McKuzmich** [gree/unity-webview#4]
Webview doesn't work on signed app with mac app store validation enabled on OS prior 10.8. Just blank view.
Both 10.6 and 10.7 affected.
Without store validation everything is ok.

**Comment by KojiNakamaru** [comment]
Though I haven't investigate the issue itself, unity-webview implementation for Editor is provided mainly for development. Its implementation is a bit tricky and sometimes don't work well compared with Android/iOS ones. Perhaps uWebKit provides a more solid implementation for OSX. Please reopen the issue if you need any assistance further.
