### ISSUE TITLE
Application Crashes "signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)" in GooglyPlay Console

### ISSUE THREAD

**Issue by cosmicmosmic** [gree/unity-webview#401]
Hello.

I added your webview plugin in our game.
and got new many crashes reported

signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)

backtrace:
 #00  pc 0000000000f73a88  /data/app/com.android.chrome-F4ci0oyduqwVE4OQOPnP9A==/base.apk
 #01  pc 00000000010261c3  /data/app/com.android.chrome-F4ci0oyduqwVE4OQOPnP9A==/base.apk

i don't have idea about this.

any help about this crashes?

**Comment by KojiNakamaru** [comment]
I guess somehow WebView crashed by displayed contents.
cf. https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/I6giN0VbVa0%5B1-25%5D
cf. https://stackoverflow.com/questions/50945853/how-to-fix-anr-issue-on-data-app-com-android-chrome-1-base-apk
