### ISSUE TITLE
Android Build Error: Manifest Reference Null

### ISSUE THREAD

**Issue by kdzapp** [gree/unity-webview#413]
`NullReferenceException: Object reference not set to an instance of an object
AndroidManifest.SetHardwareAccelerated (System.Boolean enabled) (at Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs:181)
UnityWebViewPostprocessBuild.OnPostGenerateGradleAndroidProject (System.String basePath) (at Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs:24)
UnityEditor.Android.AndroidBuildPipelineInterfaces.OnGeneratePlatformProjectPostprocess (System.String path, System.Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Android/AndroidPostGenerateGradleProject.cs:45)
UnityEditor.Android.PostProcessor.Tasks.ExportProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <df7ba4d130594d168eec372b930522d4>:0)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()
`

There's the trace, not quite sure why it's happening?

**Comment by KojiNakamaru** [comment]
Is this an output for the sample app? Which version of unity do you use?

**Comment by kdzapp** [comment]
Hey Koji, I'm actually not using this anymore due to it not working with the Oculus Go - I was using unity 2018.3.11f. In order to test it I commented out the hardware acceleration method, but I was still unable to get that method to work without a build error.

**Comment by KojiNakamaru** [comment]
If you don't need to adjust AndroidManifest.xml, you can simply remove UnityWebViewPostprocessBuild.cs.

**Comment by kdzapp** [comment]
Thanks - that's what I did!
