### ISSUE TITLE
cannot interact with the android webview

### ISSUE THREAD

**Issue by Vecol** [gree/unity-webview#418]
Hey there, we are using a website login sdk provide by our publish company, and I can get this work on a sample project.But when merging into our own game, the website is not interactable, you can't scroll the page, type into the textbox or click the button.Checked the AndroidManifest.xml, seems nothing special added.
``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="packagename" android:installLocation="internalOnly">
    <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true"  />
    <application android:icon="@drawable/app_icon" android:label="@string/app_name"   android:banner="@drawable/app_banner" android:focusable="true"
        android:focusableInTouchMode="true">
        <activity
            android:theme="@style/UnityThemeSelector"
            android:name="packagename.MainActivity"
            android:label="@string/app_name"
            android:screenOrientation="sensorLandscape"
            android:launchMode="singleTask"
            android:hardwareAccelerated="true"
            android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
            <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />
        </activity>
```
After some searching , some said it's the focus issue, so I added `android:focusable="true"  android:focusableInTouchMode="true"`, which didn't work. And tested on Android7&8 devices, both are not work. Any suggestion would be a great help.Thank you.

**Comment by KojiNakamaru** [comment]
Perhaps your activity is derived from UnityPlayerNativeActivity, as there is the following meta:

```xml
            <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
```

Your issue may be solved by replacing this with:

```xml
            <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
```

or by modifing your activity to be derived from UnityPlayerActivity. UnityPlayerNativeActivity causes troubles while there is not any major performance gain so it is depricated since Unity 5.4.0.

**Comment by Vecol** [comment]
Great! Changing the xml setting make it work. We are developing under Unity 5.3.8f1, some guy wrapped Unity activity into a jar lib to do some hot-fix working, so I'll leave it alone.Thank you for your help.Have a nice day.
