### ISSUE TITLE
"CALayerInvalidGeometry: CALayer bounds contains NaN" on IOS

### ISSUE THREAD

**Issue by Vecol** [gree/unity-webview#420]
https://github.com/gree/unity-webview/blob/4bcc76e5c43541c9608f48af40d0b9d7300af4b9/plugins/iOS/WebView.mm#L462 Debug into this line showed the divided number is 0.
Environment:
Unity 5.3.8
Xcode 10.2.1
macOS Mojave
Ipad Air2 iOS12.0

**Comment by KojiNakamaru** [comment]
I cannot prepare the same environment, but at least in the following environment, the sample app runs without the issue you described. Could you please provide a minimum iOS project that reproduce the issue, then I'll investigate it.

* Unity 5.6.6f2
* Xcodd 10.2.1
* iPhone SE (iOS 12.2)

**Comment by Vecol** [comment]
Sorry for short report written in a hurry. Rechecked the code,  the view get by this https://github.com/gree/unity-webview/blob/4bcc76e5c43541c9608f48af40d0b9d7300af4b9/plugins/iOS/WebView.mm#L459
is nil. So I move the `setMargins` call from `Awake` to `Start`, and it works alright.
