### ISSUE TITLE
Application termination

### ISSUE THREAD

**Issue by dee0152** [gree/unity-webview#425]
Is It work on Android 4.1?

The application is terminated.

Are there any options available in API 16?

And what is an empty WebView?

needs help.plz

**Comment by KojiNakamaru** [comment]
I'm sorry for the late reply. I've fixed the issue and updated binaries. Could you please try the latest.

**Comment by dee0152** [comment]
thank you.
I applied it using the latest binary file.
Troubleshoot application shutdown on Android 4.1
However, there was an error fetching the https: // URL.
-------------------------------------------------- -------------------------------------------------- ------
"The page is not available.
The web page at https://m.curveskorea.co.kr/ may be temporary.
Or you can permanently move to a new web address.
suggestion :
- Make sure you have a data connection.
- Please refresh this web page later.
- Check the address you entered. "
-------------------------------------------------- -------------------------------------------------- ----
Loading the URL as http will load normally.
You can load other sites using https.
Why can not my site load https?

You are using the following permissions:
"android: name =" android.permission.INTERNET "
