### ISSUE TITLE
Is it should be how to get the call back from the Web in Unity side? (Android)

### ISSUE THREAD

**Issue by st0326s** [gree/unity-webview#43]
The following page to reference it was implemented callback processing of WebView.
http://loumo.jp/wp/archive/20131115085810/

Where you saw the **WebViewPlugin.java**, it has the following description

```
	@JavascriptInterface
	public void call(String message)
	{
		UnityPlayer.UnitySendMessage(mGameObject, "
CallFromJS", message);
	}
```

To 
```
public void CallFromJS (string message) 
```
within **WebViewObject.cs**
I wrote Debug.Log, but the log did not appear.

The following is the source code of Unity side

```
*************** Unity Side Source Code ***************
using UnityEngine;
public class WebviewSample : MonoBehaviour
{
	private string url = "http://www.google.com/";
	WebViewObject webViewObject;
	void Start() {
		webViewObject =
			(new GameObject("WebViewObject")).AddComponent<WebViewObject>();
		webViewObject.Init((msg)=>{
			Debug.Log("***** clicked *****=" + msg);
			if (msg == "clicked") {
				Debug.Log("***** clicked ok *****");
				webViewObject.SetVisibility(false);
			}
		});
		webViewObject.LoadURL(url);
		webViewObject.SetMargins(50,100,50,50);
		webViewObject.SetVisibility(true);
		webViewObject.EvaluateJS(
			"window.addEventListener('load', function() {" +
			"   window.addEventListener('click', function() {" +
			"       Unity.call('clicked');" +
			"   }, false);" +
			"}, false);");
	}
	void OnGUI() {
		Rect textArea = new Rect(100, 0, 400, 100);
		url = GUI.TextArea(textArea, url);
		if (GUI.Button ( new Rect(500,0,100,100), "GO")) {
			webViewObject.LoadURL(url);
			webViewObject.SetVisibility(true);
		}
	}
}
```

**Comment by st0326s** [comment]
I'm sorry, I had forgotten to fill in the environment


Unity5.1.0f3
Nexus7（year2012）
Android 4.1.2

**Comment by KojiNakamaru** [comment]
Could you please try the latest repository? (https://github.com/gree/unity-webview/tree/39d08af311278693abb8c57129dc1b434b062c25) I've just merged several fixes today and the new `sample/` and `dist/unity-webview.unitypackage` runs also on Android. The file `sample/Assets/StreamingAssets/sample.html` shows how we perform a call from JavaScript to Unity. I've tested it for Unity 5.1.3p1 and Nexus7 (2013)/Android 5.1.1.

**Comment by st0326s** [comment]
Thank you.
We were able to confirm the Debug.Log that was output by Android.

After, when you run the UnitySendMessage from actual of iOS,
Since GameObject name is like not been set correctly
It I will ask in a different issue.
