### ISSUE TITLE
does it support rendering a webgl canvas?

### ISSUE THREAD

**Issue by antoniohof** [gree/unity-webview#434]
Hi, I would like to know if unity-webview supports rendering a wegl canvas, specifically a javascript 3d library such as three js.

Thank you,

**Comment by KojiNakamaru** [comment]
WebGL should work well for Android/iOS as the plugin just overlays native UIWebView/WKWebView/WebView onto Unity's rendering view. WebGL won't work well for OSX as in this case the plugin renders WebView in off-screen.

**Comment by antoniohof** [comment]
Thanks!
