### ISSUE TITLE
Is it possible to access the microphone?

### ISSUE THREAD

**Issue by antoniohof** [gree/unity-webview#435]
I would like to know if its possible to access the microphone in Ios and android.

Thanks

**Comment by KojiNakamaru** [comment]
It can't. The android version could support it if we extend the implementation, but there is no way for the iOS version.

cf. https://stackoverflow.com/questions/40236925/allowing-microphone-accesspermission-in-webview-android-studio-java/47410311#47410311
cf. https://stackoverflow.com/questions/30267621/using-microphone-api-inside-a-uiwebview-in-pure-js/51271568#51271568

**Comment by antoniohof** [comment]
ok, thank you
