### ISSUE TITLE
wkwebview linker command failed with exit code 1

### ISSUE THREAD

**Issue by whimsica** [gree/unity-webview#438]
Hi. I'm getting a wkwebview error on ios build. I have enableWKWebView=false everywhere in the setup.  I'm using xcode 10.1, unity 2019.1.  Target is ios 11.  I checked ios on the bundle settings. I'm not sure which version of webview I'm using and not sure how to check that.  I was using the branch that had the monopinvoke callback feature.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_WKWebsiteDataStore", referenced from:
      objc-class-ref in WebView.o
  "_OBJC_CLASS_$_WKUserContentController", referenced from:
      objc-class-ref in WebView.o
  "_OBJC_CLASS_$_WKWebViewConfiguration", referenced from:
      objc-class-ref in WebView.o
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in WebView.o
      l_OBJC_$_CATEGORY_WKWebView_$_WebViewProtocolConformed in WebView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KojiNakamaru** [comment]
Please check whether WebKit.framework is registered in Link Binary With Libraries.
![image](https://user-images.githubusercontent.com/2645978/60476139-5fb19d00-9cb5-11e9-9297-bdba6277055d.png)
It should be automatically registered by Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs but it is occasionally failed to be added. You can add it manually and then the project should be built without errors.

**Comment by whimsica** [comment]
That worked thanks!
