### ISSUE TITLE
On android, Not showing webview after back button to exit the app

### ISSUE THREAD

**Issue by ksay2k** [gree/unity-webview#444]
Hi, I uploaded my entire webview_call code below. I did not change other files.

On Android:
At the beginning of my app, Init_WebviewStart() is called and try to show the Webview by ShowWebView(string _url).

If I press the back button to exit my app, then run this app again, the Webview does not show anymore. 
(But the webview is working if I forced app quit by pressing the left button at the bottom of the android phone.)

How can I resolve this?
By the way, this plugin is very good to use for mobile application. Thank you very much :)

//////////////////////////////////////////////////

https://gist.github.com/ksay2k/7d5c32d2400f3f5412bb0e1655027fc6

**Comment by KojiNakamaru** [comment]
Please provide an archive of the project (based on the sample app) that reproduces the issue or provide a diff for the sample app. Please also check https://guides.github.com/features/mastering-markdown/
when pasting your code.

**Comment by ksay2k** [comment]
> Please provide an archive of the project (based on the sample app) that reproduces the issue or provide a diff for the sample app. Please also check https://guides.github.com/features/mastering-markdown/
> when pasting your code.

**Comment by ksay2k** [comment]
> Please provide an archive of the project (based on the sample app) that reproduces the issue or provide a diff for the sample app. Please also check https://guides.github.com/features/mastering-markdown/
> when pasting your code.

Hi, I upload my entire webview code. Please help this issue. I don`t know how to fix it.

**Comment by KojiNakamaru** [comment]
I've just recently fixed the issue in #447 . Could you please try the latest binaries.
