### ISSUE TITLE
Androidの特定端末において入力フォームに入れた文字が変換できない

### ISSUE THREAD

**Issue by k-n-gk** [gree/unity-webview#458]
素晴らしいプラグインをありがとうございます。

一点、こちらで確認した挙動があるのですが、Androidの特定端末にてwebview内に配置した入力フォームに文字を入力した際、以下挙動となり文字変換がうまく機能しませんでした。

SO-04H,Android 8.0.0:
文字を入力した後、変換する間もなく勝手に確定されてしまい、なぜか同じ文字が2文字目に入る。キーボード内の予測変換の表示は残っており、選択すると3文字目以降に予測変換の文字が入る。例）「あ」と打つと、すぐに「ああ」となり、予測変換で秋を選択すると「ああ秋」となる。

Zenfone5, Android 9
入力の際、予測変換などが出ずひらがなでのみ入力されてしまう

おそらくIMEがうまく働いていないような挙動に見受けられますが、具体的にどういった対応をすれば良いのかを教えていただけますと幸いです。

**Comment by KojiNakamaru** [comment]
問題はサンプルアプリ https://github.com/gree/unity-webview/tree/bcc8c13d1a420db096a630a525940ea81ee542ee/sample でも起きるでしょうか？サンプルアプリについて、Nexus 7 (2013、Android 6.0.1、Google日本語入力)では、問題はおきませんでした。
症状からすると、JavaScriptなどで入力に応じた処理をなにか行っていて、そのためにフォーカスが外れてしまう瞬間があるのではないかと思います。他には使われている日本語入力の問題がありうるかもしれません。

**Comment by k-n-gk** [comment]
ご確認ならびにアドバイスありがとうございます。

サンプルアプリにて当方のwebページを表示させた際に問題が発生しないことを確認いたしましたので当方のunityでの実装に問題がある形のようでした。お手数をおかけいたしました。

JavaScriptなどで入力に応じた処理を行っていないか再度確認してみます。

**Comment by k-n-gk** [comment]
お世話になっております。
当方の実装の不備が発見出来、修正が出来ましたのでご報告させていただきます。

ご対応、誠にありがとうございました。

**Comment by KojiNakamaru** [comment]
良かったです！
