### ISSUE TITLE
I have problem about android 9.0 (Pie)

### ISSUE THREAD

**Issue by yodsaphon** [gree/unity-webview#465]
I found that It should be config traffic permit. Please add config for android 9.0. Thanks
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by KojiNakamaru** [comment]
Yes, but this is an application-specific configuration and should be added by each developer if required.

**Comment by yodsaphon** [comment]
How to add this (android:usesCleartextTraffic="true"). Because I don't know where it the file

**Comment by yodsaphon** [comment]
When I add that config when I build I got this error.
NullReferenceException: Object reference not set to an instance of an object
AndroidManifest.SetHardwareAccelerated (System.Boolean enabled) (at Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs:181)
UnityWebViewPostprocessBuild.OnPostGenerateGradleAndroidProject (System.String basePath) (at Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs:24)
UnityEditor.Android.AndroidBuildPipelineInterfaces.OnGeneratePlatformProjectPostprocess (System.String path, System.Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Android/AndroidPostGenerateGradleProject.cs:39)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by yodsaphon** [comment]
This is my AndroidManifest.xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="net.gree.unitywebview"
      android:versionCode="1"
      android:versionName="1.0">
<uses-permission android:name="android.permission.INTERNET" />
<application android:usesCleartextTraffic="true">
</application>
</manifest>

**Comment by KojiNakamaru** [comment]
At first, please remove your AndroidManifest.xml and build your app. Then,

* If your Unity is older than 2018.1, you should find `Assets/Plugins/Android/AndroidManifest.xml` as for those Unity versions this plugin's UnityWebViewPostprocessBuild.cs emits this file.
* If you cannot find `Assets/Plugins/Android/AndroidManifest.xml` as your Unity is 2018.1 or newer, please copy `Temp/gradleOut/src/main/AndroidManifest.xml` to `Assets/Plugins/Android/AndroidManifest.xml`.

This `Assets/Plugins/Android/AndroidManifest.xml` can then be edited adequately.

**Comment by yodsaphon** [comment]
Thank you very much. You help my life.

**Comment by GameDevBhavesh** [comment]
where is that temp folder location ???
