### ISSUE TITLE
why apk is so big when its not much things??

### ISSUE THREAD

**Issue by GameDevBhavesh** [gree/unity-webview#486]
i have a game projects with lots of files graphics and when i build that project it's somewhere around 16 - 17 mb but when i downloaded your project and build  its apk size is 27 mb even it doesn't have much assets why ??

**Comment by KojiNakamaru** [comment]
The sample app's Scripting Backend is set to Mono and the resulting apk contains Mono-related dll. If you set the Scripting Backend to IL2CPP and set Target Architectures to ARMv7 and ARM64, the apk size should become around 15M.

**Comment by GameDevBhavesh** [comment]
@KojiNakamaru thanks!
