### ISSUE TITLE
How to play video?

### ISSUE THREAD

**Issue by create-4** [gree/unity-webview#49]
I try autoplay or embed mp4 format videos, I do press to play button but not play. ( I try it on local and web page)

**Comment by KojiNakamaru** [comment]
Although it won't work on osx/unity editor, it should work on android/ios devices. The implementation for osx/unity editor is mainly intended for development use and may not work well as those for mobile devices.

Please also note that iOS9 forbids http (not https) connections by default. You can temporarily allow http connections by adding the following in Info.plist.
```
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
```

**Comment by gverhaar** [comment]
can we use the webview to play a youtube video? This works on iOS. Can it also work on Android?

Example:
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/p4zluA60hjs?rel=0&amp;showinfo=0&autoplay=1" frameborder="0" allowfullscreen></iframe>

**Comment by KojiNakamaru** [comment]
Yes, it works also on Android, though autoplay won't work.
cf. http://stackoverflow.com/a/15093243

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.

**Comment by Randyanto** [comment]
I tried it in Android, the audio is working and the touch is working too but the video becomes black when I play it just the audio is playing.

**Comment by KojiNakamaru** [comment]
Could you please follow the steps described at https://github.com/gree/unity-webview#android .

**Comment by Randyanto** [comment]
@KojiNakamaru found the bug! The minSDKVersion is 9 so I change it to 11 and it works :+1: thanks!

**Comment by KojiNakamaru** [comment]
That's good:-)
