### ISSUE TITLE
Deprecated API Usage -UIWebView

### ISSUE THREAD

**Issue by bwiniarczyk** [gree/unity-webview#490]
Using the latest builds and targeting iOS9, I am unable to upload to apple without getting this error.

ITMS-90809: Deprecated API Usage -  Apple will stop accepting submissions of apps that use UIWebView APIs . | ITMS-90809: Deprecated API Usage -  Apple will stop accepting submissions of apps that use UIWebView APIs .

I understand from other comments that you have resolved this error but I'm still seeing it.

WebView.mm has the date of 11/27/19 if that helps. Anything else I can check to make sure I have the latest?

I appreciate all your work on this and making it available!

**Comment by KojiNakamaru** [comment]
At least the sample app built for iOS9 has no reference to UIWebView. My environment is 

* Unity 2019.2.14f1
* Xcode 11.2.1

and I've checked as below.

```shell
$ cd DerivedData/Unity-iPhone/Build/Products/ReleaseForRunning-iphoneos/sample.app
$ grep -R WKWebView .
Binary file ./sample matches
Binary file ./Data/Managed/Metadata/global-metadata.dat matches
$ grep -R UIWebView .
$
```

Do you have any ad-related libraries and/or other middleware in
your app? Some of them might not show UIWebView but utilize it to
retrieve user agents.

**Comment by bwiniarczyk** [comment]
Thanks for your quick response. I have confirmed that this was in fact an issue with a Unity package. I have removed Ads from my project and the problem has been solved.
