### ISSUE TITLE
Get URL

### ISSUE THREAD

**Issue by BuZLuCaY** [gree/unity-webview#50]
Hi,
I use webview on Unity Android.
How to get URL at run time?

I need access this function : http://developer.android.com/reference/android/webkit/WebView.html#getUrl()

**Comment by KojiNakamaru** [comment]
Though we could extend WebViewPlugin.jar, the following might be sufficient:

```csharp
webViewObject.EvaluateJS("if (location) window.Unity.call(location.href);");
```

This will return the current url to the callback.

**Comment by BuZLuCaY** [comment]
string Url;
    WebViewObject webViewObject;
    public static string AccessToken { get; set; }
    string UrlKontrol;

    string mUrl;

    void Start()
    {

        Url = "https://graph.facebook.com/oauth/authorize?client_id=296194087105506&redirect_uri=http://www.facebook.com/connect/login_success.html&scope=publish_actions&type=user_agent&display=popup";
        webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
        webViewObject.Init((msg) =>
        {
            if (msg.StartsWith("http"))
            {
                mUrl = msg.Substring(4);
            }

        });
        webViewObject.EvaluateJS(@"
            window.addEventListener('onpageshow', function(){
            Unity.call('url:' + window.location.href);
             }, false);
        ");

        webViewObject.EvaluateJS("if (location) window.Unity.call(location.href);");

        webViewObject.SetMargins(5, 200, 5, 500);
        webViewObject.SetVisibility(true);
        webViewObject.LoadURL(Url);
    }

    void OnGUI()
    {
        
        GUI.Box(new Rect(0, 0, 300, 25), mUrl);
    }

Not return the current url. :/
