### ISSUE TITLE
Error in Webgl 

### ISSUE THREAD

**Issue by levin-Imagin8ors** [gree/unity-webview#501]
Hi @KojiNakamaru  @shika-n 
I'm getting this error in webgl.
Unity Version: 2018.4.13f 
exception thrown: TypeError: Cannot read property 'contentWindow' of undefined,TypeError: Cannot read property 'contentWindow' of undefined
    at Object.loadURL ()
    at __gree_unity_webview_loadURL

**Comment by KojiNakamaru** [comment]
I'm sorry that information for building WebGL apps is insufficient. I've added extra steps in README as below, so could you please try them?

https://github.com/gree/unity-webview/tree/2789b555c1755108de8b347e3aa766f98f29598a#webgl

**Comment by levin-Imagin8ors** [comment]
It worked. Thanks

**Comment by danialnazir** [comment]
> It worked. Thanks

Can you help me wit that iam working on 2019.4 
i also downloaded unity 2018.4 
but still im unable to make it work as my understanding of things is not very good 
ill be thank full to you

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/669#issuecomment-812441185
