### ISSUE TITLE
WebGL unsupported?

### ISSUE THREAD

**Issue by edgargaza** [gree/unity-webview#508]
Hello. Sorry if it's a dumb question but as you tell in your readme, WebGL is supported, right? Well, I'm importing the sample project on my Unity project (2019.2.17f1 version), targeting for WebGL platform and developing in Windows OS, but nothing happens when I press play (not even the status text changes).

I've found this line of code on **WebViewObject.cs**:

`... #if UNITY_WEBPLAYER || UNITY_WEBGL //TODO: UNSUPPORTED ...`

Also, in the same file, there're few lines like this as well:

`... #elif UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN //TODO: UNSUPPORTED ...`

Could be something to do with this? Or I'm wrong and indeed WebGL is not supported yet?

Thank you!

**Comment by KojiNakamaru** [comment]
Windows (including Editor) is currently not supported. However, you should be able to export a WebGL content on Windows.

cf. https://github.com/gree/unity-webview/tree/c0ec40a7b248383c47c779fe7bb4acc6ddfe8ab4#unity-webview
cf. https://github.com/gree/unity-webview/tree/c0ec40a7b248383c47c779fe7bb4acc6ddfe8ab4#webgl
