### ISSUE TITLE
No able to open the live urls

### ISSUE THREAD

**Issue by DazzledApps** [gree/unity-webview#51]
Hi I am not able to open the live url is any specific way to do that or this plugin just open the static pages?

**Comment by aquastartw** [comment]
It can open live url, but need to rewrite some code. But its links are not clickable. Still try to figure out why.

**Comment by aquastartw** [comment]
I solved it. First, copy AndroidManifest.xml as noted [here] (https://github.com/gree/unity-webview#notes-on-adnroid). Second, change
```
android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false"
```
 to "true".

**Comment by KojiNakamaru** [comment]
The latest version doesn't have this issue but still we need to edit AndroidManifest.xml for performance.
cf. https://github.com/gree/unity-webview/tree/770f34b6b5253bfa2e25fb651e72c62834ebe03c#android
