### ISSUE TITLE
Is it possible to block pop-up windows?

### ISSUE THREAD

**Issue by DevelAx** [gree/unity-webview#510]
Is it possible to block pop-up windows like ads?

**Comment by KojiNakamaru** [comment]
This plugin doesn't support `window.open()` so any page depending on it should be blocked.

**Comment by DevelAx** [comment]
> This plugin doesn't support `window.open()` so any page depending on it should be blocked.

Sorry, I described the problem incorrectly.
Actually, I need to override JavaScript `alert()` function. Where can I do it? I tried it in the `Init` method:
```
ld: (msg) =>
{
  _webViewObject.EvaluateJS(@"
	window.alert = null;
	Window.prototype.alert = null;
");
  _webViewObject.SetVisibility(true);
},

```
but it was too late, the page `alert` had been already fired by the time I set it `null`.

**Comment by KojiNakamaru** [comment]
Okay, I implemented a new method to enable/disable alert dialogs in https://github.com/gree/unity-webview/pull/512 . Could you please import the latest binary and call `webViewObject.SetAlertDialogEnabled(false)` to disable alert dialogs.

**Comment by DevelAx** [comment]
Cool, thank you! 
Don't you plan to make a general method for changing `html/js` before activating it in the browser? Maybe something like a method which is called when each data stream chunk is being loaded with the ability to change it before passing it further.

**Comment by KojiNakamaru** [comment]
Yes, I would like to, however, there seems to be no easy way for system WebView components to do such things...
