### ISSUE TITLE
Dynamic URL loading

### ISSUE THREAD

**Issue by Catalyst-47** [gree/unity-webview#514]
First of all thanks for the plugin!!
Even if I change the URL the webview is still loading google as default

**Comment by KojiNakamaru** [comment]
If you open the sample app and select `SampleWebView`, you can find `Url`

![image](https://user-images.githubusercontent.com/2645978/75773858-0f359680-5d92-11ea-8fa0-bafc7edcbbfe.png)

which is processed as below:

https://github.com/gree/unity-webview/blob/d408b5e5bcd2251d6794f16424e173f68a0752d0/sample/Assets/Scripts/SampleWebView.cs#L108-L134

where the code loads local `Assets/StreamingAssets/sample.html` if `Url` is `sample.html`. You can change this `Url` to any url that you want to load. As you see in the code, you can also directly utilize `webViewObject.LoadURL()`.

**Comment by Catalyst-47** [comment]
I tried using webVIewObject.LoadURL() but the webview loads a empty white page

**Comment by KojiNakamaru** [comment]
Maybe you tried to load some `http:` links. `https:` links should work.
