### ISSUE TITLE
How to get URL ?

### ISSUE THREAD

**Issue by BuZLuCaY** [gree/unity-webview#52]
string Url;
    WebViewObject webViewObject;

    string mUrl;

    void Start()
    {

        Url = "https://graph.facebook.com/oauth/authorize?client_id=296194087105506&redirect_uri=http://www.facebook.com/connect/login_success.html&scope=publish_actions&type=user_agent&display=popup";
        webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
        webViewObject.Init((msg) =>
        {
            if (msg.StartsWith("http"))
            {
                mUrl = msg.Substring(4);
            }
            if (msg.StartsWith("url:"))
            {
                mUrl = msg.Substring(4);
            }

        });
        webViewObject.EvaluateJS(@"
            window.addEventListener('onpageshow', function(){
            Unity.call('url:' + window.location.href);
             }, false);
        ");

        webViewObject.EvaluateJS("if (location) window.Unity.call(location.href);");

        webViewObject.SetMargins(5, 200, 5, 500);
        webViewObject.SetVisibility(true);
        webViewObject.LoadURL(Url);
    }

    void OnGUI()
    {
        
        GUI.Box(new Rect(0, 0, 300, 25), mUrl);
    }

And I tried this code :https://github.com/gree/unity-webview/issues/8 

Not return the current url. :/

**Comment by KojiNakamaru** [comment]
Before calling `webViewObject.LoadURL(Url);` the page isn't loaded so that `location` won't exist. Though I've not tried https://github.com/gree/unity-webview/issues/8 `webViewObject.EvaluateJS("if (location) window.Unity.call(location.href);");` should invoke the callback if it is called on every frame, such as:
```c#
void Update()
{
    webViewObject.EvaluateJS("if (location) window.Unity.call('url:' + location.href);");
}
```

**Comment by BuZLuCaY** [comment]
This is working. Thank you for your answer.

**Comment by ramkeshcse084** [comment]
How are you taking url in string from  webViewObject.EvaluateJS("if (location) window.Unity.call('url:' + location.href);");   ?
When i am writing string url= webViewObject.EvaluateJS("if (location) window.Unity.call('url:' + location.href);"); 
getting error
please help .

**Comment by KojiNakamaru** [comment]
`webViewObject.EvaluateJS()` doesn't return any value. https://github.com/gree/unity-webview/issues/52#issuecomment-146583172 shows a method to send `location` by `Unity.call()` defined in JS, from JS to Unity. You can receive the value by `cb:` callback, which is specified as an argument of `webViewObject.Init()`:

https://github.com/gree/unity-webview/blob/4bcc76e5c43541c9608f48af40d0b9d7300af4b9/sample/Assets/Scripts/SampleWebView.cs#L34-L39

**Comment by pbgame55** [comment]
> Çağırmadan önce `webViewObject.LoadURL(Url);`sayfa yüklenmediği için bu `location`olmayacak. [#8'i](https://github.com/gree/unity-webview/issues/8) denememiş olmama rağmen `webViewObject.EvaluateJS("if (location) window.Unity.call(location.href);");`, aşağıdaki gibi her karede çağrılırsa geri aramayı başlatmalı:
> 
> ```cs
> geçersiz  Güncelleme ()
> {
>     webViewObject . EvaluateJS ( " if (konum) window.Unity.call('url:' + konum.href); " );
> }
> ```

In a multiplayer game, I want the masterclient to send the url currently valid for the masterclient to other players when masterclient press a button, and return the same url on each player's screen. For this I did something like this: 

`[PunRPC]
public void set(string masterValue)
    {
		masterValue = Url;
    }
    public	void sendurl()
    { 
   if	 (PhotonNetwork.IsMasterClient)
		{
			string masterValue = Url;
			photonView.RPC("set", RpcTarget.OthersBuffered, masterValue);
			set(masterValue);
			Debug.Log("urlne?" + masterValue);
		}
	}

	void Update()
	{
		webViewObject.EvaluateJS("if (location) window.Unity.call('url:' + location.href);");
		Debug.Log(Url);
	}`   
result : url for each player still as originally set(google).
If I add this inside set(): `webViewObject.LoadURL(Url);`  I get error for url: not set to an instance of an object

**Comment by KojiNakamaru** [comment]
@pbgame55 Please open another issue as your question is not directly related to this issue. Please also refer https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code .
