### ISSUE TITLE
Android build not opening play store links in the play store app.

### ISSUE THREAD

**Issue by Bisher-d790** [gree/unity-webview#523]
I've fixed this WebView error, not opening app url in Play Store, by rebuilding the WebViewPlugin.jar.
`
//// edited CWebViewPlugin.java /////
public boolean shouldOverrideUrlLoading(WebView view, String url) {
......
if (url.startsWith("https://play.google.com/store/apps/details?id=")
|| url.startsWith("http://play.google.com/store/apps/details?id=")) {

String URLSuffix = "https://play.google.com/store/apps/details?id=";
String appID = url.substring(URLSuffix.length());
System.out.println("equals market: " + appID);

try {
Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
view.getContext().startActivity(intent);
return true;
} catch (Exception e) { //google play app is not installed
Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=com.example"));
view.getContext().startActivity(intent);
return false;
}
} else if (url.startsWith("http://") || url.startsWith("https://")
|| url.startsWith("file://") || url.startsWith("javascript:")) {
System.out.println("equals http: " + url);
.......
//////////////////
`

**Comment by Bisher-d790** [comment]
I'll close this issue as my solution worked for me. Thanks very much.

**Comment by KojiNakamaru** [comment]
Thank you for providing your solution. Your solution shows how the plugin can be easily extended with small modification.
There is also a different approach: make a link to invoke `Unity.call()` for which the callback in C# invokes `Application.OpenURL()` to open the final target link.
