### ISSUE TITLE
Does not respond to clicks and scroll after returning

### ISSUE THREAD

**Issue by sutogan4ik** [gree/unity-webview#525]
Hi, I have such a problem. When I launch the application and the page loads, everything works fine, but if I minimize the application or turn off the screen and then turn it on, the web view does not respond to scrolling or clicking on page elements. I use unity 2018.4.19f1 and android 9. I used the code from the example and my own implementation, the result is the same. at the moment when the application is deployed or becomes visible, it is noticeable how the web view is redrawn.

**Comment by phda193** [comment]
Hi, I have the same problem as your problem. I use Unity 2018.4.19f1 and Android 10 (Samsung S9+).

**Comment by KojiNakamaru** [comment]
I'm sorry, the issue was introduced with the recent change #521. I've fixed it in #525 and updated binaries. Could you please try the latest.

**Comment by sutogan4ik** [comment]
I checked both scenarios, now it works fine. Thanks for your work!
