### ISSUE TITLE
How is it possible OnWebBrowserNewWindow event handling?

### ISSUE THREAD

**Issue by BuZLuCaY** [gree/unity-webview#53]
void OnWebBrowserNewWindow(string URL, int Flags, string TargetFrameName, ref object PostData, string Headers, ref bool Processed)
{
    Processed = true;
    //WBrowser.Navigate(URL);
}

I do not want to ensure the opening of a new window. Is it possible?

**Comment by KojiNakamaru** [comment]
You could modify WebViewPlugin.java and/or WebView.mm, but redefining `window.open` might be sufficient.

```C#
webViewObject.EvaluateJS(@"window.addEventListener('load', function(){window.open = function(url, name, features){}});");
```

This should be effective after webViewObject.LoadURL().

**Comment by BuZLuCaY** [comment]
I am trying to do compressible only login button. This page: http://www.mspb.gov/apps/iphone/images/help6.jpg

**Comment by BuZLuCaY** [comment]
Is this true?
webViewObject.EvaluateJS(@"window.removeEventListener('load', function(){window.open);

**Comment by BuZLuCaY** [comment]
Is this true?
webViewObject.EvaluateJS(@"window.removeEventListener('load', function(){window.open);
