### ISSUE TITLE
not showing any html page

### ISSUE THREAD

**Issue by Amitsoni5157** [gree/unity-webview#535]
hi KojiNakamaru,
I am bit confuse in your sample project I don't know how it will show web page. In android mobile it is only showing me GUI predefined boxes but not given HTML page.
why is it happening If I am giving it URL so it should be open some page and than your Unity.call will apply on some button. 
please help me 
thanks

**Comment by KojiNakamaru** [comment]
You may use http (instead of https) which is forbidden by default for recent Android devices.
cf. https://stackoverflow.com/questions/52594637/webview-is-not-loading-page-in-android-9-0/52598806#52598806

**Comment by Amitsoni5157** [comment]
Thank you so much for quick reply. I am using unity and android version is (7.1.2). I used http but it is 
also showing me white page on center of the screen and GUI button top of the screen.
URL=(http://example5157.000webhostapp.com/sample.html)

**Comment by KojiNakamaru** [comment]
UniWebView is a different plugin not related to unity-webview. Please check https://uniwebview.com/.

**Comment by Amitsoni5157** [comment]
okay got it. Thank you so much for this.
And your code is ruing perfectly
