### ISSUE TITLE
How is it possible click or window.open event handling?

### ISSUE THREAD

**Issue by BuZLuCaY** [gree/unity-webview#54]
I am trying to do compressible only login button. This example page: http://www.mspb.gov/apps/iphone/images/help6.jpg
Is this true?
webViewObject.EvaluateJS(@"window.removeEventListener('load', window.open));

**Comment by KojiNakamaru** [comment]
Sorry, I don't understand what "compressible only login button" means. Could you elaborate more about what you would like to do?

```c#
webViewObject.EvaluateJS(@"window.removeEventListener('load', window.open));
```

I guess this does nothing because `window.open()` isn't an event listener added by `window.addEventListener()`. In my comment https://github.com/gree/unity-webview/issues/53#issuecomment-146779617 I show how we can override `window.open()` and in the example I just ignore every call for `window.open()`. You can customize the behavior by changing the event listener `function(){window.open = function(url, name, features){}}`.

**Comment by BuZLuCaY** [comment]
I do not want to open a new web page. I just want to make the login process.

**Comment by KojiNakamaru** [comment]
Hmm. I tried the sample program for cnn.com. When I pushed the facebook "share" button, the webview transited to the login page without opening any new page so it seems okay.

Could you please provide a concrete example url that causes the issue? Then I can try it and may track the issue.

**Comment by BuZLuCaY** [comment]
Thing that I'm trying to do : if i am on Facebook Login page, i don't want to transmit to another page except for Facebook Login page. I just want to 'Login' button can be pressed.

**Comment by KojiNakamaru** [comment]
In the following picture you put:
![picture](http://www.mspb.gov/apps/iphone/images/help6.jpg)
Do you want to enable only two input fields and "Login" buttons, and want to disable other links?

**Comment by BuZLuCaY** [comment]
Yes :)

**Comment by KojiNakamaru** [comment]
Maybe the following works:
```c#
            webViewObject.EvaluateJS(
                "window.addEventListener('load', function() {" +
                "    var a_tags = document.getElementsByTagName('a');" +
                "    for (var i in a_tags) {" +
                "        if (! /login/.test(a_tags[i].href)) {" +
                "            a_tags[i].href = 'javascript:void(0)';" +
                "        }" +
                "    }" +
                "}, false);");
```

**Comment by BuZLuCaY** [comment]
It's working, but only the buttons closed. Links are active.

**Comment by KojiNakamaru** [comment]
Then the following should be okay, though it is very specific for https://m.facebook.com.
```c#
            webViewObject.EvaluateJS(
                "window.addEventListener('load', function() {" +
                "    var a_tags = document.getElementsByTagName('a');" +
                "    for (var i in a_tags) {" +
                "        if (! /login/.test(a_tags[i].href)) {" +
                "            a_tags[i].href = 'javascript:void(0)';" +
                "            a_tags[i].removeAttribute('data-ajaxify-href');" +
                "        }" +
                "    }" +
                "}, false);");
```

**Comment by BuZLuCaY** [comment]
I'll try it. I am grateful for your interest and your tolerance. Thanks :)

**Comment by BuZLuCaY** [comment]
It's working, but "Forgot Password?" and languages links are active.

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
