### ISSUE TITLE
Full Screen Not showing on Android.

### ISSUE THREAD

**Issue by ghost** [gree/unity-webview#55]
Only half of the Image fills the screen on Android any solution? 
Inputs too are not working.
Am testing it with Android 2.3

**Comment by WorlazMighty** [comment]
Sorry that did not do it for me.
A had a blank screen.

**Comment by WorlazMighty** [comment]
Thanks tried again. and it worked

**Comment by WorlazMighty** [comment]
Am still not getting input recognized. Despite following all the recommendations by others here.

**Comment by WorlazMighty** [comment]
Finally got it to work. Any Optimization. I've added the hardwareAccelerated = TRUE. But is Still very lagy and most of the time unresponsive

**Comment by KojiNakamaru** [comment]
Good. About the performance, if you use an old android device, hardwareAccelerated may not be effective.

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
