### ISSUE TITLE
Got an error on xcode while building sample file.

### ISSUE THREAD

**Issue by Webee-JC** [gree/unity-webview#556]
![image](https://user-images.githubusercontent.com/65617985/82356812-b0012d00-9a36-11ea-8c38-f2dde5a1bf4c.png)

I followed the instructions on the iOS part.
**Using:**
Unity 2019.2.1.17f1
macOS Catalina ver. 10.15.2
Xcode ver. 11.4.1

NOTE: It work fine on the Unity Editor when I played it but this happened on Xcode (**using Simulator**) and I don't know why.

**Comment by KojiNakamaru** [comment]
I've tested the sample app with the following environment/settings and it works without any issue.

* Unity 2019.2.17f1
* macOS Catalina 10.15.4
* Xcode 11.4.1
* Graphics API is OpenGLES2
* Target SDK is Simulator SDK

As your screenshot shows a part not related to this plugin, any other unknown issue might cause your problem.

**Comment by Webee-JC** [comment]
> I've tested the sample app with the following environment/settings and it works without any issue.
> 
> * Unity 2019.2.17f1
> * macOS Catalina 10.15.4
> * Xcode 11.4.1
> * Graphics API is OpenGLES2
> * Target SDK is Simulator SDK
> 
> As your screenshot shows a part not related to this plugin, any other unknown issue might cause your problem.

I just found out that the issue was part of Building the Unity App using iOS Simulator SDK (in order to use simulator in xcode) and not part of the plugin. Sorry.
