### ISSUE TITLE
I've been searching for a while now

### ISSUE THREAD

**Issue by Webee-JC** [gree/unity-webview#559]
I've been searching for a while now. How can I make this webview into popup like? Without the buttons and such. Please help.

**Comment by KojiNakamaru** [comment]
Have you tried https://github.com/gree/unity-webview#sample-project ?

**Comment by Webee-JC** [comment]
> Have you tried https://github.com/gree/unity-webview/tree/f9fe3cc6b648049c326abab1e3ab22b854544e33#sample-project ?

I've tried the sample but it only shows full screen. I've been editing the c# code and html file but nothing works. I can't somehow find to change it into a window like popup.

**Comment by KojiNakamaru** [comment]
In the sample app, a webview is displayed with margins for the whole screen. These margins are controlled by `webViewObject.SetMargins()`. If we need to show a "window frame",  we normally utilize uGUI to show it and place a webview adequately by utilizing `webViewOjbect.SetMargins()`.

**Comment by Webee-JC** [comment]
> In the sample app, a webview is displayed with margins for the whole screen. These margins are controlled by `webViewObject.SetMargins()`. If we need to show a "window frame", we normally utilize uGUI to show it and place a webview adequately by utilizing `webViewOjbect.SetMargins()`.

Yes, but when I tried that it will look like this and note I have a background image here.
![image](https://user-images.githubusercontent.com/65617985/82891890-13ccae00-9f81-11ea-952b-6b482ae89b83.png)

**Comment by KojiNakamaru** [comment]
I cannot understand. In your screenshot, is a webview shown as a white rectangle (with a blue button)? Is the black region "a background image"? If you "tried that", how do you make "a window frame" with "uGUI"?

**Comment by Webee-JC** [comment]
> I cannot understand. In your screenshot, is a webview shown as a white rectangle (with a blue button)? Is the black region "a background image"? If you "tried that", how do you make "a window frame" with "uGUI"?

I mean there should be a colored background image here but the webview overlap it. I've tried adjusting it using the "webViewObject.SetMargins" but it adjust only the inside of the webview, not the webview itself.

**Comment by KojiNakamaru** [comment]
Please start over from the sample app. At least it shows a blue background and several buttons, both are rendered by unity. By incrementally changing the sample app, you should identify your issue.

**Comment by Webee-JC** [comment]
> Please start over from the sample app. At least it shows a blue background and several buttons, both are rendered by unity. By incrementally changing the sample app, you should identify your issue.
> 
> Please also note the text "Development Build" in your screenshot should be rendered by unity. so the webview doesn't overlap the whole screen.

I've followed your advice. I will do some more experiment. I really hope there are more examples and documentation for this because this project help a lot. And thank you for your time on replying. I really appreciated it.
