### ISSUE TITLE
Javascript return value to Unity?

### ISSUE THREAD

**Issue by Webee-JC** [gree/unity-webview#563]
I have a API script and I have this script:
`$(document.body).on('th:order:confirmed', function (evt) {
            console.log(evt.detail.msg);
        });`
suppose this will return a value if the API is completed.
How can I apply this and get that value into unity? Any sample how I can do it?
Please help. Thanks!

**Comment by KojiNakamaru** [comment]
You can utilize `Unity.call()` to send a message to the Unity side: https://github.com/gree/unity-webview/blob/ac10622fc470d1886444b9462eecd131f3469488/sample/Assets/StreamingAssets/sample.html#L31

**Comment by Webee-JC** [comment]
> You can utilize `Unity.call()` to send a message to the Unity side:
> 
> https://github.com/gree/unity-webview/blob/ac10622fc470d1886444b9462eecd131f3469488/sample/Assets/StreamingAssets/sample.html#L31

Thats on html right? How about on the js?

**Comment by KojiNakamaru** [comment]
This example a `href` defines `onclick` event, which contains a javascript sentence `Unity.call('anchor');`. Also if you need to evaluate some javascript sentence, you can utilize `EvaluateJS()`:
https://github.com/gree/unity-webview/blob/ac10622fc470d1886444b9462eecd131f3469488/sample/Assets/Scripts/SampleWebView.cs#L103

**Comment by Webee-JC** [comment]
> This example defines a `href` with a `onclick` event which contains a javascript sentence `Unity.call('anchor');`. Also if you need to evaluate some javascript sentence, you can utilize `EvaluateJS()`:
> https://github.com/gree/unity-webview/blob/ac10622fc470d1886444b9462eecd131f3469488/sample/Assets/Scripts/SampleWebView.cs#L103

It worked! Thanks for the advice.
