### ISSUE TITLE
Can I run the web view on Android version 10?

### ISSUE THREAD

**Issue by Seul9** [gree/unity-webview#565]
I confirmed that webview works until Android version 9.
It does not work on Android version 10.
What can I do?

**Comment by KojiNakamaru** [comment]
Google radically changes the way to provide the webview component in Android 10,

https://www.androidpolice.com/2019/10/24/android-10-no-longer-uses-chrome-app-to-render-pages-inside-apps/

and this causes many troubles. The issue should be reduced by installing the latest Android System WebView from Google Play.

**Comment by Seul9** [comment]
'Android System WebView' is installed on the test phone, but it does not run the same.

If so, is this reference unavailable from Android version 10?

**Comment by Seul9** [comment]
'Android System WebView' is installed on the test phone, but it does not run the same.

If so, is this reference unavailable from Android version 10?

**Comment by KojiNakamaru** [comment]
I cannot understand what you means with "this reference," but for example the following might be helpful.

https://support.google.com/android/thread/15453501?hl=en

Even updating Android System WebView is troublesome.

**Comment by Seul9** [comment]
Does this plugin not support Android 10?
I do not understand with the link you answered.

How do I create a Unity project that is also compatible with Android 10 using this plugin?

**Comment by KojiNakamaru** [comment]
The plugin should be compatible with Android 10 without any extra step. Although I myself don't have a real Android 10 device, the sample app runs on AVD (Pixel 3 API 29) as below.

![image](https://user-images.githubusercontent.com/2645978/84669363-bc0ddb00-af5f-11ea-9d01-a1c2055339c6.png)

**Comment by Seul9** [comment]
Thank you for answer.

Since it does not apply in Android API 29, I used Logcat directly.

webViewObject.Init(
             err: (msg) =>
             {
                 Debug.Log("seul:" string.Format("CallOnError[{0}]", msg));
             }

Error'ERR_CLEARTEXT_NOT_PERMITTED' in Init() in start function

How to solve it?

` IEnumerator Start()
    {
        webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
        webViewObject.Init(
            cb: (msg) =>
            {
                Debug.Log("seul : " + string.Format("CallFromJS[{0}]", msg));
            },
            err: (msg) =>
            {
                Debug.Log("seul : " + string.Format("CallOnError[{0}]", msg));
            },`

<img width="590" alt="1" src="https://user-images.githubusercontent.com/66583923/84925348-b69dc580-b104-11ea-898e-bd7505c65568.png">
<img width="629" alt="2" src="https://user-images.githubusercontent.com/66583923/84925356-b8678900-b104-11ea-8605-af50fff38ac7.png">
<img width="1289" alt="3" src="https://user-images.githubusercontent.com/66583923/84925364-bbfb1000-b104-11ea-8ee7-4820996c34fa.png">

**Comment by KojiNakamaru** [comment]
Though ERR_CLEARTEXT_NOT_PERMITTED should happen also for Android 9, the following should help.

https://stackoverflow.com/questions/52594637/webview-is-not-loading-page-in-android-9-0/

More simply, it is better to access https sites only.

**Comment by Seul9** [comment]
Thank you for answer.
Since the https domain cannot be used,
I am trying to edit the Android manifest.xml.
application property
I want to add android:usesCleartextTraffic="true",

Where can I change it in UnityWebViewPostprocessBuild.cs file?

**Comment by KojiNakamaru** [comment]
I've updated UnityWebViewPostprocessBuild.cs in #566, so could you please import the latest package or update UnityWebViewPostprocessBuild.cs only (as you may not want to update other code). You need to define `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC`.

cf. https://github.com/gree/unity-webview/tree/f441e1d868dd0dd11bef8f7433a8613d10e974dc#usescleartexttraffic

**Comment by Seul9** [comment]
Thank you very much for your help.
We completed the web view corresponding to api29 with the uploaded file.
