### ISSUE TITLE
OSX Unity5.3 doesn't update webview texture

### ISSUE THREAD

**Issue by chobie** [gree/unity-webview#57]
Unity5.3 changes OpenGL version to 3.3. currently, unity-webview OSX doesn't work on default settings.

Workaround: use -force-opengl flag

```
open -a Unity --args -force-opengl
```

-- to japanese

Unity5.3はOpenGL3.3を使うようになったのでデフォルトの設定ではWebviewのテクスチャ更新が動作していません。
取り急ぎお困りの方は上記コマンドをTerminalから打ってOpenGL 2.1バックエンドを使うようにすればOSX上のUnityEditorでもWebviewが表示されるようになります。

**Comment by KojiNakamaru** [comment]
Fixed by https://github.com/gree/unity-webview/commit/9a3001d36a586334d7fc6fb8b3de7de91564c656
cf. http://forum.unity3d.com/threads/rendering-to-unity-texture-from-plugin-on-ios-in-unity-5.330316/
