### ISSUE TITLE
Expected expression on iOS build

### ISSUE THREAD

**Issue by sonicMinidragon** [gree/unity-webview#588]
Hi,
I installed the unity-webview-nofragment.unitypackage to update unity-webview. it was okay on the old version ( very old, likely 8 to 9 month ago).
But it give me an error on expected expression on building iOS.

![image](https://user-images.githubusercontent.com/67567842/92196327-9ed31380-eea1-11ea-81dd-32cc1148b71b.png)

Thank you very much if anyone can help me.

**Comment by KojiNakamaru** [comment]
At least the sample app built by Unity 2019.4.9f1 seems to be successfully compiled with Xcdoe 11.7. Could you please try the sample/similar environment?

**Comment by sonicMinidragon** [comment]
Thank you very much i tried with Xcdoe 11.7 and it is a xcode version problem
