### ISSUE TITLE
Loaded callback gets "Unknown URL"

### ISSUE THREAD

**Issue by lavikabel** [gree/unity-webview#592]
Hi,

I am running the sample on Mac (Catalina 10.15.6) and Unity (2020.1.4f1) and when the onLoaded callback is executed  it gets "Unknown URL" instead of the correct url. 
The url is correct in started callback.

Thanks

**Comment by KojiNakamaru** [comment]
Thank you for the report. I've fixed the issue and updated binaries. Could you please try the latest?

**Comment by lavikabel** [comment]
Yes, it looks great now.

Thanks for the (very) fast reply!
