### ISSUE TITLE
Webview with http url

### ISSUE THREAD

**Issue by daniloescobar** [gree/unity-webview#594]
Some android devices do not load the webview if the url is http, it only loads if it is https.
Can you help me ?

Android 7.0 works
Android 8.0 works
Android 9.0 dont work
Android 10 not tested

**Comment by KojiNakamaru** [comment]
Recent Android versions allow only https by default. For allowing http, please check the followings.

https://stackoverflow.com/questions/52594637/webview-is-not-loading-page-in-android-9-0/52598806#52598806
https://stackoverflow.com/questions/52594637/webview-is-not-loading-page-in-android-9-0/52687383#52687383

**Comment by daniloescobar** [comment]
Thanks! @KojiNakamaru 
I modified the manifest and added network_security_config, but it didn't work I saw in the note below that I would have to change the target for api 27, but the google console is already warning to put apps ready for android 10.

**Comment by daniloescobar** [comment]
my problem is that the site takes a streaming hls from an http server. My site is https, but it can't show the http video if I'm using https. And when I change the server to https it doesn't show the video because of the server's ssl error, unless I trust the site manually, this through the normal browser, how can I do this in the webview through the code?

**Comment by KojiNakamaru** [comment]
Did you really succeed to modify AndroidManifest.xml correctly? You can check your apk by utilizing Android Studio's following menu:

![image](https://user-images.githubusercontent.com/2645978/93404173-7ba65c00-f8c4-11ea-9cfc-d6a1a4781ed3.png)

You can also refer https://github.com/gree/unity-webview/issues/465#issuecomment-544256321 about how you can adjust AndroidManifest.xml.

**Comment by daniloescobar** [comment]
![apk analize](https://user-images.githubusercontent.com/71297782/93412933-8933f580-f874-11ea-905f-860000d9c2a7.png)
![apk analize2](https://user-images.githubusercontent.com/71297782/93412935-8a652280-f874-11ea-8702-ebc54ff28803.png)

apparently yes, my doubt is because when analyzing the file, the web address that I put in the file network_security_config does not appear

**Comment by daniloescobar** [comment]
apparently yes, my doubt is because when analyzing the file, the web address that I put in the file network_security_config does not appear

![apk analize](https://user-images.githubusercontent.com/71297782/93413223-24c56600-f875-11ea-81ea-9ca139ba72f3.png)
![apk analize2](https://user-images.githubusercontent.com/71297782/93413224-24c56600-f875-11ea-836b-989798d7c1d7.png)

**Comment by daniloescobar** [comment]
Now I saw my mistake, put it in the wrong place, put it in the metadata, tested it and it's working, thanks! @KojiNakamaru

**Comment by robertobrogi83** [comment]
@daniloescobar Hi, is possible to have more information about the flow?
can you send your manifest?
where i put the network_security_config.xml in my unity project?

thanks

**Comment by daniloescobar** [comment]
where i put the network_security_config.xml in my unity project?
\Assets\Plugins\Android\res\xml

here my manifest
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">put your site here</domain>
    </domain-config>
	<base-config cleartextTrafficPermitted="true">
           <trust-anchors>
              <certificates src="system" />
           </trust-anchors>
           </base-config>
</network-security-config>

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/610#issuecomment-721521070
