### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by DanielTortosa** [gree/unity-webview#6]
I started the sample project (with Google url) and i couldnt write letters in the google textbox).

Unity 3.5.7
Tested on HTC Desire and Nexus 7 (both with Android 4.2.1).

**Comment by KojiNakamaru** [comment]
A while back there was the issue discussed here and it was caused by NativeActivity. Recent Unity and unity-webview combination don't have the issue. Please reopen the issue if you have any assistance further.
