### ISSUE TITLE
WebGL issues on page loaded by unity-webview

### ISSUE THREAD

**Issue by viglucci** [gree/unity-webview#611]
Hello,

We are leveraging this asset package to render an HTML page which utilizes WebGL abstracted through the [Three.js](https://threejs.org/) library, and unfortunately, we are experiencing an issue where no output is produced from our scene.

Our scene renders as would be expected in native browsers both on desktop and on mobile devices, however, when we load the same scene on an HTML page loaded by `unity-webview` the output is different (nothing is drawn at all).

We are able to see that there are some warnings logged by `Three.js`, however, we aren't sure if this is to be expected, or if this indicates an issue/limitation with either this package or with the native webview leverage by Unity. Unfortunately, I am not experienced enough to say, so I am hoping maybe someone who knows more is able to point us in the right direction.

Should WebGL work "out of the box" on an HTML page loaded with `unity-webview`, or is there specific configuration/implementation details we should be aware of to "enable" WebGL in the webview?

The warnings we see from the HTML page loaded in `unity-webview` are the following:

```
THREE.WebGLRenderer: EXT_frag_depth extension not supported.
THREE.WebGLRenderer: WEBGL_draw_buffers extension not supported.
THREE.WebGLRenderer: EXT_shader_texture_lod_extension not supported.
```

Thanks for any assistance you can provide!

**Comment by KojiNakamaru** [comment]
WebGL should run without any issue. The following screenshots are captured on VANKYO S7 (android 9) and on iPhone SE2 (iOS 14.1) respectively, for https://threejs.org/examples/#webgl_shaders_ocean .

![image](https://user-images.githubusercontent.com/2645978/98237207-e3655300-1fa7-11eb-969d-1c47b1c4bb81.png)
![image](https://user-images.githubusercontent.com/2645978/98237229-e9f3ca80-1fa7-11eb-9ce0-947d7b879600.png)

Do you utilize `https` for every connection? Recent android/ios apps cannot use `http` by default and you need to extra settings to allow it.

**Comment by viglucci** [comment]
Thank you for the quick reply! We do indeed have `https` enabled and are able to verify that the textures are downloaded, and we believe that the issues are more-so that the scene is not rendered, rather than that the textures not downloading.

Additionally, we were able to test the same page in-app and experienced the same issue (no rendering), however, the demo scene works just fine in Chrome on the same device. We are going to try and update to the latest version of this plugin and see if that produces different results, and if so I will be sure to come back and close this issue.

Thanks again.

**Comment by viglucci** [comment]
Updating the package version did indeed resolve this issue. Again, thank you for the assistance :).
