### ISSUE TITLE
Send data from Unity to JS

### ISSUE THREAD

**Issue by fahadmaqsood** [gree/unity-webview#618]
how can I send data from c# to JS?

I tried manipulating url like "main.html#data1:data2" and tried to read url from JS and accessing data. but I couldn't get it working. I think webview doesn't load local files with hashtags.

**Comment by KojiNakamaru** [comment]
You can utilize `EvaluateJS(string)` to evaluate any javascript.

**Comment by fahadmaqsood** [comment]
Do you mean if I use `webViewObject.EvaluateJS("const data = [..];");` in c#, the variable `data` will be accessible from JS?

**Comment by fahadmaqsood** [comment]
I was able to get it working with your advice. Thank You!
