### ISSUE TITLE
DllNotFoundException: WebView on windows unity editor supported?

### ISSUE THREAD

**Issue by ramadansoft** [gree/unity-webview#62]
Hi,

I am trying to use that on windows editor. I get
"DllNotFoundException: WebView
WebViewObject.Init (System.Action`1 cb, Boolean transparent, System.String ua) (at Assets/Plugins/WebViewObject.cs:141)
SampleWebView+<Start>c__Iterator0.MoveNext () (at Assets/Scripts/SampleWebView.cs:39)"

It would be great if I can test on windows unity editor, is this supported?

Any help is greatly appreciated.

**Comment by KojiNakamaru** [comment]
Sorry, unity-webview is based on webkit-based system components (Android WebView, iOS UIWebView, and OSX WebView) and Windows is currently not supported.

**Comment by ramadansoft** [comment]
Thank you!
