### ISSUE TITLE
1 second delay after open app from tray

### ISSUE THREAD

**Issue by Fort44** [gree/unity-webview#621]
when hide app(not close) in tray and open again webview object loaded 1 sec and i see my scene. My customer want to remove this delay. How can i fix this problem?

**Comment by KojiNakamaru** [comment]
I'm not sure but I guess your target is android, as the Android implementation hides and shows a webview when the app is resumed. It is required for avoiding the keyboard layout issue. It is however not necessary when the keyboard is not displayed, so I've adjusted the code in #623 and updated binaries. Could you please try the latest?

**Comment by Fort44** [comment]
It works, thank you very much)
