### ISSUE TITLE
ERR_ACCESS_DENIED in webview in Android -android sdk 30 file://

### ISSUE THREAD

**Issue by Sqrt333** [gree/unity-webview#625]
i know the problems 
https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccess(boolean)
can you fix this?

**Comment by KojiNakamaru** [comment]
I've adjusted the code to call setAllowFileAccess(true) and updated binaries. Could you please try the latest?

**Comment by D33pTh0ught** [comment]
A bit late, but I just wanted to comment that updating the binaries fixed the issue. So I think this issue can be closed.
