### ISSUE TITLE
Playing youtube videos does not work

### ISSUE THREAD

**Issue by ramadansoft** [gree/unity-webview#63]
Hi,

When I enter a youtube url, I get the thumbnail and play button rendered correctly on both MAC unity editor and Android, but when I press play, it just spins indefinitely.
Android additionally displays an error message "If playback doesn't begin shortly, try restarting your device."

Thanks.

**Comment by KojiNakamaru** [comment]
The OSX implementation is intented mainly for debugging and is tricky one - it creates an offscreen WebView, delegates events to it and copies a rendered image into a texture. A youtube embedded player seems not working for this tricky implementation.

On iOS, a youtube player should work without any issue, though it may depend on iOS versions. At least on iPad3/iOS9.2.1, I've confirmed the following player worked.

```
    <iframe id="ytplayer" type="text/html" width="640" height="390"
            src="http://www.youtube.com/embed/M7lc1UVf-VE"
            frameborder="0"></iframe>
```

On Android, same settings may cause a trouble as you described. Please try the following:
https://github.com/gree/unity-webview#notes-on-adnroid
I've confirmed the above player works with this setting, on Nexus 7 (2013)/Android 6.0.1.

**Comment by ramadansoft** [comment]
I added the android:hardwareAccelerated="true" to the android build and it worked correctly.
I am sorry I did not notice that earlier.
