### ISSUE TITLE
Xcode build error with v4

### ISSUE THREAD

**Issue by MaxMaioli** [gree/unity-webview#635]
Hi, i've just upgraded to v4, and i've got a lot of error building my app for ios. (unity 2019.2.2)

here is my webview initialization:

`        
var webView = webviewObject.AddComponent<UniWebView>();

webView.SetShowSpinnerWhileLoading(true);

webView.SetHorizontalScrollBarEnabled(true);

webView.OnMessageReceived += OnReceivedMessage;

webView.SetShowToolbar(false);

i've checked that webkitframework is included in "Link Binary with libraries'.

I've read in other post to enable enableWKWebView, but my gameobject doesn't have this method.

here is my xcode logs, thanks.

webView.SetZoomEnabled(true);`

Undefined symbols for architecture arm64:
  "__CWebViewPlugin_GetCustomHeaderValue", referenced from:
      _WebViewObject__CWebViewPlugin_GetCustomHeaderValue_mD4EEB08764422357380B9C8C9846F519DAD573EF in Assembly-CSharp-firstpass1.o
     (maybe you meant: _WebViewObject__CWebViewPlugin_GetCustomHeaderValue_mD4EEB08764422357380B9C8C9846F519DAD573EF)
  "__CWebViewPlugin_SetFrame", referenced from:
      _WebViewObject__CWebViewPlugin_SetFrame_m27024B91D7A029B18F8087B6D2D347AA6C187D1D in Assembly-CSharp-firstpass1.o
      _WebViewObject_SetCenterPositionWithScale_m459D84B76D569BF987B6EFAE8792277536FE694F in Assembly-CSharp-firstpass1.o
     (maybe you meant: _WebViewObject__CWebViewPlugin_SetFrame_m27024B91D7A029B18F8087B6D2D347AA6C187D1D)
  "__CWebViewPlugin_AddCustomHeader", referenced from:
      _WebViewObject__CWebViewPlugin_AddCustomHeader_m0A76918AE42972FD5E980A74C0AD1BF6F65BFF1F in Assembly-CSharp-firstpass1.o
     (maybe you meant: _WebViewObject__CWebViewPlugin_AddCustomHeader_m0A76918AE42972FD5E980A74C0AD1BF6F65BFF1F)
  "__CWebViewPlugin_CanGoForward", referenced from:
      _WebViewObject__CWebViewPlugin_CanGoForward_m46DFC8FDA3B7A107072DE1E3249588A34A0A6DA6 in Assembly-CSharp-

**Comment by KojiNakamaru** [comment]
What do you mean by "v4"? Also this plugin doesn't have the following APIs:

```csharp
webView.SetShowSpinnerWhileLoading(true);
webView.SetHorizontalScrollBarEnabled(true);
webView.OnMessageReceived += OnReceivedMessage;
webView.SetShowToolbar(false);
```

**Comment by MaxMaioli** [comment]
i'm very sorry, i confused plugins, please close this issue.
