### ISSUE TITLE
IOS redirect not working

### ISSUE THREAD

**Issue by wengyuan1110** [gree/unity-webview#638]
Hi,
This is a great plugin. Everything work fine so far except redirect url in IOS.

In my main web page, there is a button which will open a new tab. This works fine in android. But for ios, it only trigger CallOnStarted and not response after that. If I change "Open on the new tab" to "open on the same page" from my web page, everything works fine. But I need it to be "Open on the new tab" for some reasons.

How do I solve this issue?

Thank you.

**Comment by KojiNakamaru** [comment]
I confirmed that the code worked for `<a href="..." target="_blank">...</a>` but not for `window.open("...", "_blank")`, so I applied another fix #639 . Could you please try the latest?

**Comment by wengyuan1110** [comment]
Hi @KojiNakamaru  Thanks for the reply. I did the same fix and it works on IOS now.
