### ISSUE TITLE
MAC Editor webview is not loaded non-secure http or self signed https

### ISSUE THREAD

**Issue by ramadansoft** [gree/unity-webview#64]
Hi,

I am trying to do some tests inside my MAC Unity Editor, but I noticed that only https urls are loaded, otherwise, they are not loaded.
So I created a self signed certificate on my LAN server, I added the certificate to MAC System Keychain and set it to trusted, but even after that I cannot get the HTTPS url to be loaded inside the MAC Editor webview.

The urls are correctly loaded only when it is HTTPS with a certificate from a trusted certificate authority.

Any hep is greatly appreciated.

**Comment by ramadansoft** [comment]
Hi,

I found a solution on the internet.

Find the Unity.app file then right click and 'Open Contents', then browse to 'Contents\Info.plist' and open it in a text editor.

Then add the following text before the closing </dict> at the end of the file.

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

Source:
https://onevcat.zendesk.com/hc/en-us/articles/215527307-I-cannot-open-the-web-page-in-Unity-Editor-

**Comment by KojiNakamaru** [comment]
Thank you very much for the valuable comments! I was just stuck in this issue and now it has gone. I'll later add this info to README.md.
