### ISSUE TITLE
use unity2020.2.2  Undefined symbols for architecture arm64:_UnitySendMessage,_UnityGetGLViewController

### ISSUE THREAD

**Issue by rc0903** [gree/unity-webview#656]

**Comment by rc0903** [comment]
ok

**Comment by rc0903** [comment]
ok

**Comment by lutfianasari** [comment]
Hi!
There is no description about this issue, but I actually encountered the same error.
I used Unity 2019.4

Do we have to change some settings on Unity or Xcode to solve the error?
My app didn't get any error when trying with Unity 2019.1.

**Comment by KojiNakamaru** [comment]
I put a modified sample that can be directly opened with 2019.4.40f1 under https://github.com/gree/unity-webview/tree/example-for-656/sample . A Xcode project exported from this app can be built with Xcode 14.3 by specifying UnityFramework and Unity-iPhone's architecture to arm64.

**Comment by lutfianasari** [comment]
@KojiNakamaru さん、Thanks for you reply.
I opened the sample, built it to Xcode, and finally could figure out how to do the Build Setting!
Very helpful sample, thanks.
I have a new problem (css from server not loaded), but I guess I have to make a new issue.
