### ISSUE TITLE
How to hide scrollbar in iOS?

### ISSUE THREAD

**Issue by theolovesyou** [gree/unity-webview#660]
I want to disable zoom in zoom out on webview so, 
I set html document like 
meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
or
meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
and it worked on Android but it doesn't on iOS.

so i made another empty webview on my webview
and it block under layered webview so it does not zoomed,
but empty webview is still zoomed in out.

is there a way to disable zooming on iOS or how to hide scrollbar?
thanks!

**Comment by KojiNakamaru** [comment]
Hmm, at least the sample app works correctly with the following modification. My environment is iPhone SE 2nd (iOS 14.4.1) and Unity 2019.4.18f1.

```diff
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 38de86b..d830f18 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -1,6 +1,7 @@
 <html>
   <head>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
+    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
     <title>Unity WebView</title>
     <script src="sample.js"></script>
     <!-- geolocation example
```

**Comment by theolovesyou** [comment]
Thankyou. i just copy and paste you html tag and it works.
thank you again!!!

**Comment by theolovesyou** [comment]
using html tag above solve the problem.
