### ISSUE TITLE
Allow only one domain's webpages

### ISSUE THREAD

**Issue by elephantmobiledev** [gree/unity-webview#667]
Hi. Firstly, sorry for my bad english. I want to deny all websites except just one domain's websites. Like that, deny all webpages except webpages of google.com. google.com/a... , google.com/b..., google.com/...

**Comment by KojiNakamaru** [comment]
You can utilize `SetURLPattern()` as below. For details, please refer https://github.com/gree/unity-webview/pull/550 .

```
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 95e8ba6..f426e1d 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -127,6 +127,7 @@ public class SampleWebView : MonoBehaviour
         // cf. https://github.com/gree/unity-webview/pull/550
         // introduced SetURLPattern(..., hookPattern). by KojiNakamaru · Pull Request #550 · gree/unity-webview
         //webViewObject.SetURLPattern("", "^https://.*youtube.com", "^https://.*google.com");
+        webViewObject.SetURLPattern("^https://.*google\\.com/", ".*", "");
 
         // cf. https://github.com/gree/unity-webview/pull/570
         // Add BASIC authentication feature (Android and iOS with WKWebView only) by takeh1k0 · Pull Request #570 · gree/unity-webview
```

**Comment by elephantmobiledev** [comment]
Thank you so much.

And i would like to do that, if the url was denied, open it with Application.OpenURL(). How can do that?

**Comment by KojiNakamaru** [comment]
Okay, then you can adjust the regex as below:
```csharp
webViewObject.SetURLPattern("^https://.*google\\.com/.*", ".*", "");
```

**Comment by elephantmobiledev** [comment]
That works. Thank you so much. 

If i want to allow two or more urls, can i use `webViewObject.SetURLPattern` again in the same script? Or how should i do it?

**Comment by elephantmobiledev** [comment]
Thank you again.
