### ISSUE TITLE
Vimeo Video Issue - Android

### ISSUE THREAD

**Issue by mimminito** [gree/unity-webview#67]
Hi,

I am trying to get a Vimeo video to play on Android, but its not working. I am calling LoadUrl with the Vimeo link, but when I press the play button on the page nothing happens? Any suggestions?

Adam

**Comment by KojiNakamaru** [comment]
Could you please check the followings:
* https://github.com/gree/unity-webview#notes-on-adnroid
* https://github.com/gree/unity-webview/issues/63#issuecomment-174369462

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
