### ISSUE TITLE
Callbacks on Android

### ISSUE THREAD

**Issue by pwdz** [gree/unity-webview#671]
Hi.
I have a problem with OnLoaded and OnStarted callbacks in android.
I use `WebViewObject` a couple of times in my game. Each time I init the webView with new configs and destroy it after user closes the webview(using backbutton). 
The problem is that after first time that webview is destroyed and afterwards initialized later, callbacks won't work and as it seems they're not being called.

Although when I make the webView object `DontDestroyOnLoad` and only active and deactive it instead of initialization and destruction in different parts of the game, it works fine and callbacks do the job correctly. 
But I need to destroy and init the webView cause I don't want to have a queue for `GoForward` and `GoBack` and I want it to be cleared. Plus, I want to use different callbacks in each initialization.

**Comment by KojiNakamaru** [comment]
I'm sorry for this late reply. The sample app has a button to destroy/create a webview:

https://github.com/gree/unity-webview/blob/a11f2c2dff17feb9ebbed5beb81721ca5d5db348/sample/Assets/Scripts/SampleWebView.cs#L203-L210

It works for my environment (Unity 2019.4.18f1/Vankyo S7 (Android 9)) and both `started:` and `ld:` are called when a webview is created. Could you please provide a diff for the sample app to reproduce the issue?

**Comment by pwdz** [comment]
Thank you sincerely
I fixed my issue in some other way and unfortunately couldn't spend more time on this issue and test and reproduce what you asked.
I close this issue for now. tnx again.
