### ISSUE TITLE
Cannot Auto-fit WebView content to mobile screen

### ISSUE THREAD

**Issue by ReGaSLZR** [gree/unity-webview#673]
Hello, @KojiNakamaru -san.

The HTML code my team is trying to load on the mobile screen doesn't adapt to the screen size. Their codes don't use `%` on `width` values and there are outrageous values like `8000px`. I've already suggested to them to use fluid styling with `%` values.

![Screenshot_20210413-170135](https://user-images.githubusercontent.com/50439252/114519829-bfefb400-9c7b-11eb-970f-76bc7d68bb68.png)

But on the Unity/ plugin side, I was just wondering if there is something I can do to auto-adjust the `WebViewObject` to fit the screen, at least, horizontally?

EDIT: The fix from this ticket https://github.com/gree/unity-webview/issues/230 doesn't work on my end.
EDIT 2: I also tried setting `wkContentMode = 1` on the `WebViewObject.Init()`... but it doesn't auto-adjust the WebView content horizontally.
EDIT 3: My testing environment is Android (Google Pixel 4)

**Comment by KojiNakamaru** [comment]
The target site seems to be designed only for PC, so showing PC pages should solve the issue (though the site should support mobile pages correctly as you pointed out).

* wkContentMode is effecitve only for WKWebView (iOS) and the WKWebView forcibly shows mobile pages if it is set to 1. For showing PC pages, it should be set to 2.
* Setting PC user-agent through `webViewObject.Init(ua: "...")`, for example `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.74 Safari/537.36 Edg/79.0.309.43` could make a webview show PC pages.

**Comment by ReGaSLZR** [comment]
Thank you for the response, @KojiNakamaru -san. So using `wkContntMode` won't work for Android. Got it.
I also tried the `ua` value but unfortunately, it doesn't fit the desired output.
Anyway, thank you for acknowledging that making the HTML page be adaptive is the way to solve the issue.

I'll close this ticket now since clearly, the problem is on the HTML side, not on the plugin.
More power to you and your team!
