### ISSUE TITLE
How can ı add this into a cube or canvas ı want? 

### ISSUE THREAD

**Issue by pbgame55** [gree/unity-webview#682]
Can I transfer the webview from the plugin onto a cube?

**Comment by KojiNakamaru** [comment]
Unfortunately no. Please check https://github.com/gree/unity-webview/issues/658#issuecomment-793636658 .

**Comment by pbgame55** [comment]
Thank you, since I am not professional on this subject, I want to ask another question, there is one picture on the canvas, and the dimensions of the picture are: posx 16, posy 66, width 280, height 157. And I want the webview screen to have these dimensions too.
webViewObject.SetMargins (16,66,280,157); When I write this way, the webview image does not have the size of the picture, what am I doing wrong, how should I place these values?
 #567  this is not possible for me. Thank you again.

**Comment by KojiNakamaru** [comment]
The argments of `SetMargins()` are margins from left/top/right/bottom screen edges, so in your case the following should work:

```csharp
    webViewObject.SetMargins(16, 66, Screen.width - (16 + 280), Screen.height - (66 + 157));
```

**Comment by pbgame55** [comment]
Thank you for your attention and for this nice plugin problem solved.
