### ISSUE TITLE
problems caused by changing "introduce dark mode" (#665)

### ISSUE THREAD

**Issue by laoshanlong** [gree/unity-webview#683]
i need the ability to set setForceDark regardless of the display setting of the android system.

currently, the ui including the webview implemented using the plugin has an inconsistent shape as the background color becomes white or black depending on the user's android system display setting.

since it is difficult to change the theme setting of the app, it is necessary to bypass the part that specifies setForceDark of the webview in the initial setting or add a function that can be directly specified.

**Comment by KojiNakamaru** [comment]
I added `androidForceDarkMode` argument for `WebViewObject.Init()` in #684 and updated binaries. By referring the following

https://github.com/gree/unity-webview/blob/d5f52c4e047f12c0d0a07c10c344295fe5c1b7b0/sample/Assets/Scripts/SampleWebView.cs#L118

please set this argument adequately.

**Comment by laoshanlong** [comment]
thanks for help :)

**Comment by laoshanlong** [comment]
sorry, it's a mistake
