### ISSUE TITLE
iOS error

### ISSUE THREAD

**Issue by msureka** [gree/unity-webview#69]
Hello,

The Sample project on iOS works fine, but when I add it in my working project, it gives an error. I have other plugins like Facebook, Appsflyer, GA. Anything to do because of this?

Please help.

Thanks

Undefined symbols for architecture arm64:
  "__WebViewPluginMakeTransparentBackground", referenced from:
      _WebMediator__WebViewPluginMakeTransparentBackground_m545 in Bulk_Assembly-CSharp-firstpass_0.o
      _WebMediator_MakeTransparentWebViewBackground_m550 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _WebMediator__WebViewPluginMakeTransparentBackground_m545)
  "__WebViewPluginSetMargins", referenced from:
      _WebMediator_ApplyMarginsPlatform_m547 in Bulk_Assembly-CSharp-firstpass_0.o
      _WebMediator__WebViewPluginSetMargins_m543 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _WebMediator__WebViewPluginSetMargins_m543)
  "__WebViewPluginLoadUrl", referenced from:
      _WebMediator__WebViewPluginLoadUrl_m541 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _WebMediator__WebViewPluginLoadUrl_m541)
  "__WebViewPluginInstall", referenced from:
      _WebMediator_Install_m532 in Bulk_Assembly-CSharp-firstpass_0.o
      _WebMediator_InstallPlatform_m546 in Bulk_Assembly-CSharp-firstpass_0.o
      _WebMediator__WebViewPluginInstall_m540 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _WebMediator__WebViewPluginInstall_m540)
  "__WebViewPluginSetVisibility", referenced from:
      _WebMediator_UpdatePlatform_m548 in Bulk_Assembly-CSharp-firstpass_0.o
      _WebMediator__WebViewPluginSetVisibility_m542 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _WebMediator__WebViewPluginSetVisibility_m542)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KojiNakamaru** [comment]
There is no such symbol like MakeTransparentBackground in https://github.com/gree/unity-webview but it is found in https://github.com/kimsama/unity3d-webview-csharp so some of SDKs you installed perhaps utilize the latter. 

Basically both https://github.com/kimsama/unity3d-webview-csharp and https://github.com/gree/unity-webview derived from https://github.com/keijiro/unity-webview-integration and shouldn't have much difference. I guess it is better to utilize https://github.com/kimsama/unity3d-webview-csharp only. If you still want to utilize https://github.com/gree/unity-webview,  it could be possible by changing class names in unity-webview (WebViewPlugin -> CWebViewPlugin, for example) not to conflict with those in unity3d-webview-csharp. Please let me know if you need this, I'll then modify class names.

**Comment by msureka** [comment]
Hello,

Thanks for your reply. Not sure if any of the other plugins are using kimsama sdk internally. 

However, for our webview purposes we would like to use gree sdk, so if you could modify the class names it would be great! 

Thanks
Mohit

**Comment by KojiNakamaru** [comment]
I've modified the class name: https://github.com/gree/unity-webview/pull/70. Could you please try the latest.

**Comment by msureka** [comment]
Thanks will download the zip again and give it a run!

**Comment by msureka** [comment]
Hi,

When we build the sample, we are getting an error when it tries to import
Appkit/Appkit.h. It says file not found. We are building this for iOS, so
not sure why it is trying to import Appkit framework.

Regards
Mohit



On Tue, May 10, 2016 at 9:38 AM, Mohit Sureka <msureka@gmail.com> wrote:

> Thanks will download the zip again and give it a run!
>
>
>
> On 10-May-2016, at 9:33 AM, Koji Nakamaru <notifications@github.com>
> wrote:
>
> I've modified the class name: #70
> <https://github.com/gree/unity-webview/pull/70>. Could you please try the
> latest.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gree/unity-webview/issues/69#issuecomment-218053961>
>
>


-- 
Spiel Studios
7, Swastik Society,
Gulmohar road,
Vile Parle - west,
Mumbai - 400056.
India.

Tele-fax.: (91-22) 2618 5580 / 2611 5995
Cell: 98200 59980
Web: http://www.spiel-s.com

**Comment by KojiNakamaru** [comment]
If you remove unity-webview files, can the project be built without errors? The unity-webview iOS version (`Assets/Plugins/iOS/WebView.mm`) doesn't have any import for `Appkit.h` so some code in SDKs you installed should refer it.

**Comment by KojiNakamaru** [comment]
Ah, are you trying to build the sample instead of your project? In the first comment you seemed to successfully run the sample, so you can perform the same steps, specifically https://github.com/gree/unity-webview#sample-project .

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
