### ISSUE TITLE
fix font-size regardless system setting on Android

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#697]
Hi, 
we have been using this plugin since few years ago.
Thank you very much for everyone's efforts.

Does someone know how to make the font-size of the content keep the same,
although user set the system font size in Android bigger?

My app layout become ugly when user do this, and off course we don't want this happens.
Is there any setting than can be done through the library in this plugin?

We are using Unity 2019.2 and tested on some Android phones.

**Comment by KojiNakamaru** [comment]
I've added SetTextZoom() in https://github.com/gree/unity-webview/pull/698 and updated binaries. If you call `webViewObject.SetTextZoom(100)` the font size should be fixed adequately.

**Comment by lutfianasari** [comment]
Thank you very much..
This is what I was looking for!
