### ISSUE TITLE
IPointerDownHandler.OnPointerDown called every frame

### ISSUE THREAD

**Issue by dpr3309** [gree/unity-webview#699]
Hi, I have a WebGl application in which I use the IPointerDownHandler, IPointerUpHandler interfaces to catch the user's click.
When testing an application just in a browser, the OnPointerDown method of the IPointerDownHandler interface is executed according to the unit's documentation - once by click. But when testing the same application in webview, the OnPointerDown method of the IPointerDownHandler interface is executed in every frame as long as there is a click. those. I made a counter that continuously increments as long as the screen is touched (this does not happen when testing the application in the browser).
What is the reason for this, and how can this be overcome?

**Comment by KojiNakamaru** [comment]
I created a minimum sample webgl app that rendered one sphere with the folloing behaviour.

```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;

public class TouchDetector : MonoBehaviour, IPointerDownHandler, IPointerUpHandler
{
    void Start()
    {
        Debug.Log("XXX Start");
    }

    void Update()
    {
        
    }

    public void OnPointerDown(PointerEventData pointerEventData)
    {
        Debug.Log("XXX Game Object Click in Progress");
    }

    public void OnPointerUp(PointerEventData pointerEventData)
    {
        Debug.Log("XXX No longer being clicked");
    }
}
```

By running this app in Chrome on Vankyo S7 (Android 9), I got the following console output through the inspector:

![image](https://user-images.githubusercontent.com/2645978/120780237-d838cc80-c562-11eb-824d-9da21e07aba9.png)

Please note `Game Object Click in Progress` was repeated. This occurred while I was touching the sphere. Therefore, I guess IPointerDownHandler works correctly on PC but not on Android, even for an ordinal mobile browser. As stated in https://docs.unity3d.com/2020.3/Documentation/Manual/webgl-input.html , unity's WebGL implementation doesn't formally support mobile devices so it might be better to utilize lower level APIs such as Input.touches as noted in the document.

**Comment by dpr3309** [comment]
Thank you
