### ISSUE TITLE
Problem with Width and Height screen when SetVisibility is false

### ISSUE THREAD

**Issue by josemgmz** [gree/unity-webview#701]
Hi,

I´m having problem when i start the WebViewObject with SetVisibility is set to false when page is loading. 

I´m loading a game inside the WebView this game takes the the width and height of the screen at the init and use it to setup a HTML5 canvas.

So what happen is this.

1. First i create the Webview.
2. Call SetVisibility(false) during the init of the webview (hidding the webview before the HTML5 page load).
3. After my HTML5 game send me a message saying that the game preload all the assets, i call SetVisibility(true), and my screen looks like this:

![Screenshot_2021-06-17-12-30-42-20_6bba71588efe4695dff9ee641a8f69e9](https://user-images.githubusercontent.com/23422849/122381706-82542380-cf69-11eb-812c-742c06174bd7.jpg)

If i check with chrome inspect the width and height are not right.

![Screenshot 2021-06-17 at 12 45 21](https://user-images.githubusercontent.com/23422849/122383045-c3990300-cf6a-11eb-92c7-e7708001ad71.png)

But if a change SetVisibility(false) to SetVisibility(true) in the init of Webview (lets say never hide the webview during the load of the HTML5 game) looks like this (good):

![Screenshot_2021-06-17-12-32-43-98_6bba71588efe4695dff9ee641a8f69e9](https://user-images.githubusercontent.com/23422849/122383922-85e8aa00-cf6b-11eb-89aa-8252b425ee13.jpg)

There is any way to fix this?

 One alternative i had tested is:

1. First i create the Webview.
2. Call SetVisibility(true) during the init of the webview.
3. When event CallOnStarted[{0}] is fire i call SetVisibility(false);
4. When my HTML5 game have loaded all assets i call  SetVisibility(true);

And game width and height are ok, but between step 2 and 3 there is a black texture from Webview that im not able to hide.

i have try also this: #677 but still not working.

What im looking to achieve is start with a webview hide that have the correct width and height of my screen so after my game have loaded i can set the visibility to true and display my game.

is this possible?

Thank in advance.

**Comment by josemgmz** [comment]
One alternative i had tested is:

1. First i create the Webview.
2. Call SetVisibility(true) during the init of the webview.
3. When event CallOnStarted[{0}] is fire i call SetVisibility(false);
4. When my HTML5 game have loaded all assets i call  SetVisibility(true);

And game width and height are ok, but between step 2 and 3 there is a black texture from Webview that im not able to hide.

What im looking to achieve is start with a webview hide that have the correct width and height of my screen so after my game have loaded i can set the visibility to true and display my game.

is this possible?

**Comment by KojiNakamaru** [comment]
One simple way could be to set the `transparent:` argument of `webViewObject.Init()` to `true`. The webview then becomes transparent intead of black. This could affect the performance of your html5 game though (for very old devices).

You could also solve the issue by setting negative margins. The following diff is for the sample app, in which the webview is initially placed outside the screen and is then shown by the trigger "prepared" sent from javascript.

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index e8aa466..7f819cb 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -37,6 +37,9 @@ public class SampleWebView : MonoBehaviour
         webViewObject.Init(
             cb: (msg) =>
             {
+                if (msg == "prepared") {
+                    webViewObject.SetMargins(0, 0, 0, 0);
+                }
                 Debug.Log(string.Format("CallFromJS[{0}]", msg));
                 status.text = msg;
                 status.GetComponent<Animation>().Play();
@@ -133,7 +136,7 @@ public class SampleWebView : MonoBehaviour
         // Add BASIC authentication feature (Android and iOS with WKWebView only) by takeh1k0 · Pull Request #570 · gree/unity-webview
         //webViewObject.SetBasicAuthInfo("id", "password");
 
-        webViewObject.SetMargins(5, 100, 5, Screen.height / 4);
+        webViewObject.SetMargins(0, -Screen.height, 0, Screen.height);
         webViewObject.SetTextZoom(100);  // android only. cf. https://stackoverflow.com/questions/21647641/android-webview-set-font-size-system-default/47017410#47017410
         webViewObject.SetVisibility(true);
 
diff --git a/sample/Assets/StreamingAssets/sample.js b/sample/Assets/StreamingAssets/sample.js
index 8dc3fc4..e978664 100644
--- a/sample/Assets/StreamingAssets/sample.js
+++ b/sample/Assets/StreamingAssets/sample.js
@@ -7,6 +7,7 @@ window.addEventListener(
                 document.body.style.backgroundColor = '#ABEBC6';
                 var msg = document.getElementById("msg");
                 msg.textContent = '(NOTE: the background color was changed by sample.js, for checking whether the external js code works)';
+                Unity.call("prepared");
             },
-            3000);
+            10000);
     });
```

**Comment by josemgmz** [comment]
Hi Thank for your reply, setting negative margins works for me.

Regarts!
