### ISSUE TITLE
No sound when using WKWebView on iOS  - MediaPlayback Error

### ISSUE THREAD

**Issue by josemgmz** [gree/unity-webview#703]
Hello,

I'm continuing with my project of using HTML5 games inside the WKWebView on iOS, the problem I'm having is that I have no sound when I'm inside the webview.

1. I start the webview.
2. When I finish loading and start the game, I have no sound.

In the console from safari there are no error logs, but inside XCode I have the following errors:

`[752:109198] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}>`

`[752:109198] [ProcessSuspension] 0x119fdf8d0 - ProcessAssertion: Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' for process with PID 754, error: Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}`

`[752:109198] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}>`

`[752:109198] [ProcessSuspension] 0x119fdf900 - ProcessAssertion: Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' for process with PID 752, error: Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing}`

I have seen that inside the WebView.mm file you have this:

`if (@available(iOS 10.0, *)) 
{
            configuration.mediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypeNone;
} `

From what I've been able to read it should be enough, however I'm still having the problem.

You can reproduce this error by setting in the WebView script from unity editor Url to: http://phaser.io/examples/v2/audio/sound-complete and if you click on Blaster, Explosion or Sword it should sound but it wont work, you will see the error logs in XCode.

Thank in advance.

**Comment by KojiNakamaru** [comment]
There are a lot of posts about this issue but unfortunately I could not find any adequate answer. As discussed in the following,

https://github.com/youtube/youtube-ios-player-helper/issues/401

for http://phaser.io/examples/v2/audio/sound-complete those messages occurred but audio was played on my iPhone SE 2nd gen/iOS 14.6, if the mute switch was off (BTW, UIWebView/WKWebView didn't follow the mute switch before, maybe when iOS version was 11).

**Comment by josemgmz** [comment]
Hi @KojiNakamaru,

After checking on my iPhone 8 with iOS 14.4.2. when mute switch is enable i'm not able to play any sound on the WKWebview and when the mute switch is disable i'm able to play sounds emitted from my HTML5 games.

I want to ignore hardware silent switch on iOS, and play the sounds even when the mute switch is enable.

I was checking this solution from this post: https://stackoverflow.com/questions/56460362/how-to-force-wkwebview-to-ignore-hardware-silent-switch-on-ios

But i couldn't find a way to implement it in the code, do you have any idea how can i ignore the hardware silent? is something that in our old app using Cordova-WKWebview does and would be amazing to have here also.

Regards!

**Comment by KojiNakamaru** [comment]
Thank you for the interesting post. Its core logic utilizes only javascript so it can be implemented with EvaluateJS(). The following diff seems to work okay on my iPhone.

```diff
diff --git a/plugins/WebViewObject.cs b/plugins/WebViewObject.cs
index 6170e2f..0284d59 100644
--- a/plugins/WebViewObject.cs
+++ b/plugins/WebViewObject.cs
@@ -79,6 +79,39 @@ public class WebViewObject : MonoBehaviour
     bool hasFocus;
 #elif UNITY_IPHONE
     IntPtr webView;
+    // cf. https://stackoverflow.com/questions/56460362/how-to-force-wkwebview-to-ignore-hardware-silent-switch-on-ios/56460400#56460400
+    string silenceMono56kbps100msBase64Mp3 = "data:audio/mp3;base64,//tAxAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAFAAAESAAzMzMzMzMzMzMzMzMzMzMzMzMzZmZmZmZmZmZmZmZmZmZmZmZmZmaZmZmZmZmZmZmZmZmZmZmZmZmZmczMzMzMzMzMzMzMzMzMzMzMzMzM//////////////////////////8AAAA5TEFNRTMuMTAwAZYAAAAAAAAAABQ4JAMGQgAAOAAABEhNIZS0AAAAAAD/+0DEAAPH3Yz0AAR8CPqyIEABp6AxjG/4x/XiInE4lfQDFwIIRE+uBgZoW4RL0OLMDFn6E5v+/u5ehf76bu7/6bu5+gAiIQGAABQIUJ0QolFghEn/9PhZQpcUTpXMjo0OGzRCZXyKxoIQzB2KhCtGobpT9TRVj/3Pmfp+f8X7Pu1B04sTnc3s0XhOlXoGVCMNo9X//9/r6a10TZEY5DsxqvO7mO5qFvpFCmKIjhpSItGsUYcRO//7QsQRgEiljQIAgLFJAbIhNBCa+JmorCbOi5q9nVd2dKnusTMQg4MFUlD6DQ4OFijwGAijRMfLbHG4nLVTjydyPlJTj8pfPflf9/5GD950A5e+jsrmNZSjSirjs1R7hnkia8vr//l/7Nb+crvr9Ok5ZJOylUKRxf/P9Zn0j2P4pJYXyKkeuy5wUYtdmOu6uobEtFqhIJViLEKIjGxchGev/L3Y0O3bwrIOszTBAZ7Ih28EUaSOZf/7QsQfg8fpjQIADN0JHbGgQBAZ8T//y//t/7d/2+f5m7MdCeo/9tdkMtGLbt1tqnabRroO1Qfvh20yEbei8nfDXP7btW7f9/uO9tbe5IvHQbLlxpf3DkAk0ojYcv///5/u3/7PTfGjPEPUvt5D6f+/3Lea4lz4tc4TnM/mFPrmalWbboeNiNyeyr+vufttZuvrVrt/WYv3T74JFo8qEDiJqJrmDTs///v99xDku2xG02jjunrICP/7QsQtA8kpkQAAgNMA/7FgQAGnobgfghgqA+uXwWQ3XFmGimSbe2X3ksY//KzK1a2k6cnNWOPJnPWUsYbKqkh8RJzrVf///P///////4vyhLKHLrCb5nIrYIUss4cthigL1lQ1wwNAc6C1pf1TIKRSkt+a//z+yLVcwlXKSqeSuCVQFLng2h4AFAFgTkH+Z/8jTX/zr//zsJV/5f//5UX/0ZNCNCCaf5lTCTRkaEdhNP//n/KUjf/7QsQ5AEhdiwAAjN7I6jGddBCO+WGTQ1mXrYatSAgaykxBTUUzLjEwMKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg==";
+
+    void disableIgnoreSilentSwitch()
+    {
+        Debug.Log("disableIgnoreSilentSwitch()");
+        EvaluateJS("document.getElementById('wkwebviewAudio').src=null;");
+    }
+
+    void forceIgnoreSilentHardwareSwitch(bool initialSetup)
+    {
+        Debug.Log($"forceIgnoreSilentHardwareSwitch({initialSetup})");
+        if (initialSetup)
+        {
+            EvaluateJS($"var s=new Audio('{silenceMono56kbps100msBase64Mp3}');s.id='wkwebviewAudio';s.controls=false;s.loop=true;s.play();document.body.appendChild(s)");
+        }
+        else
+        {
+            EvaluateJS($"var s=document.getElementById('wkwebviewAudio');s.src=null;s.parentNode.removeChild(s);s=null;s=new Audio('{silenceMono56kbps100msBase64Mp3}');s.id='wkwebviewAudio';s.controls=false;s.loop=true;s.play();document.body.appendChild(s)");
+        }
+    }
+
+    void OnApplicationPause(bool paused)
+    {
+        if (paused)
+        {
+            disableIgnoreSilentSwitch();
+        }
+        else
+        {
+            forceIgnoreSilentHardwareSwitch(false);
+        }
+    }
 #elif UNITY_ANDROID
     AndroidJavaObject webView;
     
@@ -879,6 +912,9 @@ public class WebViewObject : MonoBehaviour
 
     public void CallOnLoaded(string url)
     {
+#if !UNITY_EDITOR && UNITY_IPHONE
+        forceIgnoreSilentHardwareSwitch(true);
+#endif
         if (onLoaded != null)
         {
             onLoaded(url);
```

**Comment by josemgmz** [comment]
Thank you it works!!

**Comment by ArnauKokoro** [comment]
Hi @KojiNakamaru !!

We are trying to force iOS sound when the unity app starts apart from the webview force that you tell us on your last comment.

For that we created a file MyUnityAppController.mm with this:

`#import "UnityAppController.h"
#import "AVFoundation/AVFoundation.h"
 
@interface MyUnityAppController: UnityAppController {}
 
-(void)setAudioSession;
 
@end
 
@implementation MyUnityAppController
 
-(void) startUnity: (UIApplication*) application
{
    NSLog(@"MyUnityAppController startUnity");
    [super startUnity: application];  //call the super.
    [self setAudioSession];
}
 
- (void)setAudioSession
{
    NSLog(@"MyUnityAppController Set audiosession");
    AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    [audioSession setCategory:AVAudioSessionCategoryPlayback error:nil];
    [audioSession setActive:YES error:nil];
}
 
@end
 
IMPL_APP_CONTROLLER_SUBCLASS(MyUnityAppController)`

The problem now is that there should be some conflicts between this and the webview force because the webview is not working.

Do you know what can it be?

If we remove the MyUnityAppController.mm file, it works. But we need that file to force the sound on the unity app.

We have tried remove this call forceIgnoreSilentHardwareSwitch(true) and this method OnApplicationPause(bool paused), but does not work.

Many Thanks!

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/732#issuecomment-913722353
