### ISSUE TITLE
Android 12 ベータ版での挙動について

### ISSUE THREAD

**Issue by achiral-dev** [gree/unity-webview#708]
お世話になります。
Android 12  ベータ版を入れた端末でサンプルが落ちてしまうようです。
ベータ版が原因の可能性も高そうですが市場のアプリも落ちてしまうため、念のため共有させて頂きます。

端末：Google Pixel 4a
OS：S（ビルド番号が SPB2.210513.011 で、Android 12 Beta 2.1 のようです）

ログで
E WebViewFactory: Chromium WebView package does not exist
が出ていたので開発者設定を確認したところ、「WebView の実装」が「なし」になっていました。

正式版では正しく動作するのかもしれませんし、Android 12 から何か仕組みが変わるのかもしれませんが
その辺り存じ上げていないので、取り急ぎご報告させて頂きました。

**Comment by KojiNakamaru** [comment]
情報ありがとうございます。そうですね、ベータ版での問題だと思います。次に回避方法なども含め、論じられているようです:
https://9to5google.com/2021/06/07/if-apps-keep-crashing-w-android-12-beta-webview-might-be-the-issue/

**Comment by achiral-dev** [comment]
暫定的な回避策が記載されているものの、正式には Android OS 側の対応を待つ方向のようですね。
ご確認と情報共有をありがとうございました。

**Comment by achiral-dev** [comment]
暫定的な回避策が記載されているものの、正式には Android OS 側の対応を待つ方向のようですね。
ご確認と情報共有をありがとうございました。
※一旦 Close とさせて頂こうと思います
