### ISSUE TITLE
Support for .Net Standard 2.0

### ISSUE THREAD

**Issue by adityathoutam** [gree/unity-webview#715]
I have recently updated the plugin, I have noticed that the type `dynamic` has been added in `UnityWebViewPostprocessBuild.cs`.  Dynamic type is only supported in .NET 4.x.
Can something be done to stay in .Net Standard 2.0? Unity complier throws this error when switched to .Net Standard 2.0
`Missing compiler required member Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create`

**Comment by KojiNakamaru** [comment]
At least for recent Unity versions, `dynamic` can be utilized in editor script even if API Compatibility Level is set to .NET 2.0. Anyway I modified UnityWebViewPostprocessBuild.cs not to utilize `dynamic` in #717 and updated binaries. Could you please try the latest?

**Comment by adityathoutam** [comment]
I'm using latest 2020 LTS version for reference. It throws this exact error in .NET 2.0 `Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs(104,13): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'`
#717 has removed the error.

**Comment by KojiNakamaru** [comment]
Thank you for the information. Hmm, I can reproduce the same error if I use 2018.4.32f1 and set "Scripting Runtime Version" to " .NET 3.5 Equivalent", but I cannot if I use 2020.3.14f1 (it has no "Scripting Runtime Version" option).

**Comment by adityathoutam** [comment]
I am able to reproduce in 2020.3.15f1 by changing  Api Compatibility Level in Other Settings section under Android Tab of Project Settings.

**Comment by KojiNakamaru** [comment]
There is no 2020.3.15f1 on https://unity3d.com/get-unity/download/archive but by googling I found https://unity3d.com/unity/whats-new/2020.3.15 that returns 403 now. Something wrong might happen in their release process.

Can you reproduce the issue for the sample app? The sample app's "Api Compatibility Level" is ".NET Standard 2.0" and I cannot reproduce the issue. If you can, could you please archive that `sample` folder and attach it?

**Comment by adityathoutam** [comment]
Yeah looks like Unity took down 2020.3.15.
Anyway here are the steps to reproduce
1. Download sample project
2. Open Package Manager and add no fragment variant of the package from the disk
3. Make sure to download dist packages before #717 fix
4. Manifest will be updated to show 
 "net.gree.unity-webview": "file:/Users/Username/Projects/unity-webview/dist/package-nofragment", 
5. Error in the console, when package is imported 

I have attached the project, it won't open straight away since it is expecting a local package. Ignore the errors and add package manually, to find the error

Sample Project
https://www.dropbox.com/s/z5fd79lxtdougwm/unity-webview.zip

package-nofragment before #717
https://www.dropbox.com/s/tr3cuywzrlmunzv/package-nofragment.zip?dl=0

**Comment by KojiNakamaru** [comment]
Thank you very much! I can now reproduce the issue. I could not before because I extracted unity-webview.zip and did not utilize Package Manager. Compilation for the code imported by Package Manager seems to be affected by the "Api Compatibility Level" setting.

**Comment by adityathoutam** [comment]
yeah looks like it.
I'm closing this issue since #717 fixed it, but it is something to watch out for in future.
Thanks for quick fix.
