### ISSUE TITLE
webViewWebContentProcessDidTerminate

### ISSUE THREAD

**Issue by NonSpicyBurrito** [gree/unity-webview#716]
As far as I can tell, `webViewWebContentProcessDidTerminate` is not implemented in iOS nor provided something of similar purpose.
Would it be implemented?
A very good use case of it is to detect when web view process terminated (commonly due to memory issues), and be able to manually restart it.

**Comment by KojiNakamaru** [comment]
Thanks, I added it in #718 and updated binaries. If it is triggered, `err:` should receive `webViewWebContentProcessDidTerminate`.
