### ISSUE TITLE
Unable to reload live url

### ISSUE THREAD

**Issue by leiweibo** [gree/unity-webview#72]
Look #51 is the same but the reporter had been resolved the issue, but I can not resolve this in my case. So I repost a new issue here.

In sample project, I just want to change the Url in the Inspector like "www.unity3d.com", but I can not open the web page in my webview component, but get an exception 

> IsolatedStorageException: Could not find a part of the path "/storage/emulated/0/Android/data/net.gree.webview.sample/files/http:/unity3d.com/".

I tried to remove the following that I webviewObject.loadUrl(url) to load the specify url directly. But get the issue I posted in #71 

> var src = System.IO.Path.Combine(Application.streamingAssetsPath, Url);
>       var dst = System.IO.Path.Combine(Application.persistentDataPath, Url);
>       var result = "";
>       if (src.Contains("://")) {
>         var www = new WWW(src);
>         yield return www;
>         result = www.text;
>       } else {
>         result = System.IO.File.ReadAllText(src);
>       }
>       System.IO.File.WriteAllText(dst, result);

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/71#issuecomment-218344289
