### ISSUE TITLE
no non-static method with name='Init' error

### ISSUE THREAD

**Issue by lutfianasari** [gree/unity-webview#724]
Hi, I got this error when webview is going to start.
I am using Unity 2019.2 and just updated this plugin with the latest code today.
My app was just waiting for the webview to be shown and nothing happened.
Does anyone have any clue for this error?

`E/Unity: AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='Init' signature='(Ljava/lang/String;ZZILjava/lang/String;)V' in class Ljava.lang.Object;
    java.lang.NoSuchMethodError: no non-static method with name='Init' signature='(Ljava/lang/String;ZZILjava/lang/String;)V' in class Ljava.lang.Object;
        at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:180)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0
`

**Comment by KojiNakamaru** [comment]
I tested the sample app with 2019.2.21f1 and it worked okay. I installed the plugin by extracting unity-webview.zip as the 2019.2.21f1 package manager could not handle https://github.com/gree/unity-webview.git?path=/dist/package (sorry, I should fix README.md later).

**Comment by lutfianasari** [comment]
Oh, I imported `dist/unity-webview.unitypackage` 
so maybe it was because Unity 2019.2 could not handle it, as you said.
Would you please explain what you mean :  installing the plugin by extracting unity-webview.zip?
I extracted unity-webview.zip, then should I just copy the file into plugin folder in my Unity project?

btw, thanks for the quick response.

**Comment by lutfianasari** [comment]
Sorry for my question above, I just didn't understand how.
I dragged and dropped the file under Plugin directory, but not all file (only WebViewPlugin.aar)
My error still existed, but it seemed it was caused by my mistake for not editing my build.graddle file after I exported Unity project to android studio.
 
I wrote 
`implementation files('libs/WebViewPlugin.jar')`
instead of
`implementation files('libs/WebViewPlugin.aar')`
in dependencies

So, it should be .aar (previous version of this plugin used .jar).
Thanks again for your help!

**Comment by KojiNakamaru** [comment]
unity-webview.zip is created from unity-webview.unitypackage so unity-webview.unitypackage is also okay.
Yes, the latest release contains WebView.aar instead of WebView.jar so you should delete WebView.jar if it exists and use WebView.aar instead.
