### ISSUE TITLE
Using EvaluateJS after page load is causing a crash

### ISSUE THREAD

**Issue by Ezzuna** [gree/unity-webview#727]
Apologies if I'm missing something obvious. This is a great plugin but I'm having an issue trying to run JS after the page has already loaded. 

The code I'm trying to run was taken from another issue related to blocking input:

>               webViewObject.EvaluateJS(@"
>                 (function() {
>                   var div = document.createElement('div');
>                   div.style.position = 'fixed';
>                   div.style.width = '100%';
>                   div.style.height = '100%';
>                   div.style.zIndex = 2147483647;
>                   document.body.insertBefore(div, document.body.firstChild);
>                 })();                
>                 ");

If I place this code in the onload (ld) callback, it works flawlessly. However if I create a custom callback or attempt to execute the code in a method inside the samplewebview class after load this causes my Android app to crash. 

I'm running a Samsung S21 on Android 11, Unity 2019.4.29f1.

Any help/guidance would be appreciated!

**Comment by Ezzuna** [comment]
After further exploration it's whenever I use webViewObject at all after page load (such as trying to use refresh() and clearcookies()) so I think I'm clearly making a mistake. Any guidance appreciated.

**Comment by KojiNakamaru** [comment]
Could you please provide a diff for the sample app that reproduces the issue?

**Comment by Ezzuna** [comment]
Hi, sorry for the long break. 

Here's the diff. I have commented out the GUI because my solution needs to not have it present. Any of the different ways of using webViewObject after load has completed is causing the app to crash. I should also note that the GUI was working before I commented it out. 

`                 IEnumerator Start()            
                                     {            
                    +                              
                                         webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();            
                                         webViewObject.Init(            
                                             cb: (msg) =>            
            
                                             hooked: (msg) =>            
                                             {            
                                                 Debug.Log(string.Format("CallOnHooked[{0}]", msg));            
                    +                        },            
                    +                        hostlock: (msg) =>            
                    +                        {            
                    +                          webViewObject.EvaluateJS(@"            
                    +                            (function() {            
                    +                              var div = document.createElement('div');            
                    +                              div.style.position = 'fixed';            
                    +                              div.style.width = '100%';            
                    +                              div.style.height = '100%';            
                    +                              div.style.zIndex = 2147483647;            
                    +                              document.body.insertBefore(div, document.body.firstChild);            
                    +                            })();                            
                    +                            ");            
                                             },            
                                             ld: (msg) =>            
                                             {            
                                                 Debug.Log(string.Format("CallOnLoaded[{0}]", msg));            
                    +                            //webViewObject.EvaluateJS(@"            
                    +                            //(function() {            
                    +                            //  var div = document.createElement('div');            
                    +                            //  div.style.position = 'fixed';            
                    +                            //  div.style.width = '100%';            
                    +                            //  div.style.height = '100%';            
                    +                            //  div.style.zIndex = 2147483647;            
                    +                            //  document.body.insertBefore(div, document.body.firstChild);            
                    +                            //})();                            
                    +                            //");            
                                 #if UNITY_EDITOR_OSX || (!UNITY_ANDROID && !UNITY_WEBPLAYER && !UNITY_WEBGL)            
                                                 // NOTE: depending on the situation, you might prefer            
                                                 // the 'iframe' approach.            
            
                                         // cf. https://github.com/gree/unity-webview/pull/512            
                                         // Added alertDialogEnabled flag to enable/disable alert/confirm/prompt dialogs. by KojiNakamaru · Pull Request #512 · gree/unity-webview            
                                         //webViewObject.SetAlertDialogEnabled(false);            
                    
                    
                    
                    
                                 
                                         // cf. https://github.com/gree/unity-webview/pull/550            
                                         // introduced SetURLPattern(..., hookPattern). by KojiNakamaru · Pull Request #550 · gree/unity-webview            
            
                                         // Add BASIC authentication feature (Android and iOS with WKWebView only) by takeh1k0 · Pull Request #570 · gree/unity-webview            
                                         //webViewObject.SetBasicAuthInfo("id", "password");            
                                 
                    +                    webViewObject.SetMargins(5, 5, 5, 5);            
                                         webViewObject.SetTextZoom(100);  // android only. cf. https://stackoverflow.com/questions/21647641/android-webview-set-font-size-system-default/47017410#47017410            
                                         webViewObject.SetVisibility(true);            
                                 
            
                                 #if !UNITY_WEBPLAYER && !UNITY_WEBGL            
                                         if (Url.StartsWith("http")) {            
                                             webViewObject.LoadURL(Url.Replace(" ", "%20"));            
                    +                        Debug.Log(Url.Replace(" ", "%20"));            
                                         } else {            
                                             var exts = new string[]{            
                                                 ".jpg",            
            
                                                     result = System.IO.File.ReadAllBytes(src);            
                                                 }            
                                                 System.IO.File.WriteAllBytes(dst, result);            
                    +                                        
                                                 if (ext == ".html") {            
                    +                                            
                                                     webViewObject.LoadURL("file://" + dst.Replace(" ", "%20"));            
                                                     break;            
                                                 }            
            
                                         }            
                                 #endif            
                                         yield break;            
                    +                }            
                    +            
                    +                public void HostRefresh()            
                    +                {            
                    +                    webViewObject.ClearCache(false);            
                    +                }            
                    +            
                    +                public void HostConnect(string url)            
                    +                {            
                    +                    webViewObject.ClearCache(false);            
                    +                    webViewObject.ClearCookies();            
                    +                    webViewObject.LoadURL(url);            
                    +                }            
                    +                public void LockInput(){            
                    +                              
                    +                        // webViewObject.EvaluateJS(@"            
                    +                        //     (function() {            
                    +                        //         x = 0;            
                    +                        //       })();            
                    +                        //     ");            
                    +                              
                    +                }            
                    +                            
                    +                public void CallOnHostlock(string message){            
                    +                  webViewObject.CallOnHostlock(message);            
                                     }            
                                 
                                     void OnGUI()            
                                     {            
                    +                    //var x = 10;            
                                 
                    +                    //GUI.enabled = webViewObject.CanGoBack();            
                    +                    //if (GUI.Button(new Rect(x, 10, 80, 80), "<"))            
                    +                    //{            
                    +                    //    webViewObject.GoBack();            
                    +                    //}            
                    +                    //GUI.enabled = true;            
                    +                    //x += 90;            
                                 
                    +                    //GUI.enabled = webViewObject.CanGoForward();            
                    +                    //if (GUI.Button(new Rect(x, 10, 80, 80), ">"))            
                    +                    //{            
                    +                    //    webViewObject.GoForward();            
                    +                    //}            
                    +                    //GUI.enabled = true;            
                    +                    //x += 90;            
                                 
                    +                    //if (GUI.Button(new Rect(x, 10, 80, 80), "r"))            
                    +                    //{            
                    +                    //    webViewObject.Reload();            
                    +                    //}            
                    +                    //x += 90;            
                                 
                    +                    //GUI.TextField(new Rect(x, 10, 180, 80), "" + webViewObject.Progress());            
                    +                    //x += 190;            
                                 
                    +                    //if (GUI.Button(new Rect(x, 10, 80, 80), "*"))            
                    +                    //{            
                    +                    //    var g = GameObject.Find("WebViewObject");            
                    +                    //    if (g != null)            
                    +                    //    {            
                    +                    //        Destroy(g);            
                    +                    //    }            
                    +                    //    else            
                    +                    //    {            
                    +                    //        StartCoroutine(Start());            
                    +                    //    }            
                    +                    //}            
                    
                    +                    //x += 90;            
                                 
                    +                    //if (GUI.Button(new Rect(x, 10, 80, 80), "c"))            
                    +                    //{            
                    +                    //    Debug.Log(webViewObject.GetCookies(Url));            
                    +                    //}            
                    +                    //x += 90;            
                                 
                    +                    //if (GUI.Button(new Rect(x, 10, 80, 80), "x"))            
                    +                    //{            
                    +                    //    webViewObject.ClearCookies();            
                    +                    //}            
                    +                    //x += 90;            
                                     }            
                                 }`

**Comment by KojiNakamaru** [comment]
This plugin does not have any `hostlock:` argument. I guess you are using some customized version of this plugin, for which I cannot reproduce the issue. Please also use the markdown notation adequately by referring https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code .

**Comment by Ezzuna** [comment]
Thank you for the link to documentation, hopefully this will be a bit clearer. To simplify things I've now removed any changes previously made when testing so my WebViewObject has no differences at all. The only difference to my SampleWebView is the function below. 
```
+    public void LockInput(){
+
+        webViewObject.EvaluateJS(@"
+                (function() {
+                  var div = document.createElement('div');
+                  div.style.position = 'fixed';
+                  div.style.width = '100%';
+                  div.style.height = '100%';
+                  div.style.zIndex = 2147483647;
+                  document.body.insertBefore(div, document.body.firstChild);
+                })();
+                ");
+
+    }  
```

I have a reference to my WebViewObject that is in the scene on my singleton object. It is receiving a command to call lockinput. From debugging I can see it is calling the function correctly but the app crashes with no useful feedback when running webViewObject.EvaluateJS. I've tested the same method with ClearCookies and others that all result in the same app crash. 
```
                case "HOSTLOCK":
                    
                    if(sampleWebView != null){
                        sampleWebView.LockInput();
                    }
                    break;
```

**Comment by KojiNakamaru** [comment]
The sample app with the following diff works without any issue. My environment is Unity 2019.4.29f1 and Vankyo S9 (Android 9).

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 56ad03f..1cb7b13 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -108,6 +108,7 @@ public class SampleWebView : MonoBehaviour
                     "};");
 #endif
                 webViewObject.EvaluateJS(@"Unity.call('ua=' + navigator.userAgent)");
+                LockInput();
             },
             //transparent: false,
             //zoom: true,
@@ -186,6 +187,20 @@ public class SampleWebView : MonoBehaviour
         yield break;
     }
 
+    public void LockInput()
+    {
+        webViewObject.EvaluateJS(@"
+                (function() {
+                  var div = document.createElement('div');
+                  div.style.position = 'fixed';
+                  div.style.width = '100%';
+                  div.style.height = '100%';
+                  div.style.zIndex = 2147483647;
+                  document.body.insertBefore(div, document.body.firstChild);
+                })();
+                ");
+    }  
+
     void OnGUI()
     {
         var x = 10;
```

Please also try to run the sample app as is at first. If it crashes, please try to use dist/unity-webview-nofragment.unitypackage which should be more stable than dist/unity-webview.unitypackage (cf. https://github.com/gree/unity-webview/tree/79e95933c8a39cfb022b676c25190603601f13e3#sample-project ).

**Comment by Ezzuna** [comment]
Hi,

Just wanted to add a resolution as I just picked this project up and was able to properly debug it. My issue was a threading issue. Interacting with the webViewObject via the Unity main thread solved it. 

Thanks for the help. This plugin is a great tool.
