### ISSUE TITLE
[Android and Start in fullscreen off only] Webview becomes smaller when the virtual keyboard is displayed.

### ISSUE THREAD

**Issue by R-A-77** [gree/unity-webview#729]
[Eng]
Dear owner,
Webview becomes smaller when the virtual keyboard is displayed.
The problem occurs when "Start in fullscreen mode" is off  in the player settings of unity.
This does not happen when “Start in fullscreen mode” is on.
Please let me know how to stop it from getting smaller.
Related Issues #300  ?

= Environment =
SHA-1 : 3ec19e9
OS : Android 11
Unity Settings : Player Settings(Android) -> Start in fullscreen mode off 
Source : SampleWebView.cs
Change Code : `webViewObject.SetMargins(0, 0, 0, 0);`
Remarks : Also occurs with Screen.fullscreen=false.
                 The reason for off the full screen is to show the navigation bar.

[JP]
お世話になっております。
Full Screen(off)の状態でキーボードを表示すると、
WebView部分がFull Screen(on)時と比べて小さくなってしまいます。
Navigation Barを常に表示したいため、FullScreen(off)で利用したいです。
何か回避方法はありますでしょうか？
関連Issues #300  ？

FullScreen_off_Android : 
<img src="https://user-images.githubusercontent.com/89342524/130355761-4a80da1c-1e36-43e8-b5ee-c3a7280ed08e.jpg" width="210">

FullScreen_on_Android : 
<img src="https://user-images.githubusercontent.com/89342524/130355762-f79ef502-f2a1-42ed-b537-751888eacf3d.jpg" width="210">

**Comment by KojiNakamaru** [comment]
Thank you for the report. I fixed the issue with #730 and updated binaries. Could you please try the latest?

ありがとうございます。#730で修正してバイナリを更新したので、最新版をおお試しいただけますか？

**Comment by R-A-77** [comment]
Dear @KojiNakamaru san
I confirmed #730 and the solution 7ce5342 .
When the full screen is off and the keyboard is displayed, the height of the screen is not smaller.
There was no problem with the solution 7ce5342 .
Verify OK. Thank you and Good solution !!!

お世話になっております。
ご確認とご対応して頂きありがとうございます。
#730 のソリューションは期待値通りに動作し、問題ございませんでした。
ありがとうございました。

FullScreen_off_Android_after_Fix(OK) : 
<img src="https://user-images.githubusercontent.com/89342524/130655988-f6ba63ee-3908-4a0f-9e9c-c5e4d7f89637.jpg" width="210">
