### ISSUE TITLE
Conflict Forcing Webview iOS sound and forcing Unity iOS App sound

### ISSUE THREAD

**Issue by ArnauKokoro** [gree/unity-webview#732]
Hi @KojiNakamaru !! Following this comment https://github.com/gree/unity-webview/issues/703#issuecomment-865454253

We are trying to force iOS sound when the unity app starts apart from the webview force that you tell us on your last comment.

For that we created a file MyUnityAppController.mm with this:

```
#import "UnityAppController.h"
#import "AVFoundation/AVFoundation.h"
 
@interface MyUnityAppController: UnityAppController {}
 
-(void)setAudioSession;
 
@end
 
@implementation MyUnityAppController
 
-(void) startUnity: (UIApplication*) application
{
    NSLog(@"MyUnityAppController startUnity");
    [super startUnity: application];  //call the super.
    [self setAudioSession];
}
 
- (void)setAudioSession
{
    NSLog(@"MyUnityAppController Set audiosession");
    AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    [audioSession setCategory:AVAudioSessionCategoryPlayback error:nil];
    [audioSession setActive:YES error:nil];
}
 
@end
 
IMPL_APP_CONTROLLER_SUBCLASS(MyUnityAppController)
```

The problem now is that there should be some conflicts between this and the webview force because the webview is not working.

Do you know what can it be?

If we remove the MyUnityAppController.mm file, it works. But we need that file to force the sound on the unity app. Also if we remove what you give us on the comment I refered to, it works too.

Many Thanks!

**Comment by KojiNakamaru** [comment]
WKWebView runs as a separated process and should have a separate AVAudioSession (though it is not clearly documented). This is perhaps the cause of the conflict. I searched a solution and found the following:

https://ionicframework.com/docs/v3/wkwebview/#configuring-avaudiosession-doesnt-affect-wkwebview

I tested the sample app with the following modifications and it seemed to work nicely.

* set Url to https://phaser.io/examples/v2/audio/sound-complete .
* attached one AudioSource to SampleWebView to automatically start playing some music.
* modified WebViewObject.cs by following https://github.com/gree/unity-webview/issues/703#issuecomment-865454253 .
* added the following at the end of `startUnity:`.

```objc
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord
                                     withOptions:AVAudioSessionCategoryOptionMixWithOthers
                                           error:nil];
    [audioSession setActive:YES error:nil];
```

**Comment by ArnauKokoro** [comment]
@KojiNakamaru Many Thanks!!

So, just changing `[audioSession setCategory:AVAudioSessionCategoryPlayback error:nil];` from MyUnityAppController.mm to `[audioSession setCategory:AVAudioSessionCategoryPlayback withOptions:AVAudioSessionCategoryOptionMixWithOthers error:nil];` made it works.

Note: with `[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionMixWithOthers error:nil];` makes the phone speaker (speaker for phone calls) make the sound instead of the external speaker, so it was sounding lower.

**Comment by salmaPTW** [comment]
Hi using above recommended file . One issue now I see is twitch stream is not audible after Webview returns from background
got any suggestions on this ?

**Comment by KojiNakamaru** [comment]
@salmaPTW 
Have you also included the code described in https://github.com/gree/unity-webview/issues/703#issuecomment-865454253 ?

**Comment by salmaPTW** [comment]
@KojiNakamaru  - No I haven't 
Found that twitch player audio is breaking (I see some audio errors from wkwebkit Media Playback)
