### ISSUE TITLE
hi, I use this unity-webview,but t can't open any url.Please help me,thanks.

### ISSUE THREAD

**Issue by jwgqp** [gree/unity-webview#74]

**Comment by KojiNakamaru** [comment]
If it happens on Unity Editor, please check https://github.com/gree/unity-webview#os-x-editor .

**Comment by jwgqp** [comment]
thanks very much,but i know only a few ios,my mac running in virtual system,ios simulator can't open any url, Is there any problem here?

**Comment by jwgqp** [comment]
thanks very much,but i know only a few ios,my mac running in virtual system,ios simulator can't open any url, Is there any problem here?
By the way, forgot to add one point:   unity for windows bulid ios

**Comment by KojiNakamaru** [comment]
Hmm, I've confirmed the `sample` at least runs on Simulator on MacBook Pro. My environemnt is

* OS X 10.11.4 (El Capitan)
* Xcode 7.3.1
* Simulator 9.3
* Unity 5.3.4p6

By specifying a url:

![image](https://cloud.githubusercontent.com/assets/2645978/15234752/e69d1b5c-18ef-11e6-83e6-8239ea25aee2.png)

and iOS build settings (especially `Target SDK` and `Allow downloads over HTTP` are important) as below:

![image](https://cloud.githubusercontent.com/assets/2645978/15234758/f177c0b8-18ef-11e6-92ff-0365e812273c.png)

the following is displayed:

![image](https://cloud.githubusercontent.com/assets/2645978/15234764/f8bbf646-18ef-11e6-9873-1ae3ddf75e5a.png)

**Comment by KojiNakamaru** [comment]
Please reopen the issue if you need any assistance further.
