### ISSUE TITLE
Frequently error on PlayConsole at. CWebViewPlugin.java:806

### ISSUE THREAD

**Issue by supermarsal** [gree/unity-webview#753]
I got at least 100 per week this error. The same highlighted row is at. CWebViewPlugin.java:806

![Screenshot_2021-12-09-05-23-39-683_com google android apps playconsole](https://user-images.githubusercontent.com/89568058/145299245-8606c1eb-b6d5-404b-ab4d-f3e72f4350a5.jpg)

**Comment by KojiNakamaru** [comment]
Thank you for the report. I tried to reduce the issue in #754 and updated binaries. Could you please try the latest?
Also, if you don't need to utilize the file input tag, it might be better to utilize  the nofragment version as discussed in https://github.com/gree/unity-webview/tree/7528d75e670cbf73b8b3fd5cb8872c06bf7128a3#sample-project .
