### ISSUE TITLE
Hide WebView alongside pausing it

### ISSUE THREAD

**Issue by h-shokri** [gree/unity-webview#756]
I'd like to pause the WebView whenever I set `WebViewObject.SetVisibility(false)` and resume whenever I show it again (on the condition that it was previously paused). This way I can stop playing video when I hide webview.
So far I've come up with these solutions:

1. Implement `WebViewObject.Pause()` and `WebViewObject.Resume()` which seems the best and flexible way. This way I can pause and resume whenever I want.
2. Make `WebViewObject.OnApplicationPause(bool paused)` **public** so I can call it myself to mimic pause and resume behavior.
3. Expose `WebViewObject.webView` (creating a public read-only property is greatly appreciated) so I can call `CWebViewPlugin.OnApplicationPause()` on the Android side by myself.

Any help would be appreciated.

**Comment by KojiNakamaru** [comment]
I introduced Pause()/Resume() in #757 and updated binaries. Could you please try the latest?

**Comment by h-shokri** [comment]
Yes it works like a charm.
Thanks for your help.
