### ISSUE TITLE
input file' is work ?

### ISSUE THREAD

**Issue by papapapapanda** [gree/unity-webview#76]
Using this plugin in Android 6.0 Nexus5
textfield works well, but input file button is not work.(do not lauch FileChooser)

does any get wrok html5 file input ?

**Comment by KojiNakamaru** [comment]
I've tried to make it work: https://github.com/gree/unity-webview/pull/77, but as noted, it is incomplete, especially there is no easy way to solve the 4.4.0-4.4.2 issue. It might be better to provide a simple button on HTML  for calling `Unity.call()` function instead and to treat anything you need in Unity/C#.
