### ISSUE TITLE
why  Scripting Define Symbols Deleted Script

### ISSUE THREAD

**Issue by hina9** [gree/unity-webview#760]
When modifying permission through Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs
PlayerSetting -> Player -> Scripting Define Symbols within Unity. My definition (UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC) disappears. why Will it be overridden?

**Comment by KojiNakamaru** [comment]
Maybe you set `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC` for Scripting Define Symbols in OSX tab, switched the platform to Android, and checked Scripting Define Symbols in Android tab.

**Comment by hina9** [comment]
No platform changes were made.
However, when the scripting definition symbol is deleted, the following pop-up window is created and then disappears. why?
'Do you want to apply changes?' 
'apply' 'revert' 'exit' All buttons are equally deleted.
Is there something wrong with my project?

![화면 캡처 2021-12-28 015255](https://user-images.githubusercontent.com/93582930/147491930-2651305d-1634-4536-b6bd-3271d7e60277.png)

**Comment by KojiNakamaru** [comment]
The "Apply" button of this dialog seems buggy on windows.

After inputting scripting define symbols, you need to push the "Apply" button. The dialog won't be shown if you push this "Apply" button.

![image](https://user-images.githubusercontent.com/2645978/147667807-5e901763-261a-4bf9-a602-a5ba7dbdadbf.png)

**Comment by hina9** [comment]
Thank you for answer.
