### ISSUE TITLE
your browser is not supported.

### ISSUE THREAD

**Issue by cief97** [gree/unity-webview#763]
I am using this package in order to access a URL.
I get the following pop up error message:
" Your browser is not supported, only safari is supported on IOS device. Chrome and Edge are supported on Android device. Safari, Chrome and Edge are supported on Mac. Chrome and Edge are supported on Windows. Chrome only on Linux. Open the link we sent you with the correct browser."

I already tried opening other URLs and it is working alright. Plus the following URL opens for like 1 second before displaying the message.

Any help is appreciated.

**Comment by KojiNakamaru** [comment]
You can specify any user agent with the `ua:` argument. In order to emulate iOS Safari, you can specify it as below:
```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 9c3409a..12b8372 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -35,6 +35,7 @@ public class SampleWebView : MonoBehaviour
     {
         webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
         webViewObject.Init(
+            ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1",
             cb: (msg) =>
             {
                 Debug.Log(string.Format("CallFromJS[{0}]", msg));
```

**Comment by cief97** [comment]
> 

In case of Android device and chrome what should the ua be?

**Comment by cief97** [comment]
Thanks it worked.

**Comment by cief97** [comment]
> You can specify any user agent with the `ua:` argument. In order to emulate iOS Safari, you can specify it as below:
> 
> ```diff
> diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
> index 9c3409a..12b8372 100644
> --- a/sample/Assets/Scripts/SampleWebView.cs
> +++ b/sample/Assets/Scripts/SampleWebView.cs
> @@ -35,6 +35,7 @@ public class SampleWebView : MonoBehaviour
>      {
>          webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
>          webViewObject.Init(
> +            ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1",
>              cb: (msg) =>
>              {
>                  Debug.Log(string.Format("CallFromJS[{0}]", msg));
> ```

Hello got a tiny new issue. the website needs camera and microphone permissions to be allowed and i need to fill out some fields but the keyboard isnt appearing when i try to.

**Comment by KojiNakamaru** [comment]
If your target is Android, you need to define several symbols and call some method: https://github.com/gree/unity-webview/tree/b0bd77c2430f555bc430b182e1c56fb5e8888c2a#cameraaudio-permissionfeature

**Comment by cief97** [comment]
And what about the on screen keyboard not appearing ?

**Comment by KojiNakamaru** [comment]
At least the sample app shows the keyboard for StreamingAssets/sample.html and/or google.com. Could you please provide a diff for the sample app that reproduces the issue?

**Comment by cief97** [comment]
i tried other websites but they all work (Google/ facebook/youtube). But when it comes down to my site it is different. A pop up message box appears in which there is an input field. i can paste in it but no keyboard is appearing
![Proof](https://user-images.githubusercontent.com/49907778/148910542-2e6389b7-2f1c-4dd6-aaf6-f37e7fc1097c.jpg)
.

**Comment by KojiNakamaru** [comment]
Can I access the site to further investigate the issue?

**Comment by cief97** [comment]
The site is actually a web app called acty: works close to how skype and zoom work. Here is the link for the free trial that i am using to join my call https://wbc.acty.com/wbc/?p=mcufa17vn11i2k9a   .  You will get redirected to the user license and privacy page.

![Screenshot_20220112-091111](https://user-images.githubusercontent.com/49907778/149081137-5de8d68e-0edd-40b4-a028-ea1d25bf9fbd.jpg)

after checking the checkboxes and hitting accept you will be redirected to the call.

![Screenshot_20220112-091117](https://user-images.githubusercontent.com/49907778/149081321-d95018f3-38b3-4637-9280-fc48d9b70415.jpg)
 
You can then cancel the call and you will be left with the following pop up input field. That's when i get my problem with the not showing of the on screen keyboard.

![Screenshot_20220112-091126](https://user-images.githubusercontent.com/49907778/149081562-af87ea17-ddab-46f6-b2bc-8a706c57fe89.jpg)

**Comment by KojiNakamaru** [comment]
I can reproduce the issue. It seems that the site cannot be browsed well with WebView. Although I tried several modifications found on the net for showing the software keyboard, none of them succeeded.

Instead, I would like to recommend you to utilize ChromeCustomTabs. It is much more compatible with the ordinal browser. You can find a very simple example under https://github.com/gree/unity-webview/tree/master/appendix/sample-sfsafariviewcontroller-chromecustomtabs. I've confirmed that it shows the software keyboard for the situation.

**Comment by cief97** [comment]
After a bit of tweeking, it worked. Thanksss!
