### ISSUE TITLE
iframeで表示しているwebサイトの操作をmsgとして取得することは可能ですか？

### ISSUE THREAD

**Issue by miyakeyuji** [gree/unity-webview#768]
現在、WebViewでLoadHTMLを使用し、HTMLを表示しているのですがその中にiframeで表示しなければならない部分があり、そのiframe内の特定のボタンを押したときにUnity側でそのボタンを押したときのイベントを検知したいのですが、可能なのでしょうか。  
可能でしたら、ご教授いただけますと助かります。  
試しに下記のような記述で試してみたのですが、うまくイベントを感知しログを出力するまで行けませんでした。

`            webViewObject.EvaluateJS(@"
                  window.Unity = {
                    call: function(msg) {
                      var iframe = document.createElement('IFRAME');
                      iframe.setAttribute('src', 'unity:' + msg);
                      document.documentElement.appendChild(iframe);
                      iframe.parentNode.removeChild(iframe);
                      iframe = null;
                    }
                  }
                ");`

**Comment by miyakeyuji** [comment]
補足ですが、Iframeで表示しているサイトのイベントを感知したいボタンにはjsのファンクションを設定し、ファンクション内でunity.call()を呼び出してもらっていてもできませんでした。

**Comment by KojiNakamaru** [comment]
iframeの中はWebViewで表示されているhtmlと別の世界なので、unity-webviewの諸々の機能を動かすのは難しいと思います。iframeのコンテンツを編集できるのであれば、

1. iframeでイベントを検知
1. イベントをpostMessage()でiframeの親に送信
1. 親は受け取った内容に応じてUnity.call()を呼び出す

ということをすればよいと思います。postMessage()については次などをご参照ください。

https://qiita.com/TakamiChie/items/aaa435be2ca08ecdcb61

**Comment by KojiNakamaru** [comment]
また、同一ドメインであればですが、次のようなファイルを用意して、sample.htmlをunity-webviewで開くと、iframe.htmlのボタンを押した時、Unity.call()を呼び出すことができます。

sample.html:
```html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>sample</title>
    <script>
      if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl) {
          window.Unity = {
              call: function(msg) {
                  window.webkit.messageHandlers.unityControl.postMessage(msg);
              }
          }
      }
    </script>
  </head>
  <body>
    <h1>sample</h1>
    <hr/>
    <iframe src="iframe.html">
    </iframe>
  </body>
</html>
```

iframe.html:
```html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>iframe</title>
    <script>
      function clicked() {
          window.parent.Unity.call("Pushed");
      }      
    </script>
  </head>
  <body>
    <h1>iframe</h1>
    <hr/>
    <button type="button" onclick="clicked()">Button</button>
  </body>
</html>
```

**Comment by miyakeyuji** [comment]
ご回答いただきありがとうございます。

実装についても少々教えて頂きたいのですが

Iframeで表示しているコンテンツには下記のように実装しております
`<button
  onClick={e => {
    console.log("PostMessage");
    window.parent.postMessage("testMessage", "*");
  }}
>
  PostMessage
</button>`

Unity側では、EvaluteJSを使用し下記のようにJSをWindowのEventListenerに登録しようとしております
`webViewObject.EvaluateJS(@"
     window.addEventListener('message', function(e)
     {
         if( 'message' == 'testMessage' )
         unity.call('test');
     });
 ");`

というように実装をしてみたのですが、うまく動作いたしません。
こちら何か問題がございますのでしょうか。

**Comment by KojiNakamaru** [comment]
いくつか間違っているようなので、整理したサンプルを次に書きます。こちらを確認してみてください。

sample.html:
```html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>sample</title>
    <script>
      if (window && window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.unityControl) {
          window.Unity = {
              call: function(msg) {
                  window.webkit.messageHandlers.unityControl.postMessage(msg);
              }
          }
      }
      window.addEventListener(
          'message',
          function(e) {
              if (e.data == 'testMessage') {
                  Unity.call('test')
              };
          });
    </script>
  </head>
  <body>
    <h1>sample</h1>
    <hr/>
    <iframe src="iframe.html">
    </iframe>
  </body>
</html>
```

iframe.html:
```html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>iframe</title>
    <script>
      function clicked() {
          window.parent.postMessage("testMessage", "*");
      }      
    </script>
  </head>
  <body>
    <h1>iframe</h1>
    <hr/>
    <button type="button" onclick="clicked()">PostMessage</button>
  </body>
</html>
```

**Comment by miyakeyuji** [comment]
サンプルを用意してくださり、ありがとうございます！
サンプルのコードに合わせて実装したところ無事にIframe先からメッセージを受け取ることができました！
初歩的なところも含めご教授いただきありがとうございました！
