### ISSUE TITLE
Change the url

### ISSUE THREAD

**Issue by pbgame55** [gree/unity-webview#775]
I'm trying to change the webviev url in my 2nd scene with the help of buttons in my 1st scene. When I check it on Unity, the url changes, but when I try it on an android phone, the url does not change and the google page opens every time. What can I do about it? Thank you.

`       
public GameObject screen;

    void Start()
    {
        string url1 = PlayerPrefs.GetString("url");
        SampleWebView example = new SampleWebView();
        example.Url = url1;
     }

    public void Choose1()
    {
        string url1 = "https://www.youtube.com/xxxxxxxx";
        PlayerPrefs.SetString("url", url1);
      screen.GetComponent<SampleWebView>().Url= "https://www.youtube.com/xxxxxxx";
    }
    public void Choose2()
    {
        string url1 = "https://www.youtube.com/yyyyyy";
        PlayerPrefs.SetString("url", url1);
        screen.GetComponent<SampleWebView>().Url = "https://www.youtube.com/yyyyy";
    }`

**Comment by KojiNakamaru** [comment]
Could you please provide a complete project that reproduces the issue? You can attach a zip file to this issue or create a repository on github.

**Comment by pbgame55** [comment]
I will do this as soon as possible. My resources are limited right now. But I can say this: the url set in the first place is always valid, the url does not change. I can see that the url has changed on the Unity inspector, but on mobile the url does not change at all.
