### ISSUE TITLE
Size problem for mobile view

### ISSUE THREAD

**Issue by kolibaba** [gree/unity-webview#776]
If select a vertical screen layout (mobile device is selected in NoxPlayer settings, for example 1080*1920), WebView occupies only part of the screen.
Margins were set to zero: `webViewObject.SetMargins(0, 0, 0, 0);`
Is it trouble with NoxPlayer or with webView? And Can i fix it?
![Untitled](https://user-images.githubusercontent.com/2988196/152165425-17fec845-af53-4d0c-b829-094211c25da5.png)
.

**Comment by KojiNakamaru** [comment]
At least the sample app whose orientation is set to Portrait seems to run without any issue. My environment is: Unity 2020.3.25f1, noxplayer v7.0.2.1, Windows 10.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/2645978/152360498-5b3e7c6f-bd2f-49ce-bc90-3a4f69dee2b3.png">

**Comment by kolibaba** [comment]
how did you do the portrait orientation? I can't do i by settings
![Untitled2](https://user-images.githubusercontent.com/2988196/152511157-e25209b7-0b37-43f0-9809-d78726b717d2.png)
t

**Comment by KojiNakamaru** [comment]
You can specify "Allowed Orientation for Auto Rotation" in Unity's Project Settings.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/2645978/152565682-a975b74a-1a3d-428e-a263-ea8c48876606.png">

**Comment by kolibaba** [comment]
Thanks a lot!
