### ISSUE TITLE
Bad Path Formatting for info.plist

### ISSUE THREAD

**Issue by alexpoolton** [gree/unity-webview#78]
Running the sample.unity scene I get the following error (the whitespace isn't handle correctly).

DirectoryNotFoundException: Could not find a part of the path "/Applications/Unity%205.3.5f1/Unity.app/Contents/Info.plist".

**Comment by KojiNakamaru** [comment]
Thank you for your report. I've fixed it in https://github.com/gree/unity-webview/pull/79, so could you please try the latest.
