### ISSUE TITLE
always opens google

### ISSUE THREAD

**Issue by MegaTheLEGEND** [gree/unity-webview#782]
no matter what i put in the url field in unity it takes me back to google.

**Comment by KojiNakamaru** [comment]
Please provide more details to reproduce the issue. At least the sample app works without any issue:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/2645978/156079159-7b212e9a-4c99-482c-b7be-8df1f13872bd.png">

**Comment by MegaTheLEGEND** [comment]
it turns out it was something i did. you are correct the sample is working.

thanks!

**Comment by MegaTheLEGEND** [comment]
how would i make the embedded site be in desktop mode instead of mobile?

**Comment by KojiNakamaru** [comment]
You can build a standalone player where the content can be placed under StreamingAssets and will be copied at runtime:

https://github.com/gree/unity-webview/blob/e428cefb3f207365e1cdc330fe32c6ed4420beeb/sample/Assets/Scripts/SampleWebView.cs#L155-L196

Please note, however, the implementation is only for osx and is rather intended for debugging. You may need to check other more complete solutions:

https://github.com/gree/unity-webview/issues/586#issuecomment-680917028
