### ISSUE TITLE
Won't show Google Recaptcha

### ISSUE THREAD

**Issue by UnityStefan** [gree/unity-webview#799]
First of all, thank you for creating this plug-in, it really helped me out.

I'm using Unity 2019.4.15f1 and developing for iOS (and I'm going to use your plugin for Android too for the same project).
Everything works as it should, webpages are showing and everything but I'm having a problem with showing Recaptcha popup on the sign-in page that I'm opening. I see in the console that "CallOnStarted" started with the Recaptcha link but nothing happens/loads on the screen.

Edit:
Just to point out, when I add "separated: true", the Recaptcha works on created separated window.

Can you help me with this?
Thank you once again!

**Comment by KojiNakamaru** [comment]
The implementation for the editor is tricky one and may have various issues (for example, it cannot render Youtube movies). It is rather for debugging and the separated mode is less problematic. I've confirmed that https://www.google.com/recaptcha/api2/demo at least runs okay on Android 9 (Vankyo S7) and on iOS 15.4.1 (iPhone SE 2nd).

**Comment by UnityStefan** [comment]
Thank you very much for your response and for taking your time.

I understand, with the separated mode it's debuggable so it's not that big of a deal. Also, I can confirm that on iPhone 8 ReCaptcha works.

Thanks once again and wish you all the best!
