### ISSUE TITLE
Sending Url to Other Clients at Runtime

### ISSUE THREAD

**Issue by pbgame55** [gree/unity-webview#800]
Hello, I am developing an application for android and ios that allows users to surf the internet together using this plugin. In addition, photon has been integrated into the application. In a multiplayer game, I want the masterclient to send the url currently valid for the masterclient to other players when masterclient press a button, and return the same url on each player's screen. Can you help me on how to do this? 
I tried this but it didn't work, result : every user still persists with the url(google) set at start()

     

    [PunRPC]public void set( string masterValue)
          {
		masterValue = Url;
	  //  webViewObject.LoadURL(Url);	
	}
	
    public	void sendurl()
    {

		if (PhotonNetwork.IsMasterClient)
		{
			
			var masterValue = Url;
			photonView.RPC("set", RpcTarget.OthersBuffered, masterValue);
			set(masterValue);
			Debug.Log("urlne?" + masterValue);
			
		}
	}

**Comment by KojiNakamaru** [comment]
What are you trying to do in the following?

```c#
[PunRPC]public void set( string masterValue)
      {
	masterValue = Url;
  //  webViewObject.LoadURL(Url);	
}
```

This doesn't change `Url`. Also, setting `Url` only is not enough to load the corresponding page. You need to call `LoadlURL()` as below.

https://github.com/gree/unity-webview/blob/68b94c8c050a28288be2871e86f404405313d7e3/sample/Assets/Scripts/SampleWebView.cs#L156-L158

**Comment by pbgame55** [comment]
public void sendurl()
      {
		if (PhotonNetwork.IsMasterClient)
		{
			var masterValue = Url;
	               Debug.Log(masterValue);
	               photonView.RPC("set", RpcTarget.OthersBuffered, masterValue);
	              set(masterValue);
		}
	 }

	[PunRPC]
	private void set(string masterValue)
	{
	
		Debug.Log(masterValue);
		Url = masterValue;
		if (masterValue.StartsWith("http"))
		{
			webViewObject.LoadURL(masterValue.Replace(" ", "%20"));
		}

	}	
         void Update()
	{	
			webViewObject.EvaluateJS("if (location) window.Unity.call('url:' + location.href);");	
	}


I'm testing on unity editor and mobile device simultaneously. When I change the url manually in the editor and press the sendurl() button, I can send the url to the mobile device and it opens on the mobile device. But when I go to any page from a mobile device and try to send the url, the url is still valid as "google" and is constantly redirected to the google page. I still can't get the current url when surfing any page. What should I do? 
I know I'm overwhelming you, this is really my last question, I appreciate your help :)

**Comment by KojiNakamaru** [comment]
How you define the callback? As you send the current location to the unity side on Update(), you should define the callback below adequately.

https://github.com/gree/unity-webview/blob/68b94c8c050a28288be2871e86f404405313d7e3/sample/Assets/Scripts/SampleWebView.cs#L37-L43

The following is an example modification for the sample app that should suit your requirements (though I've not tested it). The EvaluateJS() argument is a bit complicated to check Unity.call() is available and not to invoke redundant Unity.call()

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 9c3409a..f89c5bf 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -31,15 +31,39 @@ public class SampleWebView : MonoBehaviour
     public Text status;
     WebViewObject webViewObject;
 
+    [PunRPC]
+    void setUrl(string masterValue)
+    {
+        if (!PhotonNetwork.IsMasterClient) {
+            Url = masterValue;
+            webViewObject.LoadURL(Url.Replace(" ", "%20"));
+        }
+    }   
+
+    void Update()
+    {
+        webViewObject.EvaluateJS(@"
+if (typeof window.Unity != 'undefined') {
+  if (typeof last_location_href != 'undefined' || last_location_href != location.href) {
+    last_location_href = location.href;
+    window.Unity.call('url:' + location.href);
+  }
+}
+");	
+    }
+
     IEnumerator Start()
     {
         webViewObject = (new GameObject("WebViewObject")).AddComponent<WebViewObject>();
         webViewObject.Init(
             cb: (msg) =>
             {
-                Debug.Log(string.Format("CallFromJS[{0}]", msg));
-                status.text = msg;
-                status.GetComponent<Animation>().Play();
+                if (PhotonNetwork.IsMasterClient) {
+                    if (msg.StartsWith("url:")) {
+                        Url = msg.SubString(4);
+                        photonView.RPC("setUrl", RpcTarget.OthersBuffered, Url);
+                    }
+                }
             },
             err: (msg) =>
             {
```

> is constantly redirected to the google page.

There is no code to redirect to google.com at least in the sample app. I guess you have any code causing that issue, so please try to search google.com in your project.

**Comment by pbgame55** [comment]
Thank you very much, it worked.
