### ISSUE TITLE
Disable touch

### ISSUE THREAD

**Issue by durumed** [gree/unity-webview#802]
Many thanks for this plugin. I have a button in my game scene and I want to make sure that when I press this button, the user can no longer touch the webview screen.
#235 It doesn't work for me. Also even if I add a transparent image after the webview is loaded it has no effect, the user can still touch the screen. Will you help me with this problem?

**Comment by KojiNakamaru** [comment]
As you pointed out, the solution in #235 reasonably works but allows scrolling, etc., so I introduced SetInteractionEnabled() in #803 and updated binaries . You can allow/disallow user interaction by calling SetInteractionEnabled(true) /  SetInteractionEnabled(false). Could you please try the latest?

**Comment by durumed** [comment]
First of all, thank you again for your effort, I tried the latest, but I was not successful, although I did not get any errors. GUI buttons are working, when I press the button I can see if it is active by printing it to the console `    public void SetInteractionEnabled(bool enabled)
    {
        Debug.Log(enabled);
    }` I updated files but as I said I can still touch and control the screen. 

I installed this plugin in my unity account about 1 year ago and some of the latest features are not available in my files. Does the operation of SetInteractionEnabled() depend on any feature for properly run? Should I update all my files even if I don't need all the features? I'm trying to reason as I don't get any errors, sorry if what I'm saying is nonsense.

**Comment by KojiNakamaru** [comment]
You need to import the latest package as SetInteractionEnabled() is found only in the latest one. Once you imported, you can use it as below:

https://github.com/gree/unity-webview/blob/02f9d6534633ea7e76dab1b5f51fb088c400b610/sample/Assets/Scripts/SampleWebView.cs#L246-L254

The latest package contains several fixes and new features compared with the one you use, but basically it should be compatible. If you have any trouble with the latest package, please let me know.
