### ISSUE TITLE
EvaluateJS issue

### ISSUE THREAD

**Issue by brycepo** [gree/unity-webview#818]
Hi Koji,

Currently working on calling a function from unity to webivew using webViewObject.EvaluateJS.

I have a evaluate JS called 
         webViewObject.EvaluateJS("getParameters('Sample Store','Sample Store Description')");
but it is not being passed to the html
  function getParameters(storeName, storeDesc) {
    window.storeName = storeName;
    window.storeDesc = storeDesc;
  }

any ideas on what is the cause?

**Comment by KojiNakamaru** [comment]
At least the sample app with the following modification works. You might invoke EvaluateJS() before the html page is loaded.

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index 2dbe3cb..6ba0b51 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -252,5 +252,10 @@ public class SampleWebView : MonoBehaviour
             webViewObject.SetInteractionEnabled(true);
         }
         x += 90;
+
+        if (GUI.Button(new Rect(x, 10, 80, 80), "call")) {
+            webViewObject.EvaluateJS("getParameters('Sample Store','Sample Store Description')");
+        }
+        x += 90;
     }
 }
diff --git a/sample/Assets/StreamingAssets/sample.html b/sample/Assets/StreamingAssets/sample.html
index 38de86b..bafa7c5 100644
--- a/sample/Assets/StreamingAssets/sample.html
+++ b/sample/Assets/StreamingAssets/sample.html
@@ -16,6 +16,13 @@
         });
     </script>
     -->
+    <script>
+      function getParameters(storeName, storeDesc) {
+          window.storeName = storeName;
+          window.storeDesc = storeDesc;
+          document.getElementById("msg").textContent = storeName + ":" + storeDesc;
+      }
+    </script>
   </head>
   <body>
     <h1>Hello Unity WebView!</h1>
```

**Comment by brycepo** [comment]
Any idea on how to do it without using a button?

**Comment by KojiNakamaru** [comment]
EvaluateJS() can be called after the page is loaded. You can detect that the page is loaded with the `ld:` callback: https://github.com/gree/unity-webview/blob/master/sample/Assets/Scripts/SampleWebView.cs#L64-L66 .

**Comment by brycepo** [comment]
something like this?
ld: (msg) =>
            {
                webViewObject.EvaluateJS("getParameters('SreeHarry','Harry Store', '255','EUR', 'Customer Name', '#shopId')");
                Debug.Log(string.Format("CallOnLoaded[{0}]", msg));

**Comment by KojiNakamaru** [comment]
Yes.

**Comment by brycepo** [comment]
is it possible to send the date before showing the page? because the data that im passing using the evaluatejs is displayed in the page immediately after loading and it is resulting like this
![image](https://user-images.githubusercontent.com/22655404/177689680-4cbd7f36-830f-42bc-8634-89a934b3ca3e.png)

**Comment by brycepo** [comment]
got it its working already thank you so much koji!
