### ISSUE TITLE
Keyboard is not interactible

### ISSUE THREAD

**Issue by Neuyazvimyi** [gree/unity-webview#82]
My Manifest
`<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="preferExternal" package="APP_BUNDLE_ID" android:versionName="2.0" android:versionCode="2">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <uses-feature android:glEsVersion="0x00020000" />
  <uses-sdk android:minSdkVersion="9" android:targetSdkVersion="18" />
  <application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="false">
    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:launchMode="singleTask" android:screenOrientation="landscape" android:hardwareAccelerated="true">
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
</manifest>
`

**Comment by KojiNakamaru** [comment]
Recent Unity doesn't utilize `com.unity3d.player.UnityPlayerNativeActivity`. I guess it is because the native activity causes many issues while it doesn't lead any major performance gain. Could you please try to use recent Unity without your custom AndroidManifest.xml, or the following may fix the issue.

```diff
--- AndroidManifest.xml~	2016-06-19 01:51:17.000000000 +0900
+++ AndroidManifest.xml	2016-06-19 01:51:51.000000000 +0900
@@ -4,9 +4,8 @@
   <uses-feature android:glEsVersion="0x00020000" /> 
   <uses-sdk android:minSdkVersion="9" android:targetSdkVersion="18" /> 
   <application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="false"> 
-    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:launchMode="singleTask" android:screenOrientation="landscape" android:hardwareAccelerated="true"> 
+    <activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:launchMode="singleTask" android:screenOrientation="landscape" android:hardwareAccelerated="true"> 
       <meta-data android:name="unityplayer.UnityActivity" android:value="true" /> 
-      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" /> 
       <intent-filter> 
         <action android:name="android.intent.action.MAIN" /> 
         <category android:name="android.intent.category.LAUNCHER" /> 
```
