### ISSUE TITLE
Full screen WKWebView and notch safe-area-inset not working

### ISSUE THREAD

**Issue by theofournier** [gree/unity-webview#826]
Hi,

I am using your package to display a fullscreen WebView in my Unity game for iOS and Android.

For iOS, I am enabling **WKWebView**.

The website I am trying to load is handling the notch thanks to the [**env** variable](https://developer.mozilla.org/fr/docs/Web/CSS/env): `env(safe-area-inset)`

With the `viewport-fit: cover` tag.

In the Safari browser, it is working well, the website has a padding equal to the `env(safe-area-inset)`

But in the unity-webview **WKWebView**, the `env(safe-area-inset)` is equal to 0.

According to the [community](https://bubblin.io/blog/notch) Apple recommend using: `@supports(padding:max(0px)) { env() }` but still no success.

Also [recommending](https://ruoyusun.com/2020/10/21/webview-fullscreen-notch-Copy.html) setting `webview!.scrollView.contentInsetAdjustmentBehavior = .never` but that is already the case.

Do you have any idea how to solve this issue and make the `env(safe-area-inset)` working with **WKWebView**?

**NB**

The last [recommendation](https://newbedev.com/make-wkwebview-real-fullscreen-on-iphone-x-remove-safe-area-from-wkwebview) is overriding **safeAreaInset** of the webview: 

```
extension WKWebView {
    override open var safeAreaInsets: UIEdgeInsets {
        return UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
    }
}
```

I could not test it because it requires to updates the package and to rebuilt it.

You can test it with this HTML sample:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no,viewport-fit=cover"
    />

    <title>Test</title>

    <style>
      html,
      body {
        height: 100vh;
        width: 100vw;
        padding: 0;
        margin: 0;
        overflow: hidden;
      }
      .container {
        height: 100vh;
        background-color: black;
        padding-left: env(safe-area-inset-left);
        padding-right: env(safe-area-inset-right);
      }
      .content {
        height: 100vh;
        background-color: red;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="content">
        <p>TEST APP</p>
      </div>
    </div>
  </body>
</html>

```

**Comment by KojiNakamaru** [comment]
Although I don't have any iOS device with notch, the sample app with your test html seems to work okay on iPhone 13 simulator:

![image](https://user-images.githubusercontent.com/2645978/181720549-206ccbcc-b489-48ca-9503-479d53581fb4.png)

I use Unity 2020.3.34f1 for the sample app uploaded to https://github.com/gree/unity-webview/tree/example-for-826 . If I import the following diff,

```diff
--- Assets/Plugins/iOS/WebView.mm
+++ Assets/Plugins/iOS/WebView.mm
@@ -51,10 +51,16 @@ extern "C" void UnitySendMessage(const char *, const char *, const char *);
 @end
 
 @interface WKWebView(WebViewProtocolConformed) <WebViewProtocol>
+@property(nonatomic, readonly) UIEdgeInsets safeAreaInsets;
 @end
 
 @implementation WKWebView(WebViewProtocolConformed)
 
+- (UIEdgeInsets)safeAreaInsets
+{
+    return UIEdgeInsetsZero;
+}
+
 - (void)load:(NSURLRequest *)request
 {
     WKWebView *webView = (WKWebView *)self;
```

safe area insets are cleared and the following result occurs:

![image](https://user-images.githubusercontent.com/2645978/181724589-d7aa3101-5e02-44f7-ba7d-367e9cd6ef6f.png)

By the way, as the plugin's iOS version is provided in source code form, you can easily customize it. You can import the plugin by extracting dist/unity-webivew.zip and edit Assets/Plugins/iOS/WebView.mm.

**Comment by theofournier** [comment]
Hi @KojiNakamaru 

Thank you very much for your investigation and your quick reply.

I forgot to mention that it is working fine on simulator but not on real device, I could not find the reason why for now.

About the `safeAreaInset`, that is a good progress, it appears not be a solution.


About extracting the plugin, after editing the `WebView.mm` file, how can I use it in my Unity project?

**Comment by KojiNakamaru** [comment]
For iOS build, Assets/Plugins/iOS/WebView.mm will be automatically included in a Xcode project Unity emits, so your change will be directly reflected to the final app binary. If you export a Xcode project, you can find WebView.mm as Libraries/net.gree.unity-webview/Assets/Plugins/iOS/WebView.mm.

(To understand how to extract the plugin under your project, please check https://github.com/gree/unity-webview/tree/f45ce25f04dbdfab3d703eb06378937c837008d8#sample-project)

As `safeAreaInsets` seems to affect to `env(safe-area-inset-*)` at least on the simulator, the following change might reduce the issue:

```
diff --git a/plugins/iOS/WebView.mm b/plugins/iOS/WebView.mm
index 6ea47bf..67a6ea4 100644
--- a/plugins/iOS/WebView.mm
+++ b/plugins/iOS/WebView.mm
@@ -51,10 +51,17 @@ extern "C" void UnitySendMessage(const char *, const char *, const char *);
 @end
 
 @interface WKWebView(WebViewProtocolConformed) <WebViewProtocol>
+@property(nonatomic, readonly) UIEdgeInsets safeAreaInsets;
 @end
 
 @implementation WKWebView(WebViewProtocolConformed)
 
+- (UIEdgeInsets)safeAreaInsets
+{
+    //return UIEdgeInsetsZero;
+    return UnityGetGLViewController().view.safeAreaInsets;
+}
+
 - (void)load:(NSURLRequest *)request
 {
     WKWebView *webView = (WKWebView *)self;

```

where overridden `safeAreaInsets` returns its value of `UnityGetGLViewController().view`.

**Comment by theofournier** [comment]
So I have tested your Sample project on a real Device, and the `env(safe-area-insets)` is working fine without any changes.

But I don't know why it is not working on my project, I am initializing the `WebViewObject` as you and set the margin to 0. The GameObject is placed at the same place in the Editor than you.

My project is a bit complex to show you, but do you think of something that could make your WebView more fullscreen?

**Comment by theofournier** [comment]
So I found the issue, I was using a custom WebView library that has 
```
- (UIEdgeInsets)safeAreaInsets
{
    return UIEdgeInsetsZero;
}
```

enabled for real device and not simulator.

So there is no issue, sorry for the disturbance and thank you for your help
