### ISSUE TITLE
Code sign error

### ISSUE THREAD

**Issue by tim-hub** [gree/unity-webview#84]
> Error Domain=IDEFoundationErrorDomain Code=1

when I build the ipa, i got this error.

I read this https://support.gamesparks.net/support/discussions/topics/1000073793
the issue is from gamesparks,

I did not use gamesparks in the project, is it due to webview plugin? and how can I fix it?

 Hope your help, and thanks in advance.

**Comment by KojiNakamaru** [comment]
This plugin should not have any issue about code signing, at least I have no such experience. The following links might help.

http://stackoverflow.com/questions/36213831/presenting-error-domain-idefoundationerrordomain-code-1-failed-to-compile-bitc
http://stackoverflow.com/questions/32963264/export-ipa-error-on-xcode-7-in-el-capitan

**Comment by tim-hub** [comment]
you are right.
I am still working on it, although 2 links did not help, but thanks anyway.
