### ISSUE TITLE
Terminated due to memory issue

### ISSUE THREAD

**Issue by slugiscool99** [gree/unity-webview#844]
We're seeing a bug on iOS where, when the webview is active for a long period of time, the application crashes with `Failure Reason: Message from debugger: Terminated due to memory issue` and user info `IDERunOperationFailingWorker = DBGLLDBLauncher`. Anyone have this problem too?

**Comment by KojiNakamaru** [comment]
Though it is not a complete solution, you may utilize https://docs.unity3d.com/2020.3/Documentation/ScriptReference/Application-lowMemory.html . When the app detects a low memory situation, you can close the webview and reopon it.

**Comment by slugiscool99** [comment]
We ended up resolving this issue by wrapping the web request in a `using` statement

E.g. replacing 
```
var www = new UnityWebRequest(backendUrlBase + urlRelativePath, method);
byte[] bodyRaw = Encoding.UTF8.GetBytes(body);
...
```

with 

```
using (UnityWebRequest www = new UnityWebRequest(backendUrlBase + urlRelativePath, method))
{
      byte[] bodyRaw = Encoding.UTF8.GetBytes(body);
      ...
}
```
