### ISSUE TITLE
Problems about download PDF from website

### ISSUE THREAD

**Issue by marcolau0212** [gree/unity-webview#848]
Hi, I'm working to develop an application that is using the WebView on iOS. When I'm try to press the "Export PDF" (Photo 1), it becomes to garbled (Photo 2). In website, it will popup a download window (Photo 3) 

Q1. Is the WebView support download file from website to device? I had read some issues before, it seem that it need to change some code from the website

Q2. Because I'm not familiar with JavaScript, I don't how to replace the if() to let the function become to find a key word, such as sample, default in the "https://www.africau.edu/images/default/sample.pdf", can the function be like that?

                webViewObject.EvaluateJS(@"
                  (function() {
                    var links = document.links;
                    for (var i = 0; i < links.length; i++) {  
                      var l = links[i];
                      if (/\.pdf$/.test(l.href)) { //replace to keyword
                        l.href = 'https://docs.google.com/gview?embedded=true&url=' + encodeURI(l.href);
                      }
                    }
                  })();
                ");

Finally, sorry for my terrible English.

Photo 1
![Photo 1](https://user-images.githubusercontent.com/68040431/197722925-f48f22c9-51cc-4f5e-860b-870ec3e37ce2.jpg)

Photo 2
![Photo 2](https://user-images.githubusercontent.com/68040431/197992254-4a707e00-8193-496c-a3a3-dd90d0e91d83.jpg)

Photo 3
![Photo 3](https://user-images.githubusercontent.com/68040431/197992585-2442fd41-a72d-4b1e-8ecf-1d62ec40e772.jpg)

**Comment by KojiNakamaru** [comment]
Sorry for this late reply.

> Q1. Is the WebView support download file from website to device? I had read some issues before, it seem that it need to change some code from the website

The current implementation doesn't support file downloading. If you set a response header `Content-Type: application/pdf`, the content could be displayed correctly.

> Q2. Because I'm not familiar with JavaScript, I don't how to replace the if() to let the function become to find a key word, such as sample, default in the "https://www.africau.edu/images/default/sample.pdf", can the function be like that?

For example, the following code retrieves the keyword and output it to the console:

```javascript
(function() {
  var links = document.links;
  for (var i = 0; i < links.length; i++) {  
    var l = links[i];
    if (/([^/]+)\.pdf$/.test(l.href)) { //replace to keyword
      console.log(RegExp.$1);  // this outputs the keyword.
      l.href = 'https://docs.google.com/gview?embedded=true&url=' + encodeURI(l.href);
    }
  }
})();
```

**Comment by marcolau0212** [comment]
Thank you for your reply!

> 
> The current implementation doesn't support file downloading. If you set a response header `Content-Type: application/pdf`, the content could be displayed correctly.
> 

I'm not sure what setting the response header `Content-Type: application/pdf` means. Is that something like this code on the PHP or HTML? (sorry for that, I'm really not familiar with the website coding)

>header('Content-type: application/pdf');

By the way, I found a way to download PDF files into the Unity application and allow users to can share the PDF file (Photo 1). 

Photo 1
![IMG_3E7BDE14D508-1](https://user-images.githubusercontent.com/68040431/198312165-05d51357-18a5-4f43-92e7-14a8aa93fd43.jpeg)


I try to use `UnityWebRequest` to download the PDF file and save it into the Unity application. Then I import this Objective-C code as a .mm file (The code link: [https://answers.unity.com/questions/1337996/ios-open-docx-file-from-applicationpersistentdata.html?childToView=1426652#answer-1426652](url))

So I can call this function to share the PDF, but I'm no idea what those codes are doing ; )

>  #if UNITY_IOS
>  [DllImport ("__Internal")]
>  internal static extern bool OpenDocumentOnIOS (string path);
>  #endif

Here is the new result after I press the "Export PDF" button on the website. 
![IMG_0055](https://user-images.githubusercontent.com/68040431/198303775-abfd35eb-3425-46e7-9ca6-d7ee4fc83cd4.PNG)

However, another problem happened, sometimes the PDF file will not open. When I try to open it with a PDF reader, the response to the PDF file is the file crash (in my case, I use Microsoft Office and Adobe Acrobat Reader). I'm not sure the reason that it happened is I call the `UnityWebRequest` and `OpenDocumentOnIOS` in the SampleWebView Started callback. I saw there has a `CallOnError` log, which is ErrorDomain Code =-999. I'll change the function `OpenDocumentOnIOS` call in the Loaded callback tomorrow and see is there have any bugs.

**Comment by KojiNakamaru** [comment]
How do you utilize UnityWebRequest? As its SendWebReqeust() returns an async operation, you have to wait for its completion.

**Comment by marcolau0212** [comment]
This is how I download and open files. That is just the concept that how I use the UnityWebRequest, the actual programming is something more in the `DownloadFile_Coroutine`. But the program is on my company computer, so I can't show the program right now. However, the concept is similar to what I typed here. 

Besides, I find out why the PDF file can't open, I find out the file Content-type is text/html, so I can't download it as the pdf file!

P.S. The reason I can await `request.SendWebRequest();` is I download a plugin that can 'await' objects from within async methods in the same way as 'yield' objects within coroutines (Async Await Support)
>     private async void DownloadAndOpenFile(string url, string pathWithName)
>     {
>         await DownloadFileAsync(url, pathWithName);
>         await OpenFile(pathWithName);
>     }
> 
>     private async Task OpenFile(string pathWithName)
>     {
>         OpenDocumentOnIOS(pathWithName);
>         await Task.Yield();
>     }
> 
>     private async Task DownloadFileAsync(string url, string pathWithName)
>     {
>         UnityWebRequest request = UnityWebRequest.Get(url);
> 
>         await request.SendWebRequest();
> 
>         if(request.result != UnityWebRequest.Result.Success || request.result != UnityWebRequest.Result.InProgress)
>         {
>             Debug.LogError(request.error);
>         }
>         else
>         {
>             File.WriteAllBytes(pathWithName, request.downloadHandler.data);
>         }
>     }
