### ISSUE TITLE
Can't work in Android APP.

### ISSUE THREAD

**Issue by Ace8793** [gree/unity-webview#85]
Hi，I've followed the step in README.but I can't see any object in an Android running app.
In my screen, just a blue-and-white color background.
Could you please write a more detailed demonstration?will be better with some pictures which show the result view.

**Comment by KojiNakamaru** [comment]
As described in https://github.com/gree/unity-webview#sample-project,

0. Open `sample/` project.
1. Open `sample/Assets/Sample.unity`
2. Open `dist/unity-webview.unitypackage` and import all files.
3. Select "File/Build Settings...", "Switch Platform" to "Android", connect your Android device, and "Build And Run".

Though there might be any performance issue, these steps (without https://github.com/gree/unity-webview#android ) should show the following:

![image](https://cloud.githubusercontent.com/assets/2645978/16217211/3579f2ce-37ac-11e6-8a85-3bd857b28efe.png)

I've tested with the following environemnt:

* Unity 5.3.5p4
* Android SDK (latest)
* Nexus 7 (2013, Android 6.0.1)
