### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by unobatbayar** [gree/unity-webview#852]
It works in Android Unity Editor but when built into a device, it doesn't display web page.

I've tested on couple of devices. Is it because of minimum API level? iOS seems to works well.

I highly value your reply. I'll keep trying in the mean time.

Thank you.

**Comment by KojiNakamaru** [comment]
You might access http (not https) urls, for which you need to define `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC`. The sample app allows http urls for iOS by setting "Allow downloads over HTTP (nonsecure)".

cf. https://github.com/gree/unity-webview/tree/151053c9058c7a740f09139c6b2ebe89b8e9d44b#usescleartexttraffic

**Comment by unobatbayar** [comment]
Thank you, I'm testing using `https://www.google.com` but I'll give this a try.

**Comment by KojiNakamaru** [comment]
I've put a modified sample app that can be directly built with Unity 2020.3.34f1.

https://github.com/gree/unity-webview/tree/example-for-852/sample

The attached [sample.apk.zip](https://github.com/gree/unity-webview/files/9987564/sample.apk.zip) contains built sample.apk that runs correctly on my devices, so please try it.

**Comment by unobatbayar** [comment]
Tested with the [sample.apk.zip](https://github.com/gree/unity-webview/files/9987564/sample.apk.zip). 

It works!!

It seems like the problem is not with this package but instead my local environment. I'll try to debug further and see what is going wrong.

Anyway, thank you so much for your time.

**Comment by unobatbayar** [comment]
Do I need to build `WebViewPlugin.jar`? It seems like it's not sending the request at all. It's always at 0 on when I integrate to my project.

**Comment by unobatbayar** [comment]
Do I need to build `WebViewPlugin.jar`?

When I integrate to my project, Android version doesn't send the request. it's 0, even if I refresh.

No canvas too.

**Comment by unobatbayar** [comment]
I guess the problem is how I imported the package.

**Comment by KojiNakamaru** [comment]
You should follow the following instruction:
https://github.com/gree/unity-webview/tree/151053c9058c7a740f09139c6b2ebe89b8e9d44b#sample-project
