### ISSUE TITLE
Is there a part that passes values ​​from Unity to WebView?

### ISSUE THREAD

**Issue by FrogLoverCEO** [gree/unity-webview#854]
hello

I am working on android

**When I click a button in Unity, I want to open the Html page as a WebView and pass the value to the Html.**

I can't find where to pass values ​​from Unity to WebView

Is there a part that passes values ​​from Unity to WebView?

**Comment by KojiNakamaru** [comment]
You can use EvaluateJS() to evaluate any javascript, for example, the following will set the body's backgroundColor.

```c#
    webViewObject.EvaluateJS(@"document.body.style.backgroundColor = 'aquamarine';");
```

**Comment by FrogLoverCEO** [comment]
> 

webViewObject.EvaluateJS Is this a function that executes a JS script?

I will write and apply JS

Thank you so much for your reply!
