### ISSUE TITLE
Is there a way to make the set Html come out without being affected by the dark mode?

### ISSUE THREAD

**Issue by FrogLoverCEO** [gree/unity-webview#861]
hello

I had a problem with the dark mode of my smartphone.

I tried to create a color palette in Html and display it as a WebView.

However, because of the dark mode, the color set to white comes out as dark gray.

Is there a way to make the set HTML appear as it is without being affected by the dark mode of the smartphone?

**Comment by KojiNakamaru** [comment]
As commented in https://github.com/gree/unity-webview/issues/683#issuecomment-830828387 , you can specify `androidForceDarkMode: 1` as an argument of Init() to force the dark mode off.
