### ISSUE TITLE
Webview seems to be whited out and I can't click radio buttons

### ISSUE THREAD

**Issue by gabrielvillage** [gree/unity-webview#877]
I'm implementing the webview as a login page on my app but when testing it out on the Editor the webpage seems to have a white hue on it and I can't click the Player/Developer radio buttons seen below. Any idea how I can fix this?
<img width="472" alt="image" src="https://user-images.githubusercontent.com/118750311/215770865-d2a9cb4a-e4c8-42a2-8936-8725c371a93c.png">

**Comment by KojiNakamaru** [comment]
The implementation for Editor utilizes offscreen rendering, which is tricky and may cause various issues. If you specify `separated: true` as an argument of `webViewObject.Init()`, the plugin utilizes a separated window to show a webview and this mode should have less trouble. In this mode, you can also use WebView's developer tools by selecting `Inspect Element` from the right-click menu. Could you please try it?

**Comment by KojiNakamaru** [comment]
Yes, iOS/Android implementation just overlays native WKWebView/WebView on unity's rendering view and should have no issue like this.

BTW, the "Google" button might not work as Google forbids webviews for OAuth requests.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html

In this case, you could utilize SFSafariViewController/ChromeCustomTabs. This plugin doesn't support them, but I provide a very simple sample app:

https://github.com/gree/unity-webview/tree/25f8a1f43d1b1defaca983e2f9bd78cf1ecbdc76/appendix/sample-sfsafariviewcontroller-chromecustomtabs

The following threads might also help.

https://github.com/gree/unity-webview/issues/313#issuecomment-381836584

**Comment by gabrielvillage** [comment]
I've tested it on the mobile build and it worked as intended. Indeed the Google button didn't work so I'll check the references you posted, thanks!

**Comment by gabrielvillage** [comment]
Do you know if there's any way of retrieving data from the SFSafariViewController/ChromeCustomTabs in Unity (similar to the "Unity.call" in the webview)?

**Comment by KojiNakamaru** [comment]
Unfortunately those are very limited compared with WebView/WKWebView. Though I've not tested, custom url schemes could be utilized:

https://stackoverflow.com/questions/36184837/exchanging-data-from-sfsafariviewcontroller-to-native-app-interface/36264945#36264945
