### ISSUE TITLE
Androidでカスタムヘッダーを設定するとPOSTデータがうまく送信されない。

### ISSUE THREAD

**Issue by r-onodera** [gree/unity-webview#881]
Androidにて、カスタムヘッダーを設定するとPOSTデータがうまく送信されない事象にぶつかっております。

Unity（C#）側で以下のように設定を行いました。

```cshape
webViewObject.AddCustomHeader("Au", "Bearer {token}");
webViewObject.LoadURL("POST送信を行うurl");
```

そして以下のようなHTMLとPHPを用意して確認しておりましたが、POSTデータを受けることができませんでした。

```html
<form method="post" action="./">
<input type="hidden" name="hoge" value="hoge">
</form>
```

```php
<pre><?php var_dump($_POST); ?></pre>
```

カスタムヘッダーを指定しないとうまくいくことから、カスタムヘッダーがあるときだけ起こるのではと考えております。
私の勘違いかもしれませんが、ご確認頂けますと幸いです。

**Comment by KojiNakamaru** [comment]
残念ながら、WebViewのAPIの制限から、カスタムヘッダの設定は、ごく制限された利用範囲でしか動作せず、POSTには対応していません。

**Comment by r-onodera** [comment]
承知いたしました。ありがとうございます。
