### ISSUE TITLE
Make httpErr work in Unity Editor

### ISSUE THREAD

**Issue by Wave1** [gree/unity-webview#882]
I've been trying to obtain the HTTP status code when loading a page and noticed the httpErr parameter that allows a callback to be set to retrieve the error code.  This code was originally submitted by JaredHays in commit #335 

It appears to work on iOS and Android but not in the Unity Editor (and presumably therefore Mac).

Is it possible to make this functionality work in the Unity Editor as well please?

**Comment by KojiNakamaru** [comment]
I modified the code in #883 and updated binaries. Could you please try the latest?

**Comment by Wave1** [comment]
Awesome, thanks for the really fast fix, can confirm it's working!  Very much appreciated.
