### ISSUE TITLE
Syntax error in WebViewObject.cs

### ISSUE THREAD

**Issue by erinlin** [gree/unity-webview#89]
In Init function, there are extra curly brackets to cause Unity Editor crushed. BTW thanks for kindly shared.
`#if UNITY_EDITOR || UNITY_STANDALONE_OSX`
        `{ << this`
           ` var uri = new Uri(_CWebViewPlugin_GetAppPath());`
          ` ....`
          `   if (Regex.IsMatch... ) {`
          `   ....`
           `  }`
        `}  << and this`

**Comment by KojiNakamaru** [comment]
It shouldn't crash with these brackets, at least Unity 5.3.5p6 (I'm currently using) works without any issue. With which version of Unity do you have the issue?
