### ISSUE TITLE
Androidについて<input type="file">でカメラ撮影した際にファイルが反映されない

### ISSUE THREAD

**Issue by x-ishi** [gree/unity-webview#890]
現在androidについてHTMLのinput type="file"でカメラ撮影したファイルが反映されない現象が発生しています。

・確認手順
　1. <input type="file" id="inputfile" accept="image/*;capture=camera""> の項目があるページのURLをWebViewで表示
　2. 上記選択時にカメラ撮影またはギャラリー選択の項目が表示される
　3. ギャラリー選択の場合は選択したファイルが反映される
　4. カメラ撮影の場合はカメラが起動→撮影した画像を選択してもページに反映されない

設定内容は以下の通りになりますので不足している設定項目などがあればご教授いただけたらと思います。

・確認端末
　Pixel3 (OS12)
　Pixel2XL(OS11)

・Unity2020.3.43f1
　プロジェクトを新規作成

・https://github.com/gree/unity-webview/blob/master/dist/unity-webview.zip
　Assetsフォルダ内のファイルをプロジェクトに複製

・https://github.com/gree/unity-webview/tree/master/dist
　unity-webview.unitypackageをインポート

・AndroidManifest.xmsを作成し以下の権限を追記

  uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
  uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
  uses-permission android:name="android.permission.CAMERA"
  uses-feature android:name="android.hardware.camera" 

  uses-permission android:name="android.permission.MICROPHONE" 
  uses-feature android:name="android.hardware.microphone" 
  uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" 
  uses-permission android:name="android.permission.RECORD_AUDIO" 

　activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/UnityThemeSelector"
                  android:hardwareAccelerated="true"
 

・Project Setting
　Internet Access に Requireを設定
　Player Settings/Other Settings/Write Permission に External(SDCard)を設定
　Scripting Define Symbols に UNITYWEBVIEW_ANDROID_ENABLE_CAMERAを追記

・SampleWebView.cs
　https://github.com/gree/unity-webview
　上記を参考にカメラのパーミッションを追記

**Comment by KojiNakamaru** [comment]
https://github.com/gree/unity-webview/tree/b3d726157eecb0504d2edc316d09ccb8a1f25b56#file-input-field
https://github.com/gree/unity-webview/tree/b3d726157eecb0504d2edc316d09ccb8a1f25b56#cameraaudio-permissionfeature

の対応が必要です。まとめると、次のようになります。

* `Player Settings/Other Settings/Configuration/Write Permission`を`External (SDCard)`にすること
* `Player Settings/Other Settings/Script Compilation/Script Define Symbols`に`UNITYWEBVIEW_ANDROID_ENABLE_CAMERA`を定義すること
* 実行時
  * https://github.com/gree/unity-webview/tree/b3d726157eecb0504d2edc316d09ccb8a1f25b56#cameraaudio-permissionfeature の最後にあるように、カメラを使う許可を得ること
  * `webViewObject.SetCameraAccess(true);`を呼ぶこと

**Comment by x-ishi** [comment]
ご確認ありがとうございます。

いただいた設定を試しましたが改善されないようでした。

**Comment by KojiNakamaru** [comment]
次にUnity 2020.3.45f1で直接ビルドできる状態のものを置きました。OSCAL Pad 8 (Android 11, https://www.devicespecifications.com/en/model/8edb570f )では動作することを確認しています。

https://github.com/gree/unity-webview/tree/example-for-890/sample

**Comment by x-ishi** [comment]
ありがとうございます。
改めていただいた内容を試しましたが改善されないようでしたので確認手順をお送りいたします。

1. 以下のプロジェクトファイルをダウンロード
　 https://github.com/gree/unity-webview/tree/example-for-890/sample

2. 1のプロジェクトファイルをUnity2020.3.45f1で起動
　 Build SettingsでAndroidを選択しBuildを実行

3. ビルドしたapkファイルを「adb install -r ビルドしたapk」でインストール

4. アプリを起動し「ファイルを選択」→「カメラ」を選択しカメラを起動
　　写真を撮影→チェックボタンでアプリに戻る
　　写真が選択されない(ストレージから選択した場合はファイル名が表示される)

アプリの操作について画面を録画しましたので添付いたします。
https://user-images.githubusercontent.com/114798103/224863051-507e6f1a-aa8b-453c-b9dc-a64ea7780e9c.mp4

また、作業環境は以下になります。

・確認端末
　Google Pixel3 (OS12)

・ビルドPC
　macOS Monterey
　MacBook Pro(13-inch, 2020, Four Thunderbolt 3 ports)
　プロセッサ 2.3GHz クアッドコア Intel Core i7
　メモリ 32GB 3733 MHz LPDR4X
　グラフィックス Intel Iris Plus Graphics 1536MB

**Comment by KojiNakamaru** [comment]
Pixel2XL(OS11)でも同様でしょうか？

**Comment by x-ishi** [comment]
Pixel2XL(OS11)も同じ動作になりました。

**Comment by KojiNakamaru** [comment]
確認、ありがとうございます。改めて調査したところ、AndroidManifest.xmlへのqueriesの追加が必要なことがわかったので、 #891 で修正し、バイナリを更新しました。
https://github.com/gree/unity-webview/tree/example-for-890/sample
も参照しているパッケージを更新しています。

**Comment by x-ishi** [comment]
ありがとうございます。
https://github.com/gree/unity-webview/tree/example-for-890/sample
上記のプロジェクトでカメラでの画像選択が動作することを確認しましたのでご連絡とさせていただきます。

**Comment by x-ishi** [comment]
引き続きアプリへの組み込みを行なっているのですが、現在uGuiと併用してWebViewを使用していまして、カメラアクセスの許可ダイアログの表示があるとカメラを起動して戻った際にuGuiをシーンから削除しても表示されたままになる現象が発生しています。
発生手順は以下になりますが、何かしらご存じであればご教授いただけますと幸いです。

1. WebViewObjectを生成しWebViewを表示
2. WebViewをuGui(Imageなど)の子オブジェクトに設定
3. HTMLのinput type="file"を選択するとカメラアクセスの許可ダイアログが出るため許可→カメラ撮影を選択しカメラを起動
　　カメラアクセスの許可後にデバイス内の写真などのアクセスの許可ダイアログが一瞬出るが勝手に消える ※ファイルアクセス許可は別画面で設定済
4. カメラを閉じる
5. Destroy(1のuGuiオブジェクト)でuGuiを削除
6. WebViewの表示は無くなるが削除したuGuiが画面に表示されたままになる
7. アプリをバックグラウンド→フォアグラウンドにするとuGuiの表示が無くなる

3のカメラアクセスの許可ダイアログの表示がない場合は現象は発生しないです。

**Comment by KojiNakamaru** [comment]
sampleアプリを元にuGUIのImageにWebViewを付帯するものを作ってみました。問題のような現象は再現しないようです。

https://github.com/gree/unity-webview/tree/example-for-890-2

**Comment by x-ishi** [comment]
ご確認ありがとうございます。

いただいたプロジェクトについてアプリの組み込みを行なっているUnity2020.3.43f1で確認したところ、お送りした現象を確認しましたので画面録画をお送りします。

・確認端末
　Pixel3 (OS12)

https://user-images.githubusercontent.com/114798103/228405782-39d8084b-dd9d-42bd-8427-7ee93d5924bf.mp4

**Comment by KojiNakamaru** [comment]
動画ありがとうございます。こちらでも再現させることができました。パーミッションに関する処理をUnity側で行うように修正したところ(#901)、うまく動作するようになりました。 https://github.com/gree/unity-webview/tree/example-for-890-2 を更新してありますのでご確認ください。

**Comment by x-ishi** [comment]
ありがとうございます。

いただいたサンプルについて修正されていることを確認しました。

アプリに組み込んで確認したところまだ現象が発生するようでしたので実装を確認しています。

**Comment by x-ishi** [comment]
アプリの組み込みに原因があると思われますが、WebViewObject.cs内の以下の処理を1フレーム待機させてから実行することで解決いたしました。
webView.Call("OnRequestFileChooserPermissionsResult", grantedCount == permissions.Count);
