### ISSUE TITLE
unitywebview_file_provider_paths

### ISSUE THREAD

**Issue by rokrodic** [gree/unity-webview#892]
Hi.
I compiled my project from scratch (clean build) on android and I received the following error:
`Gradle Error: Resource Not Found
Resource 'xml/unitywebview_file_provider_paths' not found in AndroidManifest.xml:96
`

in the file the line 96 points to meta-data:

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.someproject.ext.unitywebview.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/unitywebview_file_provider_paths" />
        </provider>

the origin is at: 
[https://github.com/gree/unity-webview/blob/5daaa90e847dffd70155bd636a26f205807d30fc/plugins/Editor/UnityWebViewPostprocessBuild.cs#L351](url)

What happened and how to solve it?
Thanks in advance,
Rok

**Comment by KojiNakamaru** [comment]
That file should be emitted by https://github.com/gree/unity-webview/blob/5daaa90e847dffd70155bd636a26f205807d30fc/dist/package/Assets/Plugins/Editor/UnityWebViewPostprocessBuild.cs#L332-L340 .

Please try the sample app. It can be built at least with Unity 2020.3.45f1.

**Comment by rokrodic** [comment]
Hi.
Thank you Koji! Sample app compiles OK.

What I have done to sort'a solve the issue with my app: commented out lines regarding "unitywebview_file_provider_paths" in UnityWebViewPostprocessBuild.cs and in AndroidManifest.xml regarding "paths" and clean built the app. I received new issues, but after reverting changes made my original code the app compiled again with no errors. 
I believe this is Unity's fault. I think resover messed things up when I changed platform to iOS and then back.

Koji, keep up the good work!
