### ISSUE TITLE
Problems of remote debugging enable

### ISSUE THREAD

**Issue by marcolau0212** [gree/unity-webview#897]
Hi, this problems is my client ask me to push the apk file to MobSF for checking security. When I pushed the file and checked, one of the "high" problems is "Remote Webview Debugging Enabled."

I had read some document, it seem that is the problems about signing?

**Comment by KojiNakamaru** [comment]
The plugin calls setWebContentsDebuggingEnabled(true) to allow remote debugging but only for the development build.

#454

MobSF's detects setWebContentsDebuggingEnabled(true) without checking its context, so it falsely says "Remote WebView debugging is enabled."

https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/6c64d17229164d15458290921216e7834a4719f9/mobsf/StaticAnalyzer/views/android/rules/android_rules.yaml#L205-L218

If you need to remove this alert from MobSF, you can remove the part introduced in #454 and rebuild WebView.aar by following https://github.com/gree/unity-webview/tree/25adb7df2b08ebee4fa367414836d164f80751a8#how-to-build-webviewpluginjar . For convenience, I've put binaries without setWebContentsDebuggingEnabled(true) in https://github.com/gree/unity-webview/tree/example-for-897 .

**Comment by marcolau0212** [comment]
This is a big thanks! You save my time and life ; )
