### ISSUE TITLE
Getting a Base URL

### ISSUE THREAD

**Issue by jamesT232** [gree/unity-webview#898]
Is there a way to fetch base URL from

        webViewObject.Init(
            cb: (msg) =>
            {
                Debug.Log(string.Format("CallFromJS[{0}]", msg));
                Url = msg;
                URLstatus.GetComponent<Animation>().Play();
            }

Callback

**Comment by marcolau0212** [comment]
Actually that may have some problem. The Callback actually will receive javascript call from the webview, which mean you will receive all javascript to the callback. The better way is to use the `EvaluateJS` function to get base url and use `Unity.call` to let Unity can receive the url. Which will be something like this

**Comment by jamesT232** [comment]
Thank so much, you guys plugin as being really helpful to me as a college student
