### ISSUE TITLE
Can i use html load local file from android

### ISSUE THREAD

**Issue by howo** [gree/unity-webview#90]
like this
https://dotblogs.com.tw/clark/2015/07/28/152978
Reading the local side have security issues thanks help^^

**Comment by KojiNakamaru** [comment]
The implementation already contains the following so it should work.
https://github.com/gree/unity-webview/blob/383b3585ff5afd215980e55ce23bc247fcf6eba4/plugins/Android/src/net/gree/unitywebview/CWebViewPlugin.java#L129-L132

**Comment by howo** [comment]
thanks help it work!!
ur nice man^^

**Comment by KojiNakamaru** [comment]
Yes, WebViewObject.cs contains `EvaluateJS(string js)`:
https://github.com/gree/unity-webview/blob/383b3585ff5afd215980e55ce23bc247fcf6eba4/plugins/WebViewObject.cs#L288

**Comment by howo** [comment]
i want call this javascript

test.html:
function changeText(text){
	$("h1").text(text);
}

unity:
 case RuntimePlatform.Android:
                webViewObject.EvaluateJS("changeText('1232455')");

but i dont know how use 
webViewObject.EvaluateJS(); thanks help^^

**Comment by KojiNakamaru** [comment]
The usage you described should be okay. `EvaluateJS(js)` evaluates `js` as JavaScript.

**Comment by howo** [comment]
Thanks it work 
my bad 
thanks u help^^
