### ISSUE TITLE
Compatible with ReactJS pages, and loading HTML5 gamep ages?

### ISSUE THREAD

**Issue by abphaiboon** [gree/unity-webview#909]
Hi im creating a lobby type mobile app. The thing is it works great on iPhone and loads all ReactJS pages, and HTML5 games. 

but when i move to android, the whole webview doesnt even show up?

Ive tested the URLs in the sample project, and it hangs up, and stays at a black screen etc. I'm guessing its something to do with processing react/js files?

**Comment by KojiNakamaru** [comment]
You might use http instead of https. For iOS, the sample app specifies "Allow downloads over HTTP" but for Android, you need to define `UNITYWEBVIEW_ANDROID_USES_CLEARTEXT_TRAFFIC`.

cf. https://github.com/gree/unity-webview/tree/bb7093087074a780022acc40b375b84f319e85aa#usescleartexttraffic

**Comment by abphaiboon** [comment]
Would this be defined in my player settings? Sorry still relatively new to unity.

**Comment by abphaiboon** [comment]
@KojiNakamaru sorry for bump. Is it in player settings in built settings?

**Comment by KojiNakamaru** [comment]
Yes, you can define it in the Android Tab of the Player Settings.

https://docs.unity3d.com/2020.3/Documentation/Manual/CustomScriptingSymbols.html
