### ISSUE TITLE
It doesn't work in viewing PDF file?

### ISSUE THREAD

**Issue by subokita** [gree/unity-webview#91]
Seems like LoadURL() doesn't work with PDF file when testing it using Android device. It doesn't throw any error at all.

**Comment by KojiNakamaru** [comment]
You cannot display a pdf on Android WebView. Please refer the following:
http://stackoverflow.com/questions/11613505/how-to-open-local-pdf-file-in-webview-in-android

**Comment by subokita** [comment]
Ah, I understand now. Thanks for the quick reply!
