### ISSUE TITLE
Cannot upload picture from gallery

### ISSUE THREAD

**Issue by Ludwintor** [gree/unity-webview#910]
Im trying to attach picture from gallery, but it doesn't work at all. When file chooser appears (camera or files), I select files, go to gallery and select image from it and nothing happens, but if I just select image from files (without going to gallery) it works fine. Uploading picture from camera also works fine. I already tried to add permissions `ACCESS_MEDIA_LOCATION`, `READ_MEDIA_IMAGES` to my manifest but it didn't helped me

**Comment by KojiNakamaru** [comment]
I've put a modified sample app that can be directly opened with 2020.3.34f1:

https://github.com/gree/unity-webview/tree/example-for-910/sample

It enables `Write Permission: External (SDCard)` and defines `UNITYWEBVIEW_ANDROID_ENABLE_CAMERA`. It seems to work well on OSCAL Pad 8 (Android 11) with Google's Gallery app (https://play.google.com/store/apps/details?id=com.google.android.apps.photosgo).

**Comment by Ludwintor** [comment]
I know about that. I already have that. Uploading files works great, but uploading files from gallery didn't work. I try to say steps to reproduce on this sample:
1) Open app
2) Go to google.com
3) Search for any photo hosting site (imgbb.com for example)
4) Click "Upload"
5) From input dialog choose Files
6) (At least on MI T9 (android 10) there is "Browse files in other apps" where I select Gallery (screenshot below)
7) Choose any image from gallery
8) Confirm
9) Nothing happens or error that unable to add this file

![image](https://user-images.githubusercontent.com/57525754/232253298-6af538b1-8475-46a2-980b-95c8f26ce89a.png)

**Comment by Ludwintor** [comment]
But when I just select image from "Recent files" or any other app in "Browse files in other apps" it works great and everything uploads

**Comment by KojiNakamaru** [comment]
If you use https://play.google.com/store/apps/details?id=com.google.android.apps.photosgo , does the issue still occur?

**Comment by Ludwintor** [comment]
No, but it possible to use default gallery without downloading another?

**Comment by KojiNakamaru** [comment]
Though it should not have any effect on Android 10, I added the `GET_CONTENT` action in `queries` (#911). This might reduce the issue. I've also updated https://github.com/gree/unity-webview/tree/example-for-910/sample to use the updated unity-webview.

**Comment by JalalMAR** [comment]
@Ludwintor I'm facing a similar issue to the one you were having can you help me fix it please?
this is my whatsApp +212632569306
