### ISSUE TITLE
wkwebview

### ISSUE THREAD

**Issue by awdogsgo2heaven** [gree/unity-webview#92]
Any chance we could see WKWebView support in the future? My understanding the performance is much better than a UIWebView.

**Comment by KojiNakamaru** [comment]
I've just finished the initial implementation for WKWebView: https://github.com/gree/unity-webview/pull/95 . As noted at https://github.com/gree/unity-webview/tree/a7151720070dfe57afba5f05159c1bb53cdd029f#ios it is disabled by default so please enable it by setting `enableWKWebView`.

**Comment by KojiNakamaru** [comment]
I've just fixed WebView.mm in https://github.com/gree/unity-webview/pull/97 .  Please pull again if necessary.

**Comment by DevUNakamura** [comment]
Sorry, I have a question to you.
I would like to use WKWebView. I wrote following source code.
void Start()
    {
        webViewObject =
			(new GameObject("WebViewObject")).AddComponent<WebViewObject>();
		webViewObject.Init((msg)=>{
			if (msg == "clicked") {
				webViewObject.SetVisibility(false);
			}
		},enableWKWebView: true);


		webViewObject.LoadURL(url);
		webViewObject.SetMargins(50,100,50,50);
		webViewObject.SetVisibility(true);
    }

But I could not compile correctly with this source code.
How can I enable WKWebView?
Is there anything my mistake in my source code?

Best Regards.

**Comment by KojiNakamaru** [comment]
cf. https://github.com/gree/unity-webview/issues/522#issuecomment-604151470
