### ISSUE TITLE
Bug with android margin adjustment for keyboard.

### ISSUE THREAD

**Issue by pinnakkkk** [gree/unity-webview#926]
Hi there! I have been using the Unity WebView plugin in my project, and overall it has been a great tool. However, I have encountered an issue with the Android margin adjustment for the keyboard, which is not working as stated in the issue #300.

Expected Behavior:
When an input field receives focus and the keyboard appears, the WebView content should be adjusted to ensure the input field remains visible without being obscured by the keyboard.

Actual Behavior:
The Android margin adjustment for the keyboard does not seem to work as intended. The WebView content does not properly adjust, resulting in the keyboard partially or completely obscuring the focused input field. 

Additional Information:
Unity version: 2021.3.0f1
Device tested: Redmi k20 (Android 11)
Unity Player settings: fullscreen enabled

Thank you for your effort in developing this plugin. It has been a valuable addition to my project, and I appreciate your dedication to maintaining it.

Please let me know if there are any further details or information I can provide to help resolve this issue.

**Comment by pinnakkkk** [comment]
Update: upon further investigating this piece of code is always false even if the keyboard is shown.

```
/// Called from Java native plugin to set when the keyboard is opened
	public void SetKeyboardVisible(string pIsVisible)
	{
		Debug.Log("SetKeyboardVisible: " + pIsVisible);
		if (BottomAdjustmentDisabled())
		{
			return;
		}
		bool isKeyboardVisible0 = mIsKeyboardVisible;
		mIsKeyboardVisible = (pIsVisible == "true");
		if (mIsKeyboardVisible != isKeyboardVisible0 || mIsKeyboardVisible)
		{
			SetMargins(mMarginLeft, mMarginTop, mMarginRight, mMarginBottom, mMarginRelative);
		}
	}
```

**Comment by KojiNakamaru** [comment]
Thank you for reporting and investigating the issue. I modified the keyboard detection logic in #928 and updated binaries. Could you please try the latest?

**Comment by wa1kb0y** [comment]
Hello, i tried it and it seems issue is still there, i tried to import `unity-webview.unitypackage` in new clean project to test. @pinnakkkk does fix work for you?

**Comment by x-ishi** [comment]
Project Settings > Resolution and Presentatin > Hide Navigation Bar
サンプルについて確認していまして上記のチェックをオフにすると調整が無効になるようでした。

ステータスバーとナビゲーションバーを表示した上で動作するように改善していただくことは可能でしょうか。

**Comment by KojiNakamaru** [comment]
@x-ishi #938 で`UNITYWEBVIEW_ANDROID_FORCE_MARGIN_ADJUSTMENT_FOR_KEYBOARD`を定義した場合に、常に調整を行うようにしました。 #729 の問題は、現時点の手元の端末で試した限りは起こらないようです。

なお、別件ですが、 https://github.com/gree/unity-webview/issues/890#issuecomment-1600345675 を参考にさせていただいて、最新のバイナリには #937 も含まれています。

**Comment by x-ishi** [comment]
@KojiNakamaru 
ご対応ありがとうございます。
アプリに組み込んで確認しまして大丈夫そうでした。
