### ISSUE TITLE
do we have a 'back' function?

### ISSUE THREAD

**Issue by AZLDC** [gree/unity-webview#93]
do we have a 'back' function?
it's just like a back button like in internet browser.
maby... back and forward (button) function.

**Comment by KojiNakamaru** [comment]
There is no support for 'go forward/back' but it should be easy to implement them. I'll check it later.

Please note we cannot put any uGUI button over WebView/UIWebView on mobile devices, because they are shown as separate views in front of Unity's rendering. To add such buttons over WebView/UIWebView, the following tricky approach might be necessary.

```diff
diff --git a/sample/Assets/Scripts/SampleWebView.cs b/sample/Assets/Scripts/SampleWebView.cs
index e6ff151..8899204 100644
--- a/sample/Assets/Scripts/SampleWebView.cs
+++ b/sample/Assets/Scripts/SampleWebView.cs
@@ -104,4 +104,36 @@ public class SampleWebView : MonoBehaviour
 #endif
 		}
 	}
+
+	void Update()
+	{
+		if (Time.frameCount % 60 == 0) {
+			webViewObject.EvaluateJS(
+				"if (document.getElementById('__b1__') == null) {" +
+				"  var button;" +
+				"  button = document.createElement('button');" +
+				"  button.id = '__b1__';" +
+				"  button.style.position = 'fixed';" +
+				"  button.style.left = '0px';" +
+				"  button.style.top = '0px';" +
+				"  button.style.zIndex = 10000;" +
+				"  button.textContent = '<';" +
+				"  button.onclick = function() {" +
+				"	 window.history.go(-1);" +
+				"  };" +
+				"  document.body.appendChild(button);" +
+				"  button = document.createElement('button');" +
+				"  button.id = '__b2__';" +
+				"  button.style.position = 'fixed';" +
+				"  button.style.left = '40px';" +
+				"  button.style.top = '0px';" +
+				"  button.style.zIndex = 10000;" +
+				"  button.textContent = '>';" +
+				"  button.onclick = function() {" +
+				"	 window.history.go(1);" +
+				"  };" +
+				"  document.body.appendChild(button);" +
+				"}");
+		}
+	}
 }
```

Of course If you prepare HTML pages by yourself, you can add any button without such tricks.

**Comment by KojiNakamaru** [comment]
I've implemented goBack/goForward in https://github.com/gree/unity-webview/pull/96 except for WebPlayer (which requires a similar hack described above for page transitions).

**Comment by AZLDC** [comment]
thank you very much !!
my project is using webview with a samll size on screen.
so I have enouph space can show a button in unity app.
using webViewObject.EvaluateJS is good for my project too.thank agane.
maby I can use it like this in monobehaviour ?

void Back()
{
  webViewObject.EvaluateJS(
    window.history.go(-1);
  );
}

void Back()
{
  webViewObject.EvaluateJS(
    window.history.go(1);
  );
}

sorry about I never use Java befor.
and thanks about all of webview and help.

**Comment by KojiNakamaru** [comment]
You may implement Back()/Forward() as you described, but the latest unity-webview now supports them so please try it. The sample app displays back/forward buttons.

![image](https://cloud.githubusercontent.com/assets/2645978/16825525/6f1eeaf0-49b0-11e6-909b-796ffadff412.png)

https://github.com/gree/unity-webview/blob/af02117624bf5c612d903bfdb0872078c8c28e5f/sample/Assets/Scripts/SampleWebView.cs#L102-L106

**Comment by KojiNakamaru** [comment]
I've just fixed WebView.mm in https://github.com/gree/unity-webview/pull/97 .  Please pull again if necessary.

**Comment by tiancaipipi110** [comment]
@KojiNakamaru Hi, so if I want to add a custom go back button, should I just make the button, then create a function `public void GoBackButton{ webViewObject.GoBack(); }` Then attach the function to the button, correct?

**Comment by KojiNakamaru** [comment]
If you create a (uGUI) `goBackButton` separately, you need to update `goBackButton.interactable` in `Update()` instead of `OnGUI()`. For example,

```c#
    void Update()
    {
        goBackButton.interactable = webViewObject.CanGoBack(); 
    }
```

where the `goBackButton` should have a listener somewhere as below:

```c#
        ...
        goBackButton.onClick.AddListener(() => {
            webViewObject.GoBack();
        });
        ...
```

**Comment by tiancaipipi110** [comment]
@KojiNakamaru  You're saying I should replace the onGUI() with the void Update(){goBackButton.interactable = webViewObject.CanGoBack(); }?  But the `goBackButton` is an object created in the hierarchy right, how do I create a variable `goBackButton` for it?

**Comment by tiancaipipi110** [comment]
@KojiNakamaru Thanks, the doc really helped. Just realized I made a mistake there on the type, should be button instead.
