### ISSUE TITLE
Why is my webview faded?

### ISSUE THREAD

**Issue by sonanlee** [gree/unity-webview#943]
![Screenshot 2023-06-29 at 2 49 32 PM](https://github.com/gree/unity-webview/assets/90168128/f189bb79-c7e4-491f-b3c1-3da3387783c1)

Today, I set up this webview in macOS Editor.
However, my webview is too faded. Does anyone know anything about this problem?

**Comment by KojiNakamaru** [comment]
The webview might be running in transparent mode. It will be opaque if you specify `transparent: false` in webViewObject.Init() arguments.

**Comment by sonanlee** [comment]
> The webview might be running in transparent mode. It will be opaque if you specify `transparent: false` in webViewObject.Init() arguments.


Thank you for your comment, @KojiNakamaru.
I checked my code, however, I already set the `transparent:false` in webViewObject.Init()..  T_T

```
webViewObject.Init(
                msg =>
                {
                    Debug.Log($"CallFromJS[{msg}]");
                },
                msg =>
                {
                    Debug.Log($"CallOnError[{msg}]");
                },
                msg =>
                {
                    Debug.Log($"CallOnHttpError[{msg}]");
                },
                started: msg =>
                {
                    Debug.Log($"CallOnStarted[{msg}]");
                },
                hooked: msg =>
                {
                    Debug.Log($"CallOnHooked[{msg}]");
                },
                cookies: msg =>
                {
                    Debug.Log($"CallOnCookies[{msg}]");
                },
                ld: msg =>
                {
                    Debug.Log($"CallOnLoaded[{msg}]");
                    var js = @"
                    if (!(window.webkit && window.webkit.messageHandlers)) {
                        window.Unity = {
                            call: function(msg) {
                                window.location = 'unity:' + msg;
                            }
                        };
                    }";
                    webViewObject.EvaluateJS(js + @"Unity.call('ua=' + navigator.userAgent)");
                }, transparent: false);
```

**Comment by KojiNakamaru** [comment]
I've put a modified sample under https://github.com/gree/unity-webview/tree/example-for-943/sample , which can be directly opened with Unity 2020.3.48f1. This shows the followings in my environment:
<img width="865" alt="image" src="https://github.com/gree/unity-webview/assets/2645978/43f9ffe1-7fc2-4306-951f-57e334e6e1a7">
<img width="759" alt="image" src="https://github.com/gree/unity-webview/assets/2645978/61a0ba59-094e-4a0f-bf0a-35bab79dcd0a">

**Comment by sonanlee** [comment]
> I've put a modified sample under https://github.com/gree/unity-webview/tree/example-for-943/sample , which can be directly opened with Unity 2020.3.48f1. This shows the followings in my environment: <img alt="image" width="865" src="https://user-images.githubusercontent.com/2645978/249759878-43f9ffe1-7fc2-4306-951f-57e334e6e1a7.png"> <img alt="image" width="759" src="https://user-images.githubusercontent.com/2645978/249759920-61a0ba59-094e-4a0f-bf0a-35bab79dcd0a.png">

I tried to change my setting to your environment, but it's same  T_T
And, I try to make the build versions(ios, android) and they are normal. 

So, I think it is not a bug it's my editor setting problem(I don't know why)
If I find the solution about the editor blurry issue, then I would come back and comment here.
Thanks!! It's done!
