### ISSUE TITLE
AddCustomHeader sometimes does not add headers

### ISSUE THREAD

**Issue by Yamaneko1031** [gree/unity-webview#951]
Headers are sometimes not added when AddCustomHeader() is called immediately after Init() processing.

It seems that AddCustomHeader() can be called before "mCustomHeaders = new Hashtable<String, String>();" in init() is finished, although not every time.
Since I can't find a function to check the end of init(), is the only solution to wait for a certain amount of time?

※Currently checking on Android.

**Comment by KojiNakamaru** [comment]
Thank you for the report. I adjusted the code in #952 and updated binaries. Could you please try the latest?

**Comment by Yamaneko1031** [comment]
I tried it with the latest and the problem is solved.
Thank you for your support!
