### ISSUE TITLE
ADS don't work properly on top of the WebView on Android platform.

### ISSUE THREAD

**Issue by JalalMAR** [gree/unity-webview#963]
I have implemented advertisements to load every 2 minutes on top of the displayed content, but when the ads appear it got crashed.
Can someone suggest something can be done to solve this issue??
Thank you.

**Comment by KojiNakamaru** [comment]
If you build the app with Development Build, you can utilize https://developer.chrome.com/docs/devtools/remote-debugging/webviews/ to remotely debug your html/js content. You could get some clues about the cause.

**Comment by JalalMAR** [comment]
Thank you for your help! I've made another solution. before the AD loaded, I set the visibility of the WebView false then after close the AD set it true, and this solve the issue.
