### ISSUE TITLE
Pass a simple variable to JS

### ISSUE THREAD

**Issue by CDAfonso** [gree/unity-webview#964]
I want to pass a simple string from Unity (userName) to Webview, but It's not working.

I tryed to use this on "started", "ld"  also, but no success. 
The background color works fine, but not the variable.

```
started: (msg) =>
			{
				Debug.Log(string.Format("CallOnStarted[{0}]", msg));
				webViewObject.EvaluateJS("const name=" + userName);
				webViewObject.EvaluateJS(@"document.body.style.backgroundColor = 'blue';");
}
```

If i simply pass a string and not the variable, it works:
`webViewObject.EvaluateJS("const name='Test'");

**Comment by KojiNakamaru** [comment]
You have to enclose `userName` with `''` as `webViewObject.EvaluateJS("const name='" + userName + "'");`

**Comment by CDAfonso** [comment]
Thank you so much. My bad. It's working now!
