### ISSUE TITLE
Message from webview to unity isn't immediate, and a NullReferenceExeption

### ISSUE THREAD

**Issue by hZorah** [gree/unity-webview#971]
Hello. I have opened a sample project, and did very small changes to it. One of this changes was showing the text of the label of the Send Message button to a Unity text.

It's a WebGL build.

![image](https://github.com/gree/unity-webview/assets/62046614/29c9ba8d-a284-4a7e-86b2-e06f13aec3e0)

But when I click on the button, the change doesn't appear immediately. It shows a Null Reference Error, and  I need to click in the blue area (outside webview) to the unity text display that message.

![image](https://github.com/gree/unity-webview/assets/62046614/163d105b-ebd1-4bbc-ad82-45a569d8c507)

What could this be? Thanks in advance.

**Comment by hZorah** [comment]
I managed to get rid of the Null Reference error by cloning the repo again and opening another project...
But the text status only updates when I click outside the WebView. There's a way to make it update instantly?

**Comment by KojiNakamaru** [comment]
By checking "Run In Background" it can be updated immediately.
![image](https://github.com/gree/unity-webview/assets/2645978/242b7cbf-e537-40e6-8635-1d93ed547892)

**Comment by hZorah** [comment]
It worked! Thank you!
