### ISSUE TITLE
Local Images/Resources in StreamingAssets

### ISSUE THREAD

**Issue by freakysheep** [gree/unity-webview#98]
Is there a way to reference images from local html files in StreamingAssets?

Following setup does not work for me:

StreamingAssets
➤sample.html - with `<img src="test.jpg"> `
➤test.jpg

**Comment by KojiNakamaru** [comment]
Maybe you don't copy `test.jpg` as the sample app does for `sample.html`.
I've modified the sample app to display a local image: https://github.com/gree/unity-webview/commit/972b9dbb1029ad5fad58d8c2f2ac7a0df122595e, please check it.

**Comment by freakysheep** [comment]
Ah, thanks for your help!
