### ISSUE TITLE
What is the use of Webview.bundle folder

### ISSUE THREAD

**Issue by UnityDev524** [gree/unity-webview#986]
Hi @KojiNakamaru ,
I would like to know the use of webview.bundle folder ?
If I delete that folder will it stop working on mobile platform?

**Comment by KojiNakamaru** [comment]
It is for Editor on mac. It won't be included in apk/ipa.

**Comment by UnityDev524** [comment]
What is the use of UnityWebViewPostprocessBuild.cs ?
If I removed this then what happen?

**Comment by KojiNakamaru** [comment]
As its name expresses, it performs various post-process operations on build. 
core-1.6.0.aar was originally introduced in #743 and related code was adjusted in #744 and #748 .
