### ISSUE TITLE
Facing NullPointerException on resumeTimers()

### ISSUE THREAD

**Issue by Won-gyu** [gree/unity-webview#994]
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.resumeTimers()' on a null object reference
  at net.gree.unitywebview.CWebViewPlugin$22.run (CWebViewPlugin.java:876)
  at android.os.Handler.handleCallback (Handler.java:978)
  at android.os.Handler.dispatchMessage (Handler.java:104)
  at android.os.Looper.loopOnce (Looper.java:238)
  at android.os.Looper.loop (Looper.java:357)
  at android.app.ActivityThread.main (ActivityThread.java:8090)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1026)`

Hi, I face this exception reported in Google Play, but I don't see any crash in Unity-end. Does anyone know why this happen?
Thanks.

**Comment by KojiNakamaru** [comment]
Which version of this plugin are you using? Could you please provide the commit hash or the date you imported the plugin?

**Comment by Won-gyu** [comment]
> Which version of this plugin are you using? Could you please provide the commit hash or the date you imported the plugin?

I installed and use net.gree.unity-webview through Package Manager which has the version 1.0.0

**Comment by KojiNakamaru** [comment]
Ah, you installed through Package Manager, then, could you please check Packages/packages-lock.json ? It should have an entry like below. I would like to know this entry of yours.

```json
    "net.gree.unity-webview": {
      "version": "https://github.com/gree/unity-webview.git?path=/dist/package",
      "depth": 0,
      "source": "git",
      "dependencies": {},
      "hash": "343c17ba69fa1bc0e5698a7429c6d278ad2f905e"
    },
```

**Comment by Won-gyu** [comment]
```json
    "net.gree.unity-webview": {
      "version": "https://github.com/gree/unity-webview.git?path=/dist/package-nofragment",
      "depth": 0,
      "source": "git",
      "dependencies": {},
      "hash": "343c17ba69fa1bc0e5698a7429c6d278ad2f905e"
    }
```

Sorry for the late resonse. Here is my net.gree.unity-webview part in the packages-lock.json

**Comment by KojiNakamaru** [comment]
Thank you. Based on your report, I found a potential issue, which should be fixed in #997.  Could you please try the latest binaries?

**Comment by Won-gyu** [comment]
```json
    "net.gree.unity-webview": {
      "version": "https://github.com/gree/unity-webview.git?path=/dist/package-nofragment",
      "depth": 0,
      "source": "git",
      "dependencies": {},
      "hash": "8821de0c7de098b3a1c34ebec4143b10f87f82a4"
    },
```
Thanks! I updated to this new version.
I will deploy it and see if the exception occurs.

**Comment by Won-gyu** [comment]
It seems to be fixed. Thanks!
